### ISSUE TITLE
Frontend should handle if existing entity(conversation, prompt, file or folder) has dots in the end

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1007]
### EPAM AI DIAL chat version

0.6.9

### What happened?

Frontend should handle if existing entity(conversation, prompt, file or folder) has dots in the end:
API doesn't allow to modify such paths - 400 error

two cases:
- existing entities with dots in the end
- create manually file/folder with dots in the end in storage which allows it

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Example of current issue:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/9f6cbd52-0467-4b15-ab21-db31b41825ba)

**Comment by VolhaBazhkova** [comment]
Verified on staging, reported #1022 #1229
