### ISSUE TITLE
[Mobile] It's impossible to open chat context menu when user just logged and chat is opened for the first time

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1010]
### EPAM AI DIAL chat version

0.6.7

### What happened?
0. Create new conversation and refresh the browser
1. On mobile device click on chat name at the end of the name -> three dots appears
2. Click on three dots -> the chat is opened -> **bug**

Expected result: chat context menu should be opened
Please note also #843 issue. 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
Related to #856

**Comment by VolhaBazhkova** [comment]
Verified on staging (iPhone) successfully
