### ISSUE TITLE
Add ability to Unshare / Unpublish some file

### ISSUE THREAD

**Issue by sdryapko** [epam/ai-dial-chat#1014]
### Description

Add ability to see all shared / published files in file manager and add option to unshare / unpublish it from this view.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Found related issues:
https://github.com/epam/ai-dial-chat/issues/1287
https://github.com/epam/ai-dial-chat/issues/1283
https://github.com/epam/ai-dial-chat/issues/1281
https://github.com/epam/ai-dial-chat/issues/1272
https://github.com/epam/ai-dial-chat/issues/1263
#1292
