### ISSUE TITLE
[Chat header] Information tooltip performs poorly if system prompt is big

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#102]
Create a chat with big system prompt -> In the chat hover over chat icon
**Expected:** to add scroll

![image](https://github.com/epam/ai-dial-chat/assets/111180458/056b69ca-2fcd-4cc4-99c1-c06bd17effaa)

**Comment by avavilau** [comment]
@VolhaBazhkova  I think it would be ugly anyway. I suggest we truncate text at some point and put three dots at the end.

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. Please note reported minor issue #335
