### ISSUE TITLE
[Regression] Talk to recent models are not updated if to use model from recent list

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1025]
### EPAM AI DIAL chat version

0.6.11

### What happened?

Probably the bug appears because of #873 fix! 
1. Create 5 chats based on different models/applications, so they all appear in recent Talk to models
For example, 
![image](https://github.com/epam/ai-dial-chat/assets/111180458/4d345393-ddc9-4b3f-8d02-be455930557f)
2. Create a conversation and use the 5th model from the recent Talk to list, e.g. Cohere Command Text V14
3. Create a conversation and check the list in Talk to -> Cohere Command Text V14 is the 5th model -> **bug**

Expected: Cohere Command Text V14 is the 1st model

Note: the list is updated ok if to select a model from See full list...

https://github.com/epam/ai-dial-chat/assets/111180458/df4d0b44-025b-46a2-bd58-1fa795851b8c

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Verified on stg, no issues
