### ISSUE TITLE
It's available to open chat settings and set another model while response generating

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#103]
1. Create a new chat and send a message, e.g. Type a fairy-tail
2. While response generating, click on Conversation settings icon in chat header -\> its' opened, user can set new setting and click on Apply changes button -\> **bug**

Note: after closing the settings, the chat continues generating the response, after receiving the response no new setting are applied -\> ok

**Expected result:** can we forbid opening the setting while response generating? show "stop" icon instead of hand\\

**Comment by YauheniyaH** [comment]
issue was fixed in #2672
