### ISSUE TITLE
Scroll in chat history is moved under input message box

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1044]
### EPAM AI DIAL chat version

0.6.11

### What happened?

1. Create a chat with several message to appear vertical scroll
2. Move scroll to the bottom of the chat -> note that scroll is moved under input message box -> **bug**
![image](https://github.com/epam/ai-dial-chat/assets/111180458/7b384a0f-b074-4dff-8a80-c17071b9f18d)

https://github.com/epam/ai-dial-chat/assets/111180458/07ee4b4c-c3f4-4ce9-ab34-64c0c11be353

Expected: Scroll border should be the same as for the last response - before input message box

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Alexander-Kezik** [comment]
Also regenerate and replay mode buttons were moved to the chat input

![Image](https://github.com/epam/ai-dial-chat/assets/98586297/5ed6129e-b2ad-4952-a7ce-829dcd1667fb)

**Comment by VolhaBazhkova** [comment]
Verified along with #949 successfully
