### ISSUE TITLE
[Sharing] Incorrect message is shown on attempt to change model for shared conversation

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1053]
### EPAM AI DIAL chat version

0.6.11

### What happened?

**Steps:**
1 prepare shared conversation
2 open conversatio nsettings, select different model and click Apply changes

**Actual result:** Rename btn is shown on confirmation window

**Expected result:** Confirm btn is shown

![image](https://github.com/epam/ai-dial-chat/assets/15156585/bc6641bc-3ff5-4113-a086-a59188942df3)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Verified on STG , no issues
