### ISSUE TITLE
[Share] Shared chat should be automatically opened, so user can see chat's history

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1072]
### EPAM AI DIAL chat version

0.7.0

### What happened?

Similar to #796

1. By user1 prepare a link to a chat
2. By user2 click on the link
3. Note that chat is added to "Shared with me" (ok), but it's not on the central part -> **bug**

Expected result: shared chat should be active, it's history should be on the screen
Note: it's important to test cases separately when user2 is logged-out and logged-in!

Note: it looks like that if user has already worked in DIAL today, the link opens on shared chat (ok); but if not ..creates new conversation? The issue root cause should be investigated!

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by irinakartun** [comment]
the issue is verified on staging env
