### ISSUE TITLE
[Share] "Conversation not found" message appears of to deleted chat from "Shared with me". Expected: available chat should be selected

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1074]
### EPAM AI DIAL chat version

0.7.0

### What happened?

1. By user1 create chat1 and share it
2. By user2 open the shared link
3. Be sure that chat1 from "Share with me" section is shown in the central part -> hover over chat1 in chat panel -> click on three dots -> Delete -> confirm deleting
![image](https://github.com/epam/ai-dial-chat/assets/111180458/98e1e645-a886-41d8-93bc-6bee12d8c174)

**Actual result:**  chat1 is deleted from chat panel; on central part message appears  "Conversation not found. Please select another conversation". -> **bug** After refresh new conversation is created and becomes in focus. 

**Expected result:** the next available chat should be focused

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by irinakartun** [comment]
verified by autotests and on local env
