### ISSUE TITLE
[UI] Chat settings looks broken if to resize panels

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1080]
### EPAM AI DIAL chat version

0.7.0

### What happened?

1. Open New conversation
2. Resize Chat and Prompt panels -> note that chat settings looks broken -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/61a06fb2-f3da-4266-a381-79abafa037a2)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/9d452575-f2aa-4c95-9eeb-9ae5f8b4e70f)

**Expected result:** we need to have min width for chat settings container - TBD
**Important:** please pay attention to two cases:
1. chat settings appeared for new conversation
2. chat setting opened from chat header (expected the same behaviour as in #1100)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by mikitabut** [comment]
Looks like you can use container queries for such case - they are widely supported and looks like can be used here
https://ishadeed.com/article/css-container-query-guide/

**Comment by VolhaBazhkova** [comment]
Verified on staging env. successfully
