### ISSUE TITLE
Addons tooltips are shown one on another. It's hard to read them

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#109]
1. Create new conversation
2. Click on See all addons..
3. Select some addons and click on Add addons button
4. Hover over addons text -\> tooltip appears
5. Hover over addons icon -\> tolltip appears on the previous tooltip -\> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/d8eeaf26-a1b1-4489-b485-25c8d2fa8519)

**Expected result:** can we show one of the tooltips above the addon and another below the addon name?

**Comment by IlyaBondar** [comment]
@Derikyan , `ModelIcon` shouldn't have top-direction for consistency with other tooltips in header:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/40db24a5-5870-4689-947a-9596b8a6181c)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/74ab38f0-82ed-4796-be45-2359cf77ce38)

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully.
If to hover over addon icon, two tooltips are shown: addon name and addon description. If to hover over addon name, only tooltip with description is shown.
![image](https://github.com/epam/ai-dial-chat/assets/111180458/ea243719-5cdc-48bc-b502-dfe7ef862a41)

**Comment by AnastasiiaHarkot** [comment]
**QA Verification — Fixed ✅**

**Verified by:** AnastasiiaHarkot
**Date:** 2026-09-16
**Result:** Addons tooltips are now properly displayed without overlapping.

**Verdict: Fixed** — verified.
