### ISSUE TITLE
[Migration] It's impossible to migrate entities if their parent folders contains "." or not allowed symbols at the end

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1099]
### EPAM AI DIAL chat version

0.7.0

### What happened?

It's impossible to migrate entities if their parent folders contains "." or not allowed symbols at the end

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. Important to check on Sales env.- waiting for 0.6.13 patch there

**Comment by sr-remsha** [comment]
Documented in [user guide](https://docs.epam-rail.com/user-guide#create-1)
