### ISSUE TITLE
[Migration] If conversations do not have a last activity date, they will be migrated in the wrong order

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1106]
### EPAM AI DIAL chat version

0.7.0

### What happened?

If conversations do not have a last activity date, they will be migrated in the wrong order

Expected result:
Conversations without a last activity date should be migrated before conversations with the last activity date

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully.
Conversation without lastActivityDate is migrated successfully and appears at the bottom of the lost of migrated conversations in Today section.
Also restricted characters and dots at the end of the names are removed.
