### ISSUE TITLE
[Compare mode] PC and Tablet. Long Addon names are not fully seen on Talk to screen in Selected and Recent

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#111]
1. Use PC or tablet (with opened panels)
2. Click on Compare mode button at the bottom of Conversation panel
3. Check Addon names in Recent section (or Selected section) on Talk to screen

![image](https://github.com/epam/ai-dial-chat/assets/111180458/9a52c882-0af1-4f85-90bd-b87749befa5a)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/8265c6b1-a151-49fb-a151-a664fa908ace)

**Expected result:** we need to show the name in two rows, so 'x' button in Selected will be available

**Comment by VolhaBazhkova** [comment]
The issue is still reproduced as there is a position while panel resizing when addon names are cut and settings are shown in two columns. 
![image](https://github.com/epam/ai-dial-chat/assets/111180458/3c349f77-9948-4218-9714-2e6da2caf69f)

**Comment by YauheniyaH** [comment]
not actual with new ui implementation for New conversation
