### ISSUE TITLE
[Share] folder structure doesn't appear in Shared with me if to share folder

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1129]
### EPAM AI DIAL chat version

0.7.0

### What happened?

1. By user1 create the following folder structure 
Root folder -> Stem folder -> Leaf folder 
Move corresponding prompts to each folder
2. By user1 share the link to Stem folder
3. By user2 click on the link -> shared folder structure prompt does not appear in "Shared with me" -> **bug**
4. By user2 refresh the browser -> shared folder appears -> ok

Note: there is the same issue if to share simple folder with a chat, when there are no any more folder levels

**Expected result:** on click on the link the first available prompt should be opened automatically; root folder should appear in "Shared with me" automatically

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Discovered defect #1250 1250

**Comment by YauheniyaH** [comment]
Verified on STG, no more issues found
