### ISSUE TITLE
Support Duplicate for own conversations and prompt

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#1137]
### Description

It's quite common when conversation went a wrong way to want to save current state and create another branch from some point in history. 
Or user may want explore different option of continue of the certain conversation
Right now user had to use replay just to create a copy. 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
@Alexander-Kezik Please take care of the issue: now duplicated chat/prompt is created in Today/Recent in all cases. But expected that duplicated chat/prompt should be created in the folder where the main chat/prompt is located. Like it's done for Replay and Playback chat types.

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. Reported low-priority issue #1241

**Comment by VolhaBazhkova** [comment]
Verified on sales env 0.9.2 version successfully

**Comment by sr-remsha** [comment]
Documented:
* [Conversations](https://docs.epam-rail.com/user-guide#duplicate)
* [Prompts](https://docs.epam-rail.com/user-guide#duplicate-1)
