### ISSUE TITLE
Add the capability to use the OTLP protocol for sending metrics and traces

### ISSUE THREAD

**Issue by alexey-ban** [epam/ai-dial-chat#1138]
### Description

Add the capability to use the OTLP protocol for sending metrics and traces. I suggest use [environment varible](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#exporter-selection) to configure exporter parameters. This involves enabling the system to send metrics and traces to the desired endpoints defined via environment variables OTEL_EXPORTER_OTLP_METRICS_ENDPOINT and OTEL_EXPORTER_OTLP_TRACES_ENDPOINT. Additionally, include TraceId and SpanId in logs when tracing is enabled.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified the enhancement on staging env + Grafana with the help of Aliaksei Banshchyk.
