### ISSUE TITLE
Chat textarea height doesn't change when side panels are resized

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1150]
### EPAM AI DIAL chat version

0.7

### How to reproduce

1. Resize the sidebars and notice that the height of the textarea has not changed -> **bug**
2. Reload the page and notice that the height of the textarea has changed -> **ok**

### Actual result

https://github.com/epam/ai-dial-chat/assets/98586297/242a8877-6b7e-4dda-8aea-ddea61714b99

### Expected result

The size of the textarea should change along with resizing of the sidebars

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The fix was verified on staging environment using Opera, Edge, Chrome browsers successfully. Reported specific FF issue #1224
