### ISSUE TITLE
Nested folders are not removed from the state if the root folder is deleted

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1151]
### EPAM AI DIAL chat version

0.7

### How to reproduce

1. Create "folder 1", "folder 2", "folder 3".
2. Put "folder 3" into "folder 2" and "folder 2" into "folder 1".
3. Delete "folder 1".
4. Create "folder 1" and note that "folder 2" and "folder 3" still exist inside "folder 1" -> **bug**

### Actual result

Uploading Screen Recording 2024-03-26 at 16.13.52.mov…

### Expected result

The root folder should be deleted along with all the nested folders

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Reproduced the issue on UAT (0.8 version). Verified on staging server successfully (0.9 version)

**Comment by VolhaBazhkova** [comment]
Also re-checked on sales env successfully
