### ISSUE TITLE
Add isolated view mode

### ISSUE THREAD

**Issue by i-serebryakov07** [epam/ai-dial-chat#1154]
### Description

There is a request to have the possibility to open chat in the isolated view with limited configuration options for the selected model/application. 
For example: User needs to open GPT-4 without any additional features or configurations. Opens `https://ai-dial-chat.com/models/gpt-4` and gets simplified UI containing only chat input with GPT-4.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The feature was verified on staging environment successfully. Isolated model view can be opened by the URL like  https://server/models/model or application id. Conversation settings, conversation and prompt panels are not shown in the view. 
When chat is created from isolated view, it's named like "isolated_model_id", after the start of conversation the name is changed automatically according to DIAL requirements.
![image](https://github.com/epam/ai-dial-chat/assets/111180458/c0d1d07d-7d64-4dc6-b0db-77038f112db9)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/dba301cd-4b17-4bf5-8570-e111f4adc36e)

Note: reported #1176 (404 error in console if to open isolated model view)

Also banner for notifications is left in isolated view.

**Comment by VolhaBazhkova** [comment]
Verified on sales env 0.9.2 version successfully

**Comment by sr-remsha** [comment]
Documented in [user guide](https://docs.epam-rail.com/user-guide#isolated-view-mode)
