### ISSUE TITLE
[Mobile] Difficult to use attachments, code blocks and markup tables due to forced opening of context menu

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1156]
### EPAM AI DIAL chat version

0.7

### What happened?

Context menu appears when you try to open and use attachments, code blocks or md-table buttons.

Expected result: do not display context menu in these cases.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on mobile device on staging env successfully
User message context menu or model response context menu is not opened if to click on buttons appear in code block, stages, MD table, attachments

**Comment by VolhaBazhkova** [comment]
Verified on sales+chrome mobile view sucecssfully
