### ISSUE TITLE
Proxying AI model images via chat

### ISSUE THREAD

**Issue by alexey-ban** [epam/ai-dial-chat#1158]
### Description

Currently, DIAL have two components named "chat" and "chat-themes." Both of these containers need to be exposed externally. When trying to expose only the chat container externally, the images for the models stop working.

What is expected:
 - THEMES_CONFIG_HOST - contain internal link
 -  only chat container exposed to internet

### Use case/motivation

The requirement is to have the "chat" container proxy the images it received from "chat-themes," rather than simply redirecting to it.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
It was configured by the team on staging environment successfully

**Comment by sr-remsha** [comment]
The [comment](https://github.com/epam/ai-dial-chat/pull/1752) was added to documentation
