### ISSUE TITLE
[Mobile] Add a blackout background under the side panels 

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1159]
### Description

Now it's possible to use the chat when the side panel open (open settings, context menu, etc.)
![image](https://github.com/epam/ai-dial-chat/assets/151838896/09e7ea42-d2d0-4819-975b-a9974446fabc)

Expected: chat will be blocked by the blackout background
![image](https://github.com/epam/ai-dial-chat/assets/151838896/cc10a11e-dbb7-4af4-8f7f-9327e4aed6a8)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging (mobile device - iPhone 15) successfully
