### ISSUE TITLE
Support Cognito Auth Provider

### ISSUE THREAD

**Issue by sdryapko** [epam/ai-dial-chat#1162]
### Description

Support Cognito on front-end level.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Waiting for DevOps to install the configuration. Currently there are some problems, which is going to be discussed on daily call. We will continue implementation in separate ticket if needed after the discussions.

**Comment by sr-remsha** [comment]
Documented: 
* [Docs](https://github.com/epam/ai-dial/blob/main/docs/Deployment/idp-configuration/cognito.md)
* [Core](https://github.com/epam/ai-dial-core/blob/de88186ff8e182679695c0a46e53f67ed6c64f56/sample/aidial.settings.json#L28)
