### ISSUE TITLE
[Shared with me] no event on clicking 'Duplicate the conversation to be able to edit it' button if conversation stays in folder

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1166]
### EPAM AI DIAL chat version

0.9.0

### What happened?

**Steps:**

1 Create new conversation and move it into folder
2 Share folder with conversation
3 Accept sharing by some user and select folder conversation
4 Click on 'Duplicate the conversation to be able to edit it' button

**Expected result:** conversation is duplicated and placed under Today conversations
**Actual result:** no event on button click

https://github.com/epam/ai-dial-chat/assets/15156585/110238c6-acc5-4c81-950b-c8fd55220f54

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by irinakartun** [comment]
verified on staging env and by autotest

**Comment by VolhaBazhkova** [comment]
Verified on sales env successfully
