### ISSUE TITLE
[Mobile] the button "Scroll down" doesn't disappear for Dall-E on mobile

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1168]
### EPAM AI DIAL chat version

0.8.0

### How to reproduce

- open DIAL chat on mobile
- request picture on Dall-E
- expand generated picture (p.1)
- scroll down to see picture
- collapse picture (p.2)

### Actual result

p.1: wasn't scrolled down to see picture
p.2: the button "Scroll down" doesn't disappear

### Expected result

p.1: should be scrolled down automatically
p.2: the button "Scroll down" should disappear

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully

**Comment by VolhaBazhkova** [comment]
Verified on sales+chrome mobile view sucecssfully
