### ISSUE TITLE
[Share] The folder structure isn't available if the selected shared chat is inside these folders

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1172]
### EPAM AI DIAL chat version

0.7

### How to reproduce

1. Prepare folder structure with chat inside by "user 1" and share it (ex. folder 1/folder 2/chat 1).
2. Accept sharing by "user 2" -> "chat 1" is selected -> **ok** 
3. Reload page -> "chat 1" is selected, but notice that only root folder is visible -> **bug**.

### Actual result

https://github.com/epam/ai-dial-chat/assets/98586297/6fdf7abb-d5d2-459d-ab37-2ffdfdcaab9b

### Expected result

Folder structure should be expanded.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
**Single prompt sharing fails with error when user opens shared link**

Steps to reproduce:

1. share prompt ( in folder or outside all folders) from user1
2. open share link by user2
Actual result: link open with error on the top "An error occurred while uploading the prompt"
Prompt is visible in the right menu, but when try to View it, loading of the prompt pop up appears, but not loaded completely

<img width="1050" alt="Screenshot 2024-04-09 at 12 32 50" src="https://github.com/epam/ai-dial-chat/assets/77381071/b254eaf5-f433-4645-8591-a1006dc2e276">

<img width="471" alt="Screenshot 2024-04-09 at 12 33 51" src="https://github.com/epam/ai-dial-chat/assets/77381071/ae552598-e62a-4f7f-9e80-d992bc9a0a89">

**Comment by VolhaBazhkova** [comment]
The ticket was verified by @YauheniyaH on staging successfully.
