### ISSUE TITLE
Remove 'useOutsideAlerter' and replace by floating ui alternative 'useDismiss'

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#118]

**Comment by denys-kolomiitsev** [comment]
Revoved useOutsideAlerter from the Folder component.
Context menu should be closed if clicked outside it. Nothing visualy should be changed.

**Comment by VolhaBazhkova** [comment]
Verified chat/prompt folder menu; chat menu; prompt menu; attachments folder and attachment menu on staging server successfully.
