### ISSUE TITLE
'Conversation not found' message appears if delete all conversations

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1187]
### EPAM AI DIAL chat version

0.8

### What happened?

https://github.com/epam/ai-dial-chat/assets/98586297/a185bd27-f9f4-4f01-8144-94bdc7f91d2f

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env. successfully. If to click on "Delete all" button on conversation panel, loaders are shown on the panel and central part while conversations are being deleted; if to click on "Delete all" on prompt panel, loader is shown on prompt panel.
