### ISSUE TITLE
[Mobile] Unify the modal windows paddings

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1191]
### Description

Side paddings are 12 px, top and bottom are 16 px. 

Need to correct:
1) Attachments
![image](https://github.com/epam/ai-dial-chat/assets/151838896/a3b784dc-0622-4874-8b5e-99334ab478e1)
2) Confirm clearing
![image](https://github.com/epam/ai-dial-chat/assets/151838896/4bf098c8-26d2-4d60-b175-be1561583be2)
3) Share
![image](https://github.com/epam/ai-dial-chat/assets/151838896/abc60d3e-35a9-47bf-bb33-fc0b727c741f)
4) Some items failed to import due to duplicate names ( also add external paddings)
![image](https://github.com/epam/ai-dial-chat/assets/151838896/44d8f67b-a810-4fd8-be19-e5730b34dd1c)

5) See also #1194 
6) Replace Confirmation Modal will be fixed as part of https://github.com/epam/ai-dial-chat/issues/1230

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env. Reported #1445 , #1468 , #1473
