### ISSUE TITLE
Update error text about tokens

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1196]
### EPAM AI DIAL chat version

0.8.0

### What happened?

Update error text about tokens: append "1 token approximately equals to 4 characters"

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The text was updated to the following one:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/ce7ee71b-56d9-4b65-b20d-0744f971e6ab)
