### ISSUE TITLE
[Folder sharing]: lowest level folder conversation is opened if share root folder 

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1202]
### EPAM AI DIAL chat version

0.9.0

### What happened?

**Steps:**

1 Prepare 4 levels folder hierarhy and put conversation in each folder
2 Share root folder
3 Open share link by some user

**Expected result:** root folder conversation is selected in chat panel
Note: Need to check sharing folder inside hierarchy in the middle ( not lowest).
E.g. 
1. Root folder->Stem folder-> Leaf folder with chat inside each folder
2. user 1 share stem folder
3. user 2 open shared link see chat from root folder

**Actual result:** lowest level folder conversation is selected in chat panel

related issue about prompts #1250 

https://github.com/epam/ai-dial-chat/assets/15156585/31d3a5a6-6ec3-4ec9-82d4-8b678ab48484

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
