### ISSUE TITLE
Incorrect import error is shown if to import prompt through chat import button

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1223]
### EPAM AI DIAL chat version

0.6.0

### What happened?

Import attached file with a prompt through import button located on conversations panel -> "Import failed" error appears -> **bug**
[epam_ai_dial_-_review_chat_prompt_4-8 (1).json](https://github.com/epam/ai-dial-chat/files/14917785/epam_ai_dial_-_review_chat_prompt_4-8.1.json)

**Note:** if to export a prompt from DIAL and export it using conversation import -> "unsupported data format" error appears -> ok
QA: need to investigate the difference of structures and update our test cases accordingly

**Expected result:** 
1) need to show correct error about unsupported formats; 
2) Need to update the text of the error to be more specific. For example, "Import of prompts failed", "Import of conversations failed", "Import of prompts failed because of unsupported data format", "Import of conversations failed because of unsupported data format"

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Verified on STG successfully
