### ISSUE TITLE
[Manage attachments]: Add tooltip for files' long names

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1227]
### EPAM AI DIAL chat version

0.9.0

### How to reproduce

1. Create conversation with attachment ( e.g. image)
2. export conversation with attachment
3. import just exported conversation with postfix
4. Open Manage Attachments pop up import folder
5. Hover on file name

### Actual result

tooltip with full file's name is not displayed
![Screenshot 2024-04-09 at 14 38 17](https://github.com/epam/ai-dial-chat/assets/77381071/93270808-9894-487a-a14d-46f9bc5ad136)

Note: tooltip also absent for chats and prompts with long names when name is wider that chat's/prompt's area

### Expected result

 need to display tooltips for long file names on hover
need to add tooltips for long names for chats and prompts

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
