### ISSUE TITLE
Nothing happens if to import file when the same exists

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#123]
1. Create a chat with some messages
2. Export the file
3. Continue conversation in the chat
4. Import the file -\> nothing happens, imported file is ignored

**Expected result:** need to discuss import feature. Should we show any warning message that the file already exists? Should we show the warning and allow to import new file with the same name and id?

**Comment by YauheniyaH** [comment]
implemented in #609
