### ISSUE TITLE
Reduce the height of modal window "Some items failed to import..."

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1230]
### EPAM AI DIAL chat version

0.9.0

### What happened?

Current
![image](https://github.com/epam/ai-dial-chat/assets/151838896/f3ab45ca-cdb9-42c0-89dc-25a49421f59b)

Let's make the height the same as in "manage attachments" window:
1. Little content -> fixed height (595px)
2. Lots of content (on screen)  -> flexible height
3. Lots of content (off screen)  -> max height + scroll

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
