### ISSUE TITLE
Center text on buttons in modal window "Some items failed to import..."

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1231]
### EPAM AI DIAL chat version

0.9.0

### What happened?

![image](https://github.com/epam/ai-dial-chat/assets/151838896/a1bef602-32cb-4679-b669-d9db746b6c56)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
