### ISSUE TITLE
Import: Postfix for duplicated files starts with number 2

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1234]
### EPAM AI DIAL chat version

0.9.0

### How to reproduce

1. Create "Chat_with_file" with attachment "file.png"
2. Export "Chat_with_file" with attachment
3. Import zip file with option postfix for chat ( only 1 dialog appeared)
4. Import zip file again with postfix option for file and chat

### Actual result

3. New "Chat_with_file 1" was created, attached file has original name  "file.png" ( without postfix)
4. New "Chat_with_file 2" was created,  attached file has name "file 2.png" (with postfix 2)

### Expected result

4. Postfix for files should start with 1 as for chats and prompts, file name should be "file 1.png"

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
