### ISSUE TITLE
Import chat with attachments: Show one dialog for conversation and file to select options for duplicates

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1237]
### EPAM AI DIAL chat version

0.9.0

### How to reproduce

1. Create "Chat with file"
2. Export "Chat with file" with attachments
3. Import zip file, select postfix option
4. Import one more time zip file

### Actual result

2 dialogs are displayed :
for file and for chat
![Screenshot 2024-04-10 at 12 09 57](https://github.com/epam/ai-dial-chat/assets/77381071/73274d30-a2b1-41a7-9c49-02b3223d9d5b)
![Screenshot 2024-04-10 at 12 10 10](https://github.com/epam/ai-dial-chat/assets/77381071/4fd54cf5-ffeb-4858-bd93-a71ecdd2fbee)

### Expected result

Show one dialog for conversation and file for selecting options for duplicates

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The new window was verified on staging env successfully. Reported regression issue #1952

**Comment by sr-remsha** [comment]
Updated [Conversation Import](https://docs.epam-rail.com/user-guide#import) in user guide.
