### ISSUE TITLE
Import chat with attachment check duplicates in Imports folder only, not the original path

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1239]
### EPAM AI DIAL chat version

0.9.0

### How to reproduce

1. Create "Chat with file" 
2. Export "Chat with file" selecting with attachments option
3. Import exported zip 

### Actual result

Dialog about option with duplicates  appeared for chat only
No dialog for file

It happens because file duplicates are checked in Imports folder, not in original path

### Expected result

Need to check duplicates of file names in original path of the chat (appdata/...)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The ticket was verified on staging successfully. Note that there is #1453 , so, user has to refresh the browser to see the created with postfix file in Manage attachments
