### ISSUE TITLE
Folders from "Shared with me" are exported thru "Export conversation without attachments" at the bottom of the conversations panel

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1243]
### EPAM AI DIAL chat version

0.6.0

### What happened?

1. By user1 create some hierarchy to share folder, chat
2. By user2 click on the link to have "Shared with me"
3. By user2 create some folders/chats in Pinned/Today
4. By user2 export the whole structure using the export button at the bottom of the chat panel
5. By user3 import the structure and check that "Shared with me" is not imported; only chats from Pinned/Today are imported -> chats from Shared with me are not imported (ok), but folder yes -> **bug**

Note: after browser refresh these folders disappear as they are empty
**Note:** seems the same issue could be for prompts, please, re-check.

![image](https://github.com/epam/ai-dial-chat/assets/111180458/6aa64eba-f14e-4281-ac61-719c55a8d025)

**Expected result:** "Shared with me" structure is NOT exported thru "Export conversation without attachments" button at the bottom of the conversations panel

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Issue is fixed , not reproducible any more on staging 0.14.0
