### ISSUE TITLE
Imported duplicated chat with attachment has link to file in appdata if Ignore option was selected for file

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1244]
### EPAM AI DIAL chat version

0.9.0

### How to reproduce

1. Create "Chat with file"
2. Export "Chat with file"
3. Import zip file , select postfix option for chat -> new chat was created with  postfix, file was added to Imports folder
4. Delete file from imported folder and upload new with the same filename
5. Import zip file again, select ignore for file, postfix- for chat

### Actual result

New Chat was created, original image is displayed in chat details, because chat has link to file in appdata folder
The same behaviour if select ignore - for file, Replace - for chat

### Expected result

New chat should have link to file in imported folder.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The ticket was fixed along with #1239 and #1420, verified on staging env successfully
