### ISSUE TITLE
UI: Shared prompt dialog has incorrect colors of buttons

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1249]
### EPAM AI DIAL chat version

0.9.0

### How to reproduce

![MicrosoftTeams-image (23)](https://github.com/epam/ai-dial-chat/assets/77381071/e40595e6-4329-4f2f-b218-17036ae8178d)

### Actual result

1. Buttons Export prompt and Delete prompt are black
2. 2. Botton Duplicate prompt is blue and it seems that user have to duplicate prompt, as no other options

### Expected result

1. Buttons Export prompt and Delete prompt should be in grey color
2. Botton Duplicate prompt should be white with black letters 
![MicrosoftTeams-image (24)](https://github.com/epam/ai-dial-chat/assets/77381071/c6c463f9-7dbb-4b9c-8eae-9e37d0d79fcc)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging in light and dark themes successfully. See also #1327
