### ISSUE TITLE
When open link with shared prompt folder from nested structure, dialog about 'root' prompt from the root folder should be shown

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1250]
### EPAM AI DIAL chat version

0.9.0

### How to reproduce

1. By user1 create the following folder structure
2. Root folder -> Stem folder -> Leaf folder
3. Move corresponding prompts to each folder
4. By user1 share the link to Stem folder
5. By user2 click on the link -> shared folder structure prompt appeared, dialog with Leaf prompt is displayed -> bug
6. By user1 share the link to Root folder 
7. By user2 click on the link -> shared folder structure prompt appeared, dialog with Root prompt is displayed 

### Actual result

When sharing prompt folder from the structure leaf prompt is displayed when open shared link

### Expected result

When sharing prompt folder from nested prompt folder structure with prompts inside, the chat from root folder should be shown  in dialog about Duplicate/Export/Delete
The same logic is applied for sharing chats: the root chat should be in focus when open shared folder from structure. there is a bug #1202 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
