### ISSUE TITLE
User not able to upload file or attach from uploaded when edit original chat message

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1263]
### EPAM AI DIAL chat version

0.10.0

### How to reproduce

Steps to reproduce:
1. Create chat with attachment ( Dial RAG or Echo)
2. Click on Edit chat icon
3. Click on Attach files icon

### Actual result

Menu with attach option is NOT displayed
![image](https://github.com/epam/ai-dial-chat/assets/77381071/042ef4fe-eb3c-4687-8722-f177888f7fe7)

### Expected result

Attach options should be displayed:
1. Attach uploaded files
2. Upload from device 

Note: attach options work correctly for input new text/prompt
![image](https://github.com/epam/ai-dial-chat/assets/77381071/ea7a855e-43b7-4af1-a0a0-1abee314d711)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
