### ISSUE TITLE
Infinite spinner

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1265]
### EPAM AI DIAL chat version

0.6.17

### How to reproduce

Open 0.6.17 in incognito mode (`selectedConversationIds: []`)

### Actual result

Infinite spinner is displayed

### Expected result

New conversation should be created

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on 0.6.19 version on Prod successfully
