### ISSUE TITLE
Need to make side panels resizable

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#128]
Need to allow users to change panels size.
Please be sure that panel size is stored if user collapses/expands panels, refresh the browser.
Check also long conversation/prompt name while resizing of panels. Note that chat can be named by DIAL or renamed by user.

**Comment by IlyaBondar** [comment]
@denys-kolomiitsev , pay attention on this panel also
![image](https://github.com/epam/ai-dial-chat/assets/20163971/1d057b2f-b013-47ea-84f6-6130dfc3cb67)

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. 
Please note the following:
1. On mobile there is no resized panels feature as it will be inconvenient
2. Min size is 260px
3. Max size is 45% from container width
4. Issue #336
