### ISSUE TITLE
Add 'Shared with me' section for shared files in Manage Attachments and Attach files forms

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1283]
### EPAM AI DIAL chat version

0.10.0

### How to reproduce

Steps to reproduce:
1. User1 create chat with attachment
2. User1 share created chat
3. User2 open shared link
4. User2 open Manage attachments form
5. User2 create new chat where there is option to attach file
6. User2 click on Attach icon, select Attach uploaded file

### Actual result

4. Shared file in not displayed on the Manage Attachment form

6. Shared file is not displayed on Attach file form

### Expected result

Add 'Shared with me' section for shared files in Manage Attachments and Attach files forms

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by sr-remsha** [comment]
Included Shared with me section in attachments manager section in[ user guide](https://docs.epam-rail.com/user-guide#attachments-manager).

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
