### ISSUE TITLE
Need to add addon icon to the received stages

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#129]
> Addon's stages for assistants with Addon icon and name

Example (the link is available for DIAL dev team only): [DIAL Chat – Figma](https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=1483-7257&mode=design&t=GmNhFL5pJvFGzgS3-0)

From Figma:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/cabc2a17-289c-4b42-ab79-0d8ab62cc451)

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. Addon name and tooltip on hover exist on stage.
![image](https://github.com/epam/ai-dial-chat/assets/111180458/e0716549-1187-433c-b53c-1089831d2194)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/f466f9ac-758b-4650-832e-2b873fc756f0)

**Comment by AnastasiiaHarkot** [comment]
**QA Verification — Fixed ✅**

**Verified by:** AnastasiiaHarkot
**Date:** 2026-09-16
**Result:** Addon icon is now properly displayed on the received stages.

**Verdict: Fixed** — verified.
