### ISSUE TITLE
Attachment still marked as shared when related chat was unshared

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1292]
### EPAM AI DIAL chat version

0.10.0

### How to reproduce

1. User 1 create chat with file pdf (DIAL RAG or echo)
2. User1 share chat with file
3. User2 open shared link
4. User1 open shared chat
5. User1 revoke access to this file chat
6. User1 open Manage Attacghment form and find file attached to the chat

### Actual result

File is still marked as shared : arrow is displayed on the file icon
![image](https://github.com/epam/ai-dial-chat/assets/77381071/dddc501c-fac4-42bc-9d79-bbf90be12e46)

Note: file also is not unshared when user1 change model to shared chat

### Expected result

 File should be shown as unshared ( without arrow on file icon)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
will be fixed in core team in https://github.com/epam/ai-dial-core/issues/310

**Comment by VolhaBazhkova** [comment]
Agreed with @sdryapko on daily-status-call that it's expected behavior.
