### ISSUE TITLE
Tables with "," in cells are copied incorrectly

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1302]
### EPAM AI DIAL chat version

0.6

### How to reproduce

1. Ask the model to write you a table, with commas in the cells. (Prompt example: Top 10 IT companies. Send me an MD table. Add ", Inc" to each company).
2. Copy the table in CSV format.
3. Paste into excel/google sheets -> more columns -> **bug**

### Actual result

When copying a table in csv format, if there are commas in the cells, extra columns will appear.

### Expected result

The cells are displayed as they should be.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully.
Now if to paste CSV to Excel/google and continue with Text Import Wizard with Comma as delimiter, values separated by comma are added into one column.
 
![image](https://github.com/epam/ai-dial-chat/assets/111180458/cd923a02-69e2-4989-a0b4-27605b14f3f4)
