### ISSUE TITLE
[Mobile] Incorrect menu colour in chat history

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1305]
### EPAM AI DIAL chat version

0.10.0

### What happened?

1. On mobile device open any chat with some history
2. Note that there are different types of context menu highlighting -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/83677421-f3c7-4442-b186-ea64b4b8d7ac)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/608f0f4e-3152-47ae-9470-dbe53d53f8bc)

**Expected result:** context menu should be highlighted using blue background colour (no green, no text highlight)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Please change background color to blue

**Comment by YauheniyaH** [comment]
verified on stg
