### ISSUE TITLE
[Attach link] Chat name is not cut to 160 symbols if the chat is named as link title automatically

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1313]
### EPAM AI DIAL chat version

0.10.0

### What happened?

*Preparation:*

1. Create chat based on DIAL RAG application
2. In input message field click on Clip -> Attach link 
3. Copy-paste any site address to Address field (example, https://www.epam.com/)
4. Type Title ~200 symbols. For example, 
Lorem ipsum dolor sit amet consectetur adipiscing elit. Donec efficitur ullamcorper mauris vel efficitur enim venenatis in. Phasellus fermentum quam sed lacinia fermentum. Ut vitae ullamcorper odio!!
5. Click on Attach
6. Send the message

*Steps:*
Check chat name in chat header and conversation panel (hover over the chat name in chat header or copy-paste the name in edit mode on conversation panel) -> Conversation name is not cut -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/1ef74420-7ad2-4473-b801-476d5049065f)

**Expected result:** chat name should be cut to 160 symbols
Note: Please do the same fix if to name the chat using link only (add link); using attachment name (for example, .png in attachment)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on stg - fixed
