### ISSUE TITLE
UI: On hover buttons  Export and Delete should be blue on prompt view pop-up

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1327]
### EPAM AI DIAL chat version

0.10.0

### How to reproduce

1. user1 create prompt and share it
2. user2 open shared link -> View pop-up is open
3. user2 hover export and delete buttons-> change color to purple

### Actual result

hover buttons become purple 
![image](https://github.com/epam/ai-dial-chat/assets/77381071/59c89c38-d7a8-4861-90f7-4628f4ac3a05)

### Expected result

According to design buttons in cetral part should be blue https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3827-9180&mode=design&t=LI2zsIest2gVynKX-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Returned to developer as the issue is still reproduced (0.12 version). Need to re-check the PR

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
