### ISSUE TITLE
[Attachments] Error message "Not allowed to have folders with same names" stays on "Select folder" window if to reopen it

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1337]
### EPAM AI DIAL chat version

0.10.0

### What happened?

1. Click on Clip icon on Conversations panel
2. Click on Upload from device button
3. Close window pop-up and click on Change
4. Click on Create New folder button
5. Click on Create New folder button and rename the folder to be the same as previous one
6. Click on Confirm button -> Error message "Not allowed to have folders with same names" appears on Select folder window -> ok, the folder name is returned to initial one (ok), but edit mode is closed (is it ok?)
7. Close the window on X
8. Click on Change in "Upload to" field -> Note that the Error message is still on the Select folder window -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/d61ca94b-a8dc-4c76-b05b-62a0f275d230)

**Expected result:** 
6. Now edit mode is closed. But if there is a dot at the end of folder name, edit mode stays on after the error. We need to discuss and choose one type of behavior
8. The error should disappear at least if to reopen Select folder window. TBD if we can close it earlier

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on STG
