### ISSUE TITLE
[Attachments] Select folder screen:  "Create new folder" borders are not highlighted when background is changed on hover

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1338]
### EPAM AI DIAL chat version

0.10.0

### What happened?

There is one position when hover over Select Folder icon, background is changed (ok), but folder icon is not blue

![image](https://github.com/epam/ai-dial-chat/assets/111180458/4a82dbcf-1749-40b1-81f7-f4ac055445fa)

**Expected result:**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/5a1382a1-d331-4474-aa07-e569701ab786)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on STG
