### ISSUE TITLE
[Attachments] Nested folders disappear if to rename parent folder

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1339]
### EPAM AI DIAL chat version

0.10.0

### What happened?

1. Click on Clip icon on Conversations panel
2. Click on Create new folder button -> click on tick to close Edit mode
3. Hover over just created folder to appear three dots menu
4. Click on three dots menu -> click on "Add new folder" item menu -> click on tick to close Edit mode
5. Hover over PARENT folder -> click on three dots menu -> click on Rename
6. Type new name for parent folder and click on tick -> folder is renamed (ok), but child folder disappears -> **bug**

https://github.com/epam/ai-dial-chat/assets/111180458/2c0557f8-a9d3-47b3-a7b6-5585ade265be

**Expected result:** nested folders should not disappear if to rename parent folder

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on stg
