### ISSUE TITLE
[Attachments] Folder with default name is in Edit mode if to collapse and expand  All files (the same issue if to expand any parent folder with nested ones inside)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1340]
### EPAM AI DIAL chat version

0.10.0

### What happened?

1. Click on Clip icon on Conversations panel
2. Click on Create new folder button -> click on tick to close Edit mode (New folder 1 is created)
3. Create one more folder -> click on tick to close Edit mode (New folder 2 is created)
4. Click on All files to collapse all the folders 
5. Click on All files again to expand all the folders -> note that New folder 2 is in edit mode -> **bug**

Note: the same issue if to collapse/expand any parent folder

https://github.com/epam/ai-dial-chat/assets/111180458/d091ff2f-17d6-4938-af4c-ef2a77301a74

**Expected result:** edit mode should not be opened automatically if it was closed once

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on STG
