### ISSUE TITLE
[Talk to] [UI] Model version is not right-aligned if there is also an icon to expand long description

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1346]
### EPAM AI DIAL chat version

0.10.0

### What happened?

Found this type of configuration on Prod server
![image](https://github.com/epam/ai-dial-chat/assets/111180458/93a8eec2-4b6a-45b9-9580-5518046755a2)

Now we don't have the same case on staging

Expected: TBD

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
The ticket can not be checked in staging because the env does not have any model with description to be expanded and also with versions of model.

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
![image](https://github.com/epam/ai-dial-chat/assets/111180458/7e936252-0bda-4fa7-a21f-6550c79fa5e1)
