### ISSUE TITLE
[UI] Divider color on chat settings is incorrect

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1349]
### EPAM AI DIAL chat version

0.10.0

### What happened?

While working with custom theme "Light orange' it appears that we have incorrect color for dividers on chat settings screens (initial and opened from chat header). 

![image](https://github.com/epam/ai-dial-chat/assets/111180458/a8ca7996-de4f-442d-9b8a-d1373caddc8c)

**Expected result:**
Dividers should have the same color.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by denys-kolomiitsev** [comment]
**Tech comment**
We should add `divider-<x or y>` and `divider-<divider color>` classes to the relevant elements.

**Comment by VolhaBazhkova** [comment]
closing the ticket as it's not valid anymore due to new design. No we have different pop-ups for changing agent and configure settings
