### ISSUE TITLE
[Attachments] Files becomes unchecked if they were downloaded

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1350]
### EPAM AI DIAL chat version

0.10.0

### What happened?

1. Click on Clip icon on Conversation panel
2. Select several files (hover over the file and click on check box)
3. Click on Download icon at the bottom of the window (left corner) -> files are downloaded (ok), but become unchecked -> **bug**

**Expected result:** files should stay selected
**Note:** A file stay selected if to check it and download thru context menu (ok)

![image](https://github.com/epam/ai-dial-chat/assets/111180458/52655ca5-4f6b-4a14-a44c-42ba86f8b12a)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
tested on STG , no issues
