### ISSUE TITLE
Implement Okta provider Auth

### ISSUE THREAD

**Issue by mcandio** [epam/ai-dial-chat#1360]
### Description

This feature extends the scope of available Auth providers introducing Okta.

### Use case/motivation

I'm trying to contribute to DIAL and at the same time cover the needs of customers.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified that user logged in via Okta can work with two applications (necessary for the customer), the same user logged in via Keycloak doesn't see the same applocations. Configuration was checked with DevOps team.

**Comment by sr-remsha** [comment]
Added [IDP instruction](https://github.com/epam/ai-dial/blob/main/docs/Deployment/idp-configuration/okta.md) and example in the [Core documentation](https://github.com/epam/ai-dial-core/blob/de88186ff8e182679695c0a46e53f67ed6c64f56/sample/aidial.settings.json#L48)
