### ISSUE TITLE
[Share] Sharing is failed if to share a chat with attached link

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1372]
### EPAM AI DIAL chat version

0.10.0

### What happened?

1. Create a chat based on the app with works with links (e.g. DIAL RAG on dev env)
2. Click on Clip icon in input message -> click on Attach link -> fill in all required fields and send the message
3. Open context menu for the chat on conversation panel -> click on Share menu item -> error appears -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/8d5a19cd-2e82-492b-a34a-daa1ef029b80)

**Expected result:** share link is created; chat is shared by user1; appears in Shared with me for user2

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by irinakartun** [comment]
verified on staging env

**Comment by VolhaBazhkova** [comment]
Verified on UAT env. (0.10.2 version) successfully. For testing purposes imported chat was used as Attach link feature is disabled there.
