### ISSUE TITLE
It's impossible to exit playback mode or delete a chat in payback mode

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1378]
### EPAM AI DIAL chat version

0.11.0

### What happened?

Regression issue in 0.11 version. It's not reproduced on 0.10 and 0.9 versions

1. Create a chat with some messages
2. Create Playback version of the chat
3. Click on next several times to have text in chat history and click on Stop playback, which is in chat header
-> error appears -> bug
![image](https://github.com/epam/ai-dial-chat/assets/111180458/ac03e438-1644-4ff6-9a17-d2c622af7a4e)
4. Refresh browser -> the chat in playback is on the screen and also it's copy is created -> bug
5. Delete these chats -> 500 error in console -> bug

**Expected result:** Stop playback should change the mode of the chat (exit playback and make the chat like regular one)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by irinakartun** [comment]
verified on staging env
