### ISSUE TITLE
[Feature] support Playback-mode in Overlay 

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1403]
### Description

1) the Playback-conversation should be published and avalable for target audience
2) should update Playback-logic to avoid saving playback-index into Storage (store only locally in state)
3) hide "Stop playback" button for published with me conversations
4) allow to publish Playback-conversations 
5) add new option to the `ChatOverlayOptions` like overalay `overlayConversationId` to use for Overlay this conversation always, and be able to set it through the `setOverlayOptions`.

### Use case/motivation

We want to host some demo Overlay with Playback-conversation

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Checked on STG :
For Replay chat there is no option Publish

**Note 01:** In case Replay chat is inside folder and user create Publish request for folder, then request will be created successfully.
Need to discuss correct behaviour

**Note 02:** Does share and Publish option should be available on Playback chat?

**Comment by YauheniyaH** [comment]
related defects
 #1469
#1470

**Comment by VolhaBazhkova** [comment]
Verified the enhancement locally.
Steps are the following:
1. Create a chat with Plotly graph -> Create Playback version of the chat -> Publish playback chat, so, it appears in Organization structure -> Remember the ID of the chat (for example, select the chat and find it's ID in local store)
2. In app > cases> overlay > page.tsx update "overlayConversationId"
3. Compile and open Overlay in localhost -> Playback chat is shown, next/back arrow are working (hot keys are working)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/6224dbc5-ff22-4df7-87a5-d5b8eb7bde6a)

Note: there is one blocking issue waiting to be fixed on BE side. Error is shown if to open Chart from published playback chat. https://github.com/epam/ai-dial-core/issues/348
