### ISSUE TITLE
The arrow near user_name menu stays in expanded mode when any menu item is opened

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#141]
1. Open DIAL app, note the position of arrow in user_name menu -\>

![image](https://github.com/epam/ai-dial-chat/assets/111180458/219429b9-283b-4c31-ab75-cda2340ecae1)  \-\> correct position of the arrow

2. Click on the arrow -\> menu is opened, note the arrow position -\>

![image](https://github.com/epam/ai-dial-chat/assets/111180458/e00592cd-094c-46fe-b399-38fb8044778c) \-\> correct

3. Click on Settings -\> the menu is closed automatically (Ok), the position of arrow stays the same -\> **bug**
![image](https://github.com/epam/ai-dial-chat/assets/111180458/c6c82e31-7687-45bc-8681-f9974ac5bc8c)

4. Close Setting window -\> the arrow also stays in expanded position -\> **bug**

   **Expected result:** Arrow should be in collapsed mode when the menu is closed

   **Note:** it's ok if to collapse/expand the menu on arrow only; or the menu is closed automatically, when user clicks on any DIAL area

**Comment by YauheniyaH** [comment]
verified on staging successfully
