### ISSUE TITLE
An error shown if to clear conversation messages while response is generating

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1414]
### EPAM AI DIAL chat version

0.6.19

### What happened?

**Steps:**
1 Start chat with any model
2 Send several messages
3 Send a request that suppose a long response
4 Press 'Clear conversation messages' button in the chat header while response is generating
5 Refresh page

**Actual result:** last request is preserved, error is shown
**Expected result:** all messages are removed, conversation settings popup is shown

![image](https://github.com/epam/ai-dial-chat/assets/15156585/682fc8ed-f22e-48df-bade-b05eb2dc825f)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
For DIal RAG:

Steps:

1. create a request to model
2. while model responding , click "clear conversation messages" icon on the top
3. confirm deletion

**Actual result**

1. Request and response were removed,
2. main form for selecting model is displayed
3. user can not select any other conversation on side panel



NOTE: for Palm model side panel is not blocked

**Expected result**
"clear conversation messages" should not be available during model response generation

**Comment by YauheniyaH** [comment]
verified on staging successfully
