### ISSUE TITLE
Conversation settings popup is jumping if opened while response generating

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1417]
### EPAM AI DIAL chat version

0.6.19

### What happened?

**Steps:**
1 Start chat with any model
2 Send a request that suppose a long response
3 Press 'Conversation settings' button in the chat header while response is generating

**Actual result:** settings popup is jumping
**Expected result:** Conversation settings btn should be disabled until response is received. Probably, toolip should be shown on hover to inform user that settings cannot be changes until response received

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
issue was fixed in #2672
