### ISSUE TITLE
Publish: Publication request/section should be collapsible 

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1430]
### EPAM AI DIAL chat version

0.11.0

### How to reproduce

- expand any publication request/section
![image](https://github.com/epam/ai-dial-chat/assets/20163971/8f337821-0973-46a1-9a2a-583b3ca188f7)
- try to collapse it

### Actual result

The publication request can't be collapsed

### Expected result

The publication request should be collapsible to be consistent with all other collapsible sections on our UI

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
![image](https://github.com/epam/ai-dial-chat/assets/20163971/eef08948-401d-4fcf-99ae-b187c40357e8)
but should be upload once

**Comment by YauheniyaH** [comment]
Verified on STG - fixed
