### ISSUE TITLE
Replay-conversation shouldn't be available for sharing and publishing

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1435]
### EPAM AI DIAL chat version

0.6.19

### How to reproduce

- create Replay-conversation
- check context menu options: Share and Publish options are hidden
![image](https://github.com/epam/ai-dial-chat/assets/20163971/38ca9cc9-c706-436b-b8fa-23b14280fee9)
- click "Start Replay" and stop it when any messages appears
- check context menu

### Actual result

Share and Publish options are available
![image](https://github.com/epam/ai-dial-chat/assets/20163971/648fa89c-fe75-4a7d-87d1-b02166f84e08)

### Expected result

Share and Publish options should be hidden for Replay-conversation always
TBD: Also should we need to hide Playback and Replay options? 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
