### ISSUE TITLE
Publish: add selectors to publish and unpublish dialogs

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1439]
### Description

It's required to add the ability to select items when creating a request to publish or unpublish a folder

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
related issues 
#1801 
#1805 
#1812
#1853
#1867
#1876

**Comment by YauheniyaH** [comment]
Open questions:
1. Chats with files can be published without files or it should be not allowed?
2. Can chat with files be unpublished without files ( unpublish only chat, files still remain published)?

Current behaviour: if uncheck file from request for chat with attached files, but request will have the files in request on Admin form

**Comment by VolhaBazhkova** [comment]
Closing the ticket as there is still no design session was organized.
