### ISSUE TITLE
Fix export/import of Replay-conversations

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1451]
### EPAM AI DIAL chat version

0.6.19

### How to reproduce

Issue 1 with attachments:
- create Vision conversation with several user-messages and attachments in each of then
- create Replay for this conversation
- export it with attachments and import back 
- start replay in imported conversation

Issue 2 with attachments:
- create Dall-E conversation (with attachment in each content-message)
- create Replay for this conversation
- start replay and pause after 1-2 content-messages appears
- export this conversation with attachments and import back 
- start replay in imported conversation

### Actual result

Issue 1 with attachments: attachments weren't exported
Issue 2 with attachments: not all attachments were exported

### Expected result

Issue 1 with attachments: all attachments should be exported and imported back
Issue 2 with attachments: all attachments replay and content should be exported

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
