### ISSUE TITLE
[Publication]: Add filters for unpublish request details form

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1460]
### EPAM AI DIAL chat version

0.12.0

### How to reproduce

Preconditions:
1. user create chat
2.  user create publish request 
3.  change Publish to path , add folder
4. add filter for new folder
5. submit request
6. Admin approve request

Steps:
1. create unpublish request for published chat
2. go to admin area and review Target Audience Filters section

### Actual result

For all unpublish requests in Target Audience Filters displayed 
"This publication will be available to all users in the organization"

### Expected result

Need to display filter which were applied to chat/prompt/folder while publish
[Question for designer]:
In case no folders was applied, then need to display "This publication will be available to all users in the organization" but the font make the same as "Path" text 
<img width="686" alt="image" src="https://github.com/epam/ai-dial-chat/assets/77381071/3788d70e-eb72-465a-9bbf-9038ac8121af">

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Alexander-Kezik** [comment]
Resolved in #1640
