### ISSUE TITLE
[Mobile][Publication]: Need to unify the modal windows paddings on Publication screens

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1473]
### EPAM AI DIAL chat version

0.12.0

### What happened?

Similar ticket for the rest of windows is #1191 
**Expected:** Side paddings are 12 px, top and bottom are 16 px.
**Actual, for example:**
Select folders 16px, 24px (opened from published and from **attachments** please, fix both)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/2a93e8d2-35f8-4479-a6bd-110411e60ad5)

Publication request for conversation
![image](https://github.com/epam/ai-dial-chat/assets/111180458/1df3ada8-ab87-4bb1-9a4c-b019944fe9d6)

Please be sure the check all publication modals, e.g. publish prompt, approve the prompt by admin. For example,
![image](https://github.com/epam/ai-dial-chat/assets/111180458/5f9490e3-ffa7-4340-b1d5-47fc6c1b1bf0)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
@DaryaKarniyenka Let's discuss windows on the 2nd screenshot. Probably it's another type of window and 20px is ok there?

[Volha 6/10/2024] Discussed that there is the same rule for Publishing windows (12 px sides; 16 px top and bottom)

**Comment by YauheniyaH** [comment]
Verified on stg - fixed
