### ISSUE TITLE
[Publication]: Error notifications adjustment 

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1481]
### EPAM AI DIAL chat version

0.12.0

### How to reproduce

Case1:
Precondition:
user has chat01
user create 2 or more publication requests for chat01 ( the same requests, to the same path)

Steps:
1. admin approve one of the publication requests for chat01
2. admin click Approve button for another publication request for chat01 ->error message "Publication approving failed." -> bug

Case2:
Precondition:
user has folder01 with chat01, chat02, chat03 in it
user created publish request for the folder
admin approve publish request

Steps:
1. user create another publish request for the folder01 - > error message "Publication failed. Please try again later" -> bug

Case 3
Stesp:

1.  user created chat01 
2.  user created publish request for chat into new folder01 inside Organization ( Publish to Organization/folder01/chat01)
3. user set filter for folder01, which is nit available for himself ( e.g. user is developer, but filter is only for BA)
4. admin approves the publish request
5. user create another publish request for any chat to the same folder01  -> error message "Rules uploading failed"

<img width="1106" alt="image" src="https://github.com/epam/ai-dial-chat/assets/77381071/5d9cde13-3104-43da-9f55-31433d1f8147">

### Actual result

Error messages do not give explanation why publish requests can not be made

### Expected result

Error message should contain meaningful description of  the case happen and how it can be avoided of fixed ( if applicable)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
**Case 4**

Steps:
1. crate folder01 with chat01
2. create publish request for folder01 with some rules
3. admin approve publication request
4. user create unpublish request for folder01
5. admin approve unpublish request
6. user create new folder01 with chat01 

Actual result: error message appears "Rules uploading failed". It happens because when unpublish folder, then rules applied to this folder are not removed. Also submit request fail with error

Expected result: TBD need to create error message which will be informative for user but not expose folder name or other info about inner storage structure

**Comment by YauheniyaH** [comment]
Preconditions:
user published Chat01 with File01, chat available in Organization section

Steps:
1. User rename Chat01 to Chat01_remaned
2. user create publish request to the same path as Chat01 was published
3. send request

Actual result: error message is displayed that publication can be performed. This happen because there is already published chat with the same file name to the same path

**Comment by YauheniyaH** [comment]
for described case 2 return error toast message with text '400'


![Image](https://github.com/user-attachments/assets/3c7704b7-ce6c-45b8-a137-0d03f643717f)

**Comment by YauheniyaH** [comment]
all errors return text as mentioned above

**Comment by VolhaBazhkova** [comment]
Verified on staging environment with the following results:
Case 1:
![image](https://github.com/user-attachments/assets/8bbd607f-fb3e-41c6-98bf-c030a61bb734)
Case 2: 
![image](https://github.com/user-attachments/assets/f21bbc14-f498-443e-934b-d94d52d898bf)
Case3: 
![image](https://github.com/user-attachments/assets/58362c39-fcaa-4567-a3bf-0a0e394a1784)
Case4: (there is a misprint in the last step - another user should create the same folder in change path while publishing)
![image](https://github.com/user-attachments/assets/7d711a3a-59be-4ee6-b6cb-53b93225e9c3)
Case5:
![image](https://github.com/user-attachments/assets/ea912f39-8873-4e78-9821-ec1ade83eafd)


Reported #1915 and discussing with the team the wording of the message (it seems to be strange to show the path and %20) Reported to core: https://github.com/epam/ai-dial-core/issues/442


Reported #1944 
Please note, that error messages were updated on UI. Now there are no %20 Example:
![image](https://github.com/user-attachments/assets/995ce7f5-db13-434f-bbf4-fd42ca74abf6)
