### ISSUE TITLE
Support inline markdown images and links

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1486]
### Description

Support inline markdown images and links

**Example:**
```
[Link](files/BUCKET/appdata/foo/bar.png)
![Image](files/BUCKET/appdata/foo/bar.png)
```
![Image](https://github.com/epam/ai-dial-chat/assets/20163971/5e88ffd0-af0e-4473-80dd-0addb3fa9904)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
