### ISSUE TITLE
Publish: remember "Organization" and "Shared with me" sections collapsed-state in localStorage

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1495]
### Description

remember "Organization" and "Shared with me" sections collapsed-state in localStorage

### Use case/motivation

Right now on Staging the Organization folder is always shown as expanded and takes all the space on the conversations list. The first action I have to do is to collapse it to have an access to my conversations history. See the screenshot.
![image](https://github.com/epam/ai-dial-chat/assets/20163971/2380a2c1-8b00-494d-8b96-d34016cb9eb3)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Verified on STG - fixed
