### ISSUE TITLE
Fix issue with receiving the first chunk with an empty list of choices

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1509]
### EPAM AI DIAL chat version

0.6.19

### What happened?

Fixes issue with receiving the first chunk with an empty list of choices

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env that GPT-3.5 models (all versions) respond ok, work with addons and react according to system prompt set.
