### ISSUE TITLE
[Publication/Sharing]: Arrow scroll down is not displayed for published and shared chats

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1510]
### EPAM AI DIAL chat version

0.12.0

### How to reproduce

preconditions:
there is chat with long history

steps:
1. publish the chat
2. share the chat
3. view published chat when text is under the button
4. view shared chat when text is under the button

### Actual result

![image](https://github.com/epam/ai-dial-chat/assets/77381071/cd95c731-0b93-4d02-b745-3c542568b346)

### Expected result

should be according to Figma
![Screenshot 2024-06-05 at 16 16 32](https://github.com/epam/ai-dial-chat/assets/77381071/f55a3f69-da0b-448c-ac4d-0136eacaec95)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The ticket was verified on staging env successfully. Reported #1611 for Mobile view
