### ISSUE TITLE
Rendering is broken for Mardown-inlined images encoded as Data URLs

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-chat#1518]
### EPAM AI DIAL chat version

0.5.3

### How to reproduce

Send this to the Echo application:

```
![Image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAAFElEQVR4nGNkYPjPgBsw4ZEbwdIAPy4BE1xg8Zc)
```

### Actual result

The image link which is [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) is incorrectly prepended with `api/` prefix which breaks the rendering:

<img width="777" alt="Screenshot 2024-06-06 at 11 07 57" src="https://github.com/epam/ai-dial-chat/assets/4329926/df9b5682-02ab-4d91-bb1f-1bd33c5d38db">

### Expected result

10x10 blue square

<img width="777" alt="Screenshot 2024-06-06 at 11 11 12" src="https://github.com/epam/ai-dial-chat/assets/4329926/96fdf2cd-fd51-4b30-96fc-807598dd9892">

Apparently the bug is caused by https://github.com/epam/ai-dial-chat/pull/1487

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
