### ISSUE TITLE
Use monospace font for Markdown code blocks

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-chat#1530]
### Description

<img width="520" alt="Screenshot 2024-06-06 at 16 58 38" src="https://github.com/epam/ai-dial-chat/assets/4329926/78423e87-fba6-44e9-a775-77d314e302e7">

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified successfully on staging for code block and stages with code
