### ISSUE TITLE
Add ability to have multiple select for prompts / conversations to remove it

### ISSUE THREAD

**Issue by sdryapko** [epam/ai-dial-chat#1531]
### Description

Add ability to have multiple select for prompts / conversations to remove it
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=9500-14264&t=oMlxlW2015uh7s0g-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
'Select all' button was implemented on 'Conversation list' and 'Prompt list' panels.
'Select' option in context menu was implemented for chats/prompts/folders.
Reported the following issues: #1689 #1691 #1692 #1694 #1698 #1699 #1704 #1710 #1735 

Mass files selection (Select all) will be implemented in future. no enhancement created

**Comment by sr-remsha** [comment]
Added to the [conversations](https://docs.epam-rail.com/user-guide#select-to-delete) and [prompts](https://docs.epam-rail.com/user-guide#select-to-delete-1) documentation
