### ISSUE TITLE
[Publication]: Publish option is available for Replay chats

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1532]
### EPAM AI DIAL chat version

0.12.0

### How to reproduce

Steps:
1. create chat
2. create replay for created chat
3. hover on 3 dot for Replay chat

### Actual result

Publish option is available for Replay chats

### Expected result

According to the requirements Publish should not be available for Replay chats

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
Not the bug

**Comment by YauheniyaH** [comment]
After user start replay and response generated, then chat is treated as normal one, not like Replay chat.
Not a bug
