### ISSUE TITLE
[Publication]Admin area: Add arrow for chats which not fit screen when admin reviews the publication

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1544]
### EPAM AI DIAL chat version

0.12.0

### How to reproduce

Steps:
1. create chat with history which cannot be displayed on the screen fully, need to scroll it
2. create a publication request
3. admin open the publication request
4. admin click "Go to publication review" and scroll the history up

### Actual result

Arrow is not displayed near button "Back to publication request"

### Expected result

arrow button to go to the end pf conversation should be displayed as it stated in Figma 
![image](https://github.com/epam/ai-dial-chat/assets/77381071/5f69c330-931c-4464-94a9-1f057ca4666f)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The ticket was verified on staging env successfully. Reported #1611 for Mobile view
