### ISSUE TITLE
Collapsed Today and Pinned conversations sections should expand when create New conversation or New Folder

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1552]
### EPAM AI DIAL chat version

0.12.0, 0.6.19

### How to reproduce

Steps:
1. Collapse Today and Pinned conversations sections
2. click New conversation button
3. click New folder button

### Actual result

Today and Pinned conversations sections are not expanded
User does not see how many chats or folders he/she created

Additional case: when user select option  Move to for chat while Pinned conversations section is collapsed.

### Expected result

Collapsed Today and Pinned conversations sections should expand when create New conversation or New Folder

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
please, have a look at case when user select option Move to for chat while Pinned conversations section is collapsed.

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully.
If to create new conversation/new folder/prompt the corresponding section is expanded. Reported #2884
