### ISSUE TITLE
Prompts from collapsed folders inside Organization and 'Shared with me' folders are not available while create, edit chat or system prompt

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1562]
### EPAM AI DIAL chat version

0.12.0

### How to reproduce

Steps:
1. Login as any user ( auth0 or keycloak)
2. collapse all folders in Prompts side panel (inside Organization, Shared with me, Pinned prompts)
3. click New conversation button
4. input "/" into text box and review list of available prompts

### Actual result

prompts from folders from sections Organization and 'Shared with me' are not displayed in the list of available prompts.
Only prompts from Pinned prompts and Recent sections are available

### Expected result

Prompts from folders from sections Organization and 'Shared with me'should be visible in the list when create New conversation using "/" even if folders are collapsed

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Alexander-Kezik** [comment]
related issue: #2001

**Comment by YauheniyaH** [comment]
verified on staging successfully
