### ISSUE TITLE
[Publication] Admin area: incorrect font for text in Publication request for user and admin view

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1591]
### EPAM AI DIAL chat version

0.13.0

### How to reproduce
**Case 1:**
Steps:
1. user create publish request
2. admin approve request
3. user create unpublish request for published resource
4. admin review unpublish request

### Actual result
**Case 1**
incorrect font size 12px for lines and its values: Publication id, Path, Publication date
![image](https://github.com/epam/ai-dial-chat/assets/77381071/719b99f2-3ad5-45fa-a295-67fda22dca20)

**Case 2** 
For Publication request from user view lines Conversations, Prompts, Files has font size 12px

<img width="895" alt="Screenshot 2024-06-18 at 10 27 27" src="https://github.com/epam/ai-dial-chat/assets/77381071/11674dcf-502f-4e26-8db4-105497f05072">
<img width="1571" alt="image" src="https://github.com/epam/ai-dial-chat/assets/77381071/cc6ca1db-141c-4d76-ad01-474d54023451">

Case 3 For (Un) Publish request for Admin view titles Conversations, Files, Prompts also have font size 12px 

### Expected result

Font size should be 14px according to https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=9313-12735&t=BPv8K93Ms0SpQZDW-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Alexander-Kezik** [comment]
upd:
Case 1 is invalid. Now we have new design for this case.
Case 2: 'Request creation date' text must be 12px according to new design

**Comment by YauheniyaH** [comment]
case 2 still reproducible on stg : For Publication request from **user** view lines Conversations, Prompts, Files has font size 12px, need to be 14px

**Comment by YauheniyaH** [comment]
verified on stg - fixed
