### ISSUE TITLE
Improve Replay functionality via supporting the template markup

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#1592]
### Description

1. Extend templating markup used in prompts. {{ParameterName|DefaultValue}}
2. Allow usage templating markup in chat.
3. When user (or replay) enters message with template parameters show parameter entry form. With prepopulated default values.
4. Once user fill the form, send message to model, but replace markups with filled values, However on disk store original markup text (use filled values as default). 
5. In UI sent message contains only filled value, but it must be emphasized in some way. Suggested way: underscored. 
6. Change replay functionality so it run step by step similar to playback. 
7. After each model response allow to:
    - Rerun last request
    - Change last message manually and rerun
    - Go next: send next prompt. With entered values populated.

### Expected UX. 

We allow end-users to create their chats/stories with templates. And then share/publish them. Once recipient user get such story he can replay it with their own parameter. Replay stops after each step and allo one assess the result and try again if fails. 

### Use case/motivation

We may significantly improve applicability of chat for knowledge sharing.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
Note: now we have new type of prompt with parameters 
![image](https://github.com/user-attachments/assets/84dc81b2-d402-4868-903d-b15458bf39b2)

**Comment by sr-remsha** [comment]
Documented in [Parameterized replay](https://docs.epam-rail.com/user-guide#parameterized-replay) in the user guide. Also, updated the [section](https://docs.epam-rail.com/user-guide#variables) about prompt variable with the new options of adding default values for variables.
