### ISSUE TITLE
Unpublish window height should be flexible 

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1594]
### EPAM AI DIAL chat version

0.13.0

### How to reproduce

Open unpublish window for any folder in the organization

### Actual result

![image](https://github.com/epam/ai-dial-chat/assets/151838896/fc625f6f-9d09-4d32-853e-e361e21a8052)

### Expected result

Min height is 579 px. Max height should be as high as the screen height allows and only after it scroll will appear.

Example: manage attachments window 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Tested successfully on Staging
