### ISSUE TITLE
[Publication] Right part scroll works incorrectly for the publication request window

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1595]
### EPAM AI DIAL chat version

0.13.0

### How to reproduce

Create publiсation request window with enough content for scroll in left and right parts

### Actual result

Left part scroll works correctly
![image](https://github.com/epam/ai-dial-chat/assets/151838896/5785b232-3f59-4665-bd0b-79e3ec51d280)

Right part scroll works as common scroll
![image](https://github.com/epam/ai-dial-chat/assets/151838896/6b97153a-78ae-48d7-9ce7-02c474ff8d23)

### Expected result

Right part scroll should apply only for right part of the window

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified successfully on staging
