### ISSUE TITLE
[Share conversation] Infinite loader is shown on opening share conversation link

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1596]
### EPAM AI DIAL chat version

0.13.0-rc

### What happened?

**Setup:**
- conversation created several days ago exists in the system

**Steps:**
1 Select 'Share' option in the conversation dropdown menu
2 Copy share link
3 Open copied link by another user

**Expected result:** conversation with the history is opened
**Actual result:** conversation is visible on side panel; infinite loader is shown istead of chat history

The issue is reproduced sometimes. Possible conditions: share past conversation; conversation model is Rag

![image](https://github.com/epam/ai-dial-chat/assets/15156585/1fc58a17-026e-4d4b-8259-30a83ba657c7)

The issue is also reproduced for conversations with links and shared folder with conversations/prompts. Http 500 error is displayed in the console on opening DIAL home page:

![image](https://github.com/user-attachments/assets/3b79f4f3-b5be-4329-b46e-93dc2d089381)

The issue is possibly related with error response from recursive api listing:

![image](https://github.com/user-attachments/assets/8ac935af-412e-46fa-a667-7da01e9b29f1)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Issue also reproducible for folders with chats with attached/ produced files

**Comment by VolhaBazhkova** [comment]
Verified the fix on the staging env. using chats with link, images, pdf, just text created a month ago (or yesterday) and folders. Now no infinite loader appears.
Reported #2652 as in most cases single shared char is not focused.
