### ISSUE TITLE
[Publication]: Long names on Unpublish form are displayed in 2 lines

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1600]
### EPAM AI DIAL chat version

0.13.0

### How to reproduce

Precondition:
there is published chat with long name, e.g. 
Lorem ipsum dolor sit amet consectetur adipiscing elit. Nullam ultricies ipsum nulla nec viverra lectus rutrum id. Sed volutpat ante ac fringilla turpis duis!

Steps: 

1. User create unpublish request for the chat
2. view unpublish form

### Actual result

Long names on Unpublish form are displayed in 2 lines
![Screenshot 2024-06-17 at 18 32 41](https://github.com/epam/ai-dial-chat/assets/77381071/e0db6151-5b6b-47df-a2eb-d47f04b89d1b)

### Expected result

Long names on Unpublish form are displayed in one line with 3 dots in the end and display tooltip

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Alexander-Kezik** [comment]
Resolved in #1628
