### ISSUE TITLE
Forbid double quote from being in resource name

### ISSUE THREAD

**Issue by sdryapko** [epam/ai-dial-chat#1622]
### EPAM AI DIAL chat version

0.10.1

### What happened?

Forbid double quote from being in resource name

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
" sign now is forbidden in DIAL, verified on staging env successfully

**Comment by sr-remsha** [comment]
documented in [user guide](https://github.com/epam/ai-dial/blob/main/docs/user-guide.md#arrange)
