### ISSUE TITLE
Publish: add a name field for publication request

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1628]
### Description

Now we're using ids to identify publications. need to replace it with publication names

### Use case/motivation

It's impossible for an administrator to prioritize publications for review based on their `ids`. Adding names will make it much easier for him to prioritize and review them

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on stg - fixed
