### ISSUE TITLE
Publish: Need to add publication request review wizards for admins 

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#164]
### Description
Admin should be able to see all request details.
`Approve` button is disabled until all items in request will be viewed.
`Reject` button is always enabled and admin can reject after review request details. 
When `Reject` button clicked Admin should enter Rejection reason in modal
When admin clicks to "Go to a chat review..." then first item in request will be displayed

conversations:
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3741-11008&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/2b7e74c3-b5e3-45c2-8d81-a01736fd4adb)
prompts:
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=4007-8883&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/57a671ee-d708-41ea-975d-0ab608c9a277)
Rejection reason:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/eb185034-fcbd-401e-a76b-fe7c6befc19d)

**Comment by Alexander-Kezik** [comment]
Resolved in #323
