### ISSUE TITLE
Publish: redesign filters

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1640]
### Description

need to redesign filters according to:
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=3807-8779&t=zq7VfvSrAYgfZCEz-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
#1696 
#1700
#1701
#1714
#1715

**Comment by YauheniyaH** [comment]
When unpublish single chat from folder Comparison form show that filters are removed

Steps:
1. Publish chat into folder with some rules
2. admin approve request
3. user create unpublish request for this chat ( not for folder)
4. admin review the request

Actual result: Comparison form show that filter rules were removed


![Image](https://github.com/epam/ai-dial-chat/assets/77381071/bc5faf59-c714-46f5-ae57-36a768a800c6)

**Comment by YauheniyaH** [comment]
verified successfully on stg
