### ISSUE TITLE
Fix markdown displaying for dark themes 

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1641]
### EPAM AI DIAL chat version

0.12.0

### What happened?

Markdown should use invertion for any themes where id starts with `dark`
![image](https://github.com/epam/ai-dial-chat/assets/20163971/b681d48e-8d91-4370-90ac-7f63ff74491e)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified that MD table looks fine in Light and Dark themes. Reported an issue #1646
