### ISSUE TITLE
Integrate with DIAL stateful API 

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#165]
Required issue: https://github.com/epam/ai-dial-core/issues/33

**Comment by DaryaKarniyenka** [comment]
Loader examples
![1920_loaders](https://github.com/epam/ai-dial-chat/assets/151838896/99d69020-2c36-4f7a-86cc-ba3a0d3494ec)

For input
![image](https://github.com/epam/ai-dial-chat/assets/151838896/860fc456-93e3-4ed4-97e4-ab363596a66c)

For modal windows
![image](https://github.com/epam/ai-dial-chat/assets/151838896/239aeb2b-7398-4b45-9af9-44fb1290a78c)

Animated prototype (press "R" to start animation)
https://www.figma.com/proto/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?page-id=0%3A1&type=design&node-id=5834-9838&viewport=-243%2C-1339%2C0.06&t=mu2eEwlXfYTsbdbf-1&scaling=min-zoom&starting-point-node-id=5834%3A9838&mode=design
