### ISSUE TITLE
Make empty chat settings optional, due to they are confusing users

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#1656]
### Description

1. **Done**: _We should highlight new conversation button on mobile_ 
2. We need to get rid of empty chat settings and show them just icon of model, name of model and short description of model in this conversation

### Use case/motivation

1. **Done**: _Users really don't see new conversation button on mobile, but usually they should see it clearly and understand how to create new conversation from mobile_ 
2. After clicking on new conversation or landing newly on website users confused with a lot of parameters they can change. We need to show them minimal info about conversation

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Reported tickets #1664, #1671, #1672, #1662

**Comment by VolhaBazhkova** [comment]
Closing the ticket as in 0.21.0 and 0.22.0 milestones we re-designed DIAL. Please refer to #2045
