### ISSUE TITLE
No scroll down button for chat with not allowed model

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1660]
### EPAM AI DIAL chat version

0.13.0

### How to reproduce

Open a chat with not allowed model

### Actual result

![image](https://github.com/epam/ai-dial-chat/assets/151838896/81e9eaae-3acf-437a-b780-2d9c6f449eed)

### Expected result

Scroll down button should appear 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
![image](https://github.com/epam/ai-dial-chat/assets/111180458/6a7afb10-14d3-40dc-b50c-7ad5ca28c9c1)
