### ISSUE TITLE
[Replay]: cannot change model for replay mode

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1662]
### EPAM AI DIAL chat version

0.14.0-rc

### What happened?

**Steps:**
1 Create a new chat
2 Create replay chat based on it
3 Click 'Start replay' button
4 Stop replay when part of content is received
5 Open chat settings
6 Try to change model -> model cannot be selected

**Expected result:** any model/app is selected, settings are displayed

![image](https://github.com/epam/ai-dial-chat/assets/111180458/6036af27-db09-48c1-8439-222f13c5be1b)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The ticket as a duplicate of https://github.com/epam/ai-dial-chat/issues/138
Verified on staging env successfully.
