### ISSUE TITLE
[Playback]: 'Stop playback' button is available on just created playback conversation

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1664]
### EPAM AI DIAL chat version

0.14.0

### What happened?

Steps:
1 Create any chat
2 Create playback chat based on it -> 'Stop playback' button is availabe in the header

![image](https://github.com/epam/ai-dial-chat/assets/15156585/3890db30-f3ac-49cf-a556-f2a8f02ef40f)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Not reproduced anymore. Verified after re-design phase in 0.22.0 milestone
