### ISSUE TITLE
[Attachments] Folder attachment disappears during message editing and after a message is edited

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-chat#1665]
### EPAM AI DIAL chat version

0.5.3

### What happened?

How to reproduce:
1. add a folder attachment to a message
2. send the message
3. edit the message via "Edit" button - the folder attachment disappears **during** the editing and **after** the editing is done.

https://github.com/epam/ai-dial-chat/assets/4329926/0e1b8ece-9018-47b1-a95a-b5db53f62ade

Note that this doesn't happen with regular **file** attachments.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The fix was verified on staging env successfully.
