### ISSUE TITLE
[Publication]: Folder icons turn into infinite spinner while enter text into search text box

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1667]
### EPAM AI DIAL chat version

0.13.0

### How to reproduce

Preconditions:
there are at least several folders available in organization for user

Steps: 
1. Open publish request form
2. go to Change path form
3. input any text into search are which fits al least 2 folders

### Actual result

Folder icons turn into infinite spinner 

### Expected result

folder icons should be displayed after search is completed

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
issue reproduced when create prompt publication request

**Comment by VolhaBazhkova** [comment]
Still fine for conversations, but unexpected loader appears for prompts folders if to expand folder or if to update search word

https://github.com/user-attachments/assets/9cee8b9e-be13-4ce8-a7e1-490d5458fe2a

**Comment by VolhaBazhkova** [comment]
Agree that sometimes the issue is not reproduced, but FF example for prompts:
![image](https://github.com/user-attachments/assets/51dd89ea-a607-46fe-aad7-76d58ca28b79)
and everything is fine for chats

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully.
The fix for chats was delivered in 0.16 milestone, the fix for prompts in 0.17 milestone.
