### ISSUE TITLE
Publish: redesign approve required modal

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1676]
### Description

redesign approve required modal according to
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=3741-12372&t=5a91fUZl3J8DNkRN-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
