### ISSUE TITLE
Use mobile header for tablet view

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#1682]
### Description

We need to have simular view for app header on mobile and tablet views

### Use case/motivation

On tablet view users mostly working without side panels and it's really helpful to have new conversation button in header to reduce amount of clicks to create it

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The "New conversation" button was redesigned and added to tablet view.
![image](https://github.com/epam/ai-dial-chat/assets/111180458/ea7dea35-acdd-4a29-8406-f1689d64b5aa)

**Comment by sr-remsha** [comment]
currently, we do not have interface documentation for anything other than desktop resolution
