### ISSUE TITLE
Support application publication on UI

### ISSUE THREAD

**Issue by sdryapko** [epam/ai-dial-chat#1686]
### Description

Support application publication (aka registration) on UI and ability to use publishing for it.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
documentation
https://gitlab.deltixhub.com/Deltix/openai-apps/documentation/-/blob/fe432a02a617180ba78ededdc746f5ab8971cea3/design/user_application_deployment.md

**Comment by VolhaBazhkova** [comment]
The first part was packed in 0.16 rc. but testing of the feature (along with refactoring we are doing in 0.17 version) => changing the milestone

**Comment by YauheniyaH** [comment]
verified on staging, related issues created
