### ISSUE TITLE
Need to add sharing option/wizard in Chatbar settings menu and Share by me dialog

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#169]
Chatbar menu option:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/1a305553-38f4-46c9-a427-efdb69944fdf)

Share by me dialog:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/94ee153d-0605-45fc-9276-d62dcce71b27)

Share with me section:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/10c90b4f-8b74-4fc3-837b-bea03b5a77c0)

**Comment by avavilau** [comment]
No way to know users who you shared to. For now at least.

**Comment by VolhaBazhkova** [comment]
Please note that it was discussed not to do Shared by me dialog. There are filters instead implemented in #276 
Also "Shared with me" will be updated in the code according to new API. This feature will be re-tested fully.
