### ISSUE TITLE
 Infinite spinner when Delete all for only empty folders

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1698]
### EPAM AI DIAL chat version

0.14.0

### How to reproduce

Preconditions:
user doe not have any own chats and prompts ( only shared with me or Organization if exist)
Steps:
1. add new chat folder 
2. click Delete all button in the bottom of conversation side panel -> infinite spinner on the panel
3. add new prompt folder 
2. click Delete all button in the bottom of prompt side panel -> infinite spinner on the panel

### Actual result

<img width="469" alt="image" src="https://github.com/epam/ai-dial-chat/assets/77381071/b4352283-3991-4074-be5b-ad390e2278cb">

### Expected result

side panel without deleted folder should be displayed

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
Note: to reproduce p.2 you need to have Shared with me or Published conversation and don't have own conversations

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
