### ISSUE TITLE
custom_content.attachments isn't removed when all attachments in a message are removed

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-chat#1717]
### EPAM AI DIAL chat version

staging

### What happened?

How to reproduce:

1. Select a model which supports attachments and send a single request to it _(e.g. ask a vision model to describe an image)_
2. Change the model to GPT-4, which doesn't support attachments
3. Edit first user message - remove all attachments and send it again
4. An internal error will be thrown, because DIAL Chat sends an empty list of attachments to a GPT-4 model which doesn't support those:

```json
{ "custom_content": { "attachments": [] }
```

The error message throw by Azure OpenAI is the following:

```
Additional properties are not allowed ('custom_content' was unexpected) - 'messages.0'
```

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
@adubovik  : UI doesn't remove `custom_content` from assistant messages, but only `attachments` field
![Image](https://github.com/user-attachments/assets/3c8ad43d-d072-45bc-bb02-fd7425c8a8f6)

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
