### ISSUE TITLE
The panel resize feature does not work on tablet landscape view (or within the 1060–1279 breakpoint range)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1727]
### EPAM AI DIAL chat version

0.14.0

### What happened?

Open DIAL on tablet. Use landscape mode -> open the 'Conversation list' panel ->resize the panel -> nothing happens -> **bug**
Note: tested on iPad Air (5th generation)
Note: The panel resize feature does not work within the 1060–1279 breakpoint range
Note: arrows on the panels in tablet view are by design

Expected: The panel resize feature should work on tablet landscape view (or within the 1060–1279 breakpoint range)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Issue is reproducible for:
 tablet view vertical and landscape
mobile view - landscape

**Comment by VolhaBazhkova** [comment]
#1886

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
Reported #1911
