### ISSUE TITLE
[Publication][Admin area]: Infinite spinner in publication request for if page was not refreshed for some time

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1729]
### EPAM AI DIAL chat version

0.14.0

### How to reproduce

Precondition:
Admin has own prompts and conversations

Steps:

1. Open DIAL with admin user
2. Do not refresh page for some time ( 7-10 min, maybe less)
3. hover on 3 dots for chat/prompt/folder and select Publish option in context menu

### Actual result

![image](https://github.com/epam/ai-dial-chat/assets/77381071/24ae91c4-ac18-417e-9100-a29ff20970cd)
 Infinite spinner in publication request on the right side of the form

### Expected result

Conversation/prompt/folder details should be displayed

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
Can be reproduced:
- open any request in `Approve required` section
- try to publish anything

**Comment by YauheniyaH** [comment]
issue verified on staging successfully
