### ISSUE TITLE
Publish: redesign publication filters for mobile

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1732]
### Description

redesign publication filters for mobile
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=9718-13288&t=VbcIpQeikvVbTiYh-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
related issue #1775

**Comment by YauheniyaH** [comment]
verified on staging succesfully
