### ISSUE TITLE
[Publication]: Change path has 2 vertical scrolls for list of available folders

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1736]
### EPAM AI DIAL chat version

0.14.0

### How to reproduce

Preconditions:
there are at least 20 of publish folders

Steps:
1. user create publication request
2. open change path form
3. scroll through the folder list

### Actual result

2 scrolls are displayed :

- for the whole form starting from Search text box
- for the Organization area

![Screenshot 2024-07-08 at 13 23 45](https://github.com/epam/ai-dial-chat/assets/77381071/f06f1a38-11e5-4aee-b0f3-88d5afbd54d1)

### Expected result

One scroll should be displayed : for Organization area

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
