### ISSUE TITLE
[Authorizatiton] Add option to do authorization in the same window

### ISSUE THREAD

**Issue by hhharmEpm** [epam/ai-dial-chat#1737]
### Description

Add configuration option to perform authorization in the same window as overlay.

### Use case/motivation

If dial chat is embeded, authorization doesn't work, because it's opened in browser and not in the application where it's embedded.

E.g. we try to embed dial overlay in Excel Add In. Overlay itself is run in Edge inside Excel, but after pressing 'Login' button authorization opens in browser, and after user is authorized overlay doesn't know about it.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Separate team implemented the feature: so, now if to set signInInSameWindow: true in Overlay code, authorization will be in the same window. It was verified locally and works with Auth0 provider successfully. Unfortunately, DIAL is down if to use Keycloak provider. Currently, I'm waiting for Overlay installation to verify other available providers.

**Comment by VolhaBazhkova** [comment]
Closing the ticket. The task to install Overlay on a separate server is on the board, but with no ETA and low priority. 
Probably the feature works with
- Auth0 provider
- Keycloak provider, but separate team added extra specific implementation to make it work
- Azure provider, seems to be working, but extra effort (on Devops or UI dev side?) is needed as login is in the same page, but DIAL doesn't work with Azure now
- other providers were not tested as there is no any environment
