### ISSUE TITLE
[Overlay]: modelId option is ignored in overlay configuration

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#1742]
### EPAM AI DIAL chat version

0.14.0

### What happened?

**Steps:**

1 Configure overlay sandbox with the following options (*may use existing sandbox apps/overlay-sandbox/app/cases/overlay/page.tsx):
`{
  domain: process.env.NEXT_PUBLIC_OVERLAY_HOST!,
  theme: 'light',
  modelId: 'gpt-4',
  enabledFeatures: [
    Feature.ConversationsSection,
    Feature.PromptsSection,
    Feature.TopSettings,
    Feature.TopClearConversation,
    Feature.TopChatInfo,
    Feature.TopChatModelSettings,
    Feature.EmptyChatSettings,
    Feature.Header,
    Feature.Footer,
    Feature.RequestApiKey,
    Feature.ReportAnIssue,
    Feature.Likes,
  ],
  requestTimeout: 20000,
  loaderStyles: {
    background: 'white',
    fontSize: '24px',
  },
};`

2 Start overlay sandbox ->gpt-3.5 is used as default model, gpt-4 added as recent

**Expected result:** modelId from overlay config should be used as default

![image](https://github.com/epam/ai-dial-chat/assets/15156585/3900daf8-a5cf-4d8c-9804-3faca58ce786)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The ticket was fixed in #2297
