### ISSUE TITLE
Publish: redesign unpublish modal

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1746]
### Description

redesign unpublish modal
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=9671-13033&t=eqX0OC7hyf7cUtZL-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
related issue #1867
