### ISSUE TITLE
Publish: publication review works incorrect if publication has prompts and conversations simultaneously

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1748]
### EPAM AI DIAL chat version

0.14.0

### What happened?

publication review works incorrect if publication has prompts and conversations simultaneously if publish it **API** directly, not through **DIAL Chat**

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
