### ISSUE TITLE
[Publication][Admin area]: 'Back to publication request' button lead to incorrect unpublish request if there are more than one the same requests

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1770]
### EPAM AI DIAL chat version

0.15.0

### How to reproduce

Steps:
1. create 'unpublish request 1' and 'unpublish request 2' for the same folder from Organization
2. admin click on 'unpublish request 1' and click 'Go to a review' link
3. click 'Back to publication request button'

### Actual result

redirect to 'unpublish request 2' happen

https://github.com/user-attachments/assets/73fed9a2-0d18-4c22-8b81-93f497a1c0a6

Note: also redirect happen to incorrect request if 2 or more unpublish requests have the same chats inside

### Expected result

on click 'Back to publication request' redirect to the parent request should occur

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
Also fixed:
![image](https://github.com/user-attachments/assets/f54053b1-e0da-471f-b642-67cd7e69f07f)
->
![image](https://github.com/user-attachments/assets/93e7ad6e-5ee0-4ec5-9510-1e061ec85b32)
and
![image](https://github.com/user-attachments/assets/db454ae4-708d-4422-b646-b97cc4ff8a2b)
->
![image](https://github.com/user-attachments/assets/43c7bb72-fb57-44bc-a1f9-651b4ed210f0)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. Checked unpublication of several chats/chat folders/prompts/prompt folders
Example:
![image](https://github.com/user-attachments/assets/2326a2d9-02e2-4705-97c3-aa6991b1eb71)
