### ISSUE TITLE
[Visualizer Connector] Add the possibility to send messages from the custom visualizer.

### ISSUE THREAD

**Issue by denys-kolomiitsev** [epam/ai-dial-chat#1782]
### Description

Now, with the visualizer connector, you could get your data to visualize, but we don't have the possibility to send some data back to the model. 
It would be good to have both-sided communication.

**Expected result:** 
The visualizer could send data to the chat.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Confirmed with a separate team that the feature works as expected.
