### ISSUE TITLE
[Publication]: Display published files in Manage attachments modal window

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1801]
### Description

Publication feature allow publish files without chats.
But published chats are not visible for user .
For correct usage of files need implement section for published files in Manage attachments modal.

Design mockup will be provided.
Details -TBD

### Related issues

#1439

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Reported #1977 , #1962

**Comment by sr-remsha** [comment]
Included Organization section in the attachments manager section in [user guide](https://docs.epam-rail.com/user-guide#attachments-manager).

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
