### ISSUE TITLE
Publish: need to combine prompt and conversation folders for 'Change Path' modal

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1812]
### EPAM AI DIAL chat version

0.15

### What happened?

Public prompts and conversations are in the same bucket, so folders can contain prompts and conversations at the same time with the same rules

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
related issue #1844

**Comment by YauheniyaH** [comment]
verified on stg, see related issue
