### ISSUE TITLE
Closing error toast unexpectedly closes prompt creation dialog

### ISSUE THREAD

**Issue by nartovm** [epam/ai-dial-chat#1819]
### EPAM AI DIAL chat version

Version 0.15.0-rc

### What happened?

**Description**
When an error toast appears during prompt creation (e.g., due to an invalid character in the prompt name) and the user closes the toast, the entire prompt creation dialog closes unexpectedly. 

This results in the loss of any data entered in the dialog, including the prompt name, description, and content.

**Steps to Reproduce:**

1. Navigate to the "Prompts" panel.
2. Click the "New Prompt" button to open the prompt creation dialog.
3. Enter an invalid character in the "Name" field (e.g., a dot at the end).
4. Fill in the "Prompt" field with any content.
5. Click the "Save" button.
6. An error toast appears, indicating the invalid character in the name.
7. Close the error toast.

**Expected Result:**
The error toast should close, and the prompt creation dialog should remain open, allowing the user to correct the error in the "Name" field without losing the other entered data.

**Actual Result:**
Closing the error toast also closes the prompt creation dialog, discarding all entered data.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Will be re-designed in #1918
