### ISSUE TITLE
Server error if try to use shared link in DIAL RAG

### ISSUE THREAD

**Issue by YuryZhylko** [epam/ai-dial-chat#1827]
### EPAM AI DIAL chat version

0.6

### How to reproduce

Rag -> Attach link -> Publicly shared link from box to a Zoom transcript

### Actual result

This is the previous result (it works)
![2024-07-25_16-32-26](https://github.com/user-attachments/assets/6eb059bc-9b8a-4768-8cfe-744a0a330b0c)
This is a new result (issue)
![2024-07-25_16-37-51](https://github.com/user-attachments/assets/a820251e-399e-409a-b471-1f6d76210786)

### Expected result

It should work without issues

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
@YuryZhylko Could you please provide the json of the conversation? 
Developer guesses, that fail occured on stage of mapping this "[1][2]" to document chunks. But to prove it we need the whole content.

**Comment by YuryZhylko** [comment]
**Case:** attach public URL - Wiki page https://en.wikipedia.org/wiki/2024_Summer_Olympics
[epam_ai_dial_chat_with_attachments_8-7 (1).zip](https://github.com/user-attachments/files/16531191/epam_ai_dial_chat_with_attachments_8-7.1.zip)
Reproduced in EPAM instanve of DIAL Version 0.10.3
@VolhaBazhkova Here is one example of the issue

**Comment by YuryZhylko** [comment]
@VolhaBazhkova 
Here are 2 additional
**Case 1:** attach public URL - Wiki page https://en.wikipedia.org/wiki/2024_Summer_Olympics
[ai_dial_chat_with_attachments_8-7.zip](https://github.com/user-attachments/files/16539149/ai_dial_chat_with_attachments_8-7.zip)
<img width="941" alt="Screenshot 2024-08-07 at 08 28 20" src="https://github.com/user-attachments/assets/7295afb1-01c4-4693-afdc-630bc2a4a470">

**Case 2:** Shared link to Zoom (Box folder) 
[ai_dial_chat_with_attachments_8-7 (3).zip](https://github.com/user-attachments/files/16539388/ai_dial_chat_with_attachments_8-7.3.zip)
Please pay attention that URLs was modified in this json due to NDA
<img width="588" alt="Screenshot 2024-08-07 at 08 28 58" src="https://github.com/user-attachments/assets/6af4e550-2d8d-445f-af1f-d7a4adc24d8d">
<img width="881" alt="Screenshot 2024-08-07 at 08 29 46" src="https://github.com/user-attachments/assets/fe1f40fe-7ecf-4c2a-85b1-b6baa191ce17">

DIAL Version 0.13.0-rc

**Comment by roman-romanov-o** [comment]
Resolved in `dial-rag` version `0.10.0`
