### ISSUE TITLE
Publish: get rid of BackendDataNodeType in publications epic

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1831]
### EPAM AI DIAL chat version

0.16.0

### What happened?

BackendDataNodeType should be inside the services. Epic does not need to know about this

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Publication requests can be created and reviewed and approved by Admin, successfully displayed in Organization section for chats and prompts
