### ISSUE TITLE
[Regression]: New message can be sent when response generation was stoped after part of response was provided for Application, Assistant or Model with addon

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1834]
### EPAM AI DIAL chat version

0.15.0

### How to reproduce

Steps:
1. create chat with Application (or Assistant, or Model with addon)
2. input message which suppose to generate long answer (for example "Provide 50 adjectives about weather)
3. stop generating after part of response was provided
4. type message into text box and click Send button

### Actual result

Send button is enabled, next message can be posted

### Expected result

In case User stoped generation or Error from DIAL the following behaviour should be 

1. when no response produced 
Model/ Model with Addon/ Application/ Assistant  -> Send button is disabled

2. when part of response provided 
Model -> Send button is enabled
Model with addon/Application/Assistant -> Send button is disabled (this part need to fix)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The flag "allowResume" was introduced. It's set in config for specific applications.

**Comment by VolhaBazhkova** [comment]
The flag "allowResume" was introduced. By default it is set to true. 
For assistant and model + addon, "allowResume" is always set to false.  In case of empty or partly response an error appears, user has to regenerate the response. 
For application, model without addon, by default "allowResume" = true. In case of empty or partly response it's allowed to send the next user-message, regenerate action is not required. 
In config we set "allowResume" = false for DIAL RAG and WEB RAG applications, it means that regenerate action is required when response is stopped. Example: 
![image](https://github.com/user-attachments/assets/a3406eb3-5525-4950-bfaa-4e4f6311ce0e)
![image](https://github.com/user-attachments/assets/5249a630-b93d-429e-a60c-0d3d155c1784)

Reported UI defect #1963
