### ISSUE TITLE
[Publication][Admin area]: Dots on request icons and counter should have purple color for prompt panel

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1842]
### EPAM AI DIAL chat version

0.16.0

### How to reproduce

Steps:
1. create publication rquests for prompts
2. admin  review Approve required section for prompts

### Actual result

dots on requests and counter have green color
![Screenshot 2024-07-30 at 12 34 49](https://github.com/user-attachments/assets/356794ff-3beb-4d82-8384-2725ec4915d8)

### Expected result

Dots on request icons and counter should have purple color for prompt panel

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Dots are green for prompts

**Comment by VolhaBazhkova** [comment]
Verified on staging env (light and dark themes) successfully
![image](https://github.com/user-attachments/assets/a14fdc2c-ba6a-4b00-a3a8-ec18efd95985)

Note that there is specific colours in Light Orange theme (orange icons for both)
![image](https://github.com/user-attachments/assets/f564f8f4-d951-43bc-8a30-169ea096defa)
