### ISSUE TITLE
Horizontal scroll appears when renaming nested elements

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1846]
### EPAM AI DIAL chat version

0.10.3

### How to reproduce

Create a highly nested structure. Rename the bottom level.
![image](https://github.com/user-attachments/assets/da105855-6462-4b25-a142-19ffe9976fd3)

### Actual result

![image](https://github.com/user-attachments/assets/0dc7f9f1-1d37-45da-ac2d-0c9f1742647a)

### Expected result

No horizontal scroll

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. Verified conversation; the lowest level folder renaming in chats/prompts.
