### ISSUE TITLE
[Publication][Admin area]: Dot should be removed from request icon for unpublish request with already unpublished resource as reviewed when admin click on request

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1847]
### EPAM AI DIAL chat version

0.16.0

### How to reproduce

Preconditions:
create 2 unpublish requests for the same resource
Approve one of the requests

Steps:
1. Admin click on second request

### Actual result

Request details are displayed on central part of the screen, request has note why ot can not be approved, no 'Go to a review' link - ok
Dot is still remain on the request icon, counter did not decreased - bug
![image (30)](https://github.com/user-attachments/assets/d9a73c11-f8cf-4824-a4ea-d36e322a8612)

### Expected result

Need to remove dot from request icon for unpublish request with already unpublished resource as reviewed when admin click on request
Also counter of unreviewed request should be decreased by one

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
also should be fixed in the ticket
![image](https://github.com/user-attachments/assets/a779ac43-6d55-4c75-be20-6c76b3d08814)

**Comment by YauheniyaH** [comment]
verified on staging , fixed
