### ISSUE TITLE
'Select all' button  does not select empty folders

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1864]
### EPAM AI DIAL chat version

0.16.0

### How to reproduce

Preconditions:
side panel contains chats, folders with chats and empty folders

Steps:
1. click on 'Select all' button in the bottom of conversation panel

### Actual result

all items were selected except empty folders
issue reproducible for empty folders in prompt panel

### Expected result

'Select all' button should select all items (chats, prompts) and folders except items from sections Shared with me, Organization, Approve required

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
