### ISSUE TITLE
Need to re-design successful message after import

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1865]
### EPAM AI DIAL chat version

0.16.0

### What happened?

Now:
![image](https://github.com/user-attachments/assets/0100e8b4-5124-4a9e-a3f6-8ca855bbb7f0)

Expected: https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=10460-2592&t=jREnMZEDV5N7SNlT-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
Pay attention on these notifications also:
![Image](https://github.com/user-attachments/assets/780bded3-f91e-4e0c-8001-667dbae4e7fe)
![Image](https://github.com/user-attachments/assets/ce7ca566-2397-4e72-88bd-52cf4f734b9a)

Now they are in such style
![Image](https://github.com/user-attachments/assets/10780811-3d96-4104-a175-fbda7a93ed23)

**Comment by IlyaBondar** [comment]
![image](https://github.com/user-attachments/assets/8af45dd9-9fef-497c-8cb3-1c20f4935a1e)
![image](https://github.com/user-attachments/assets/1180459e-568f-4b8e-98a9-f78bdb1ed08d)

**Comment by VolhaBazhkova** [comment]
It looks like we don't have 'yellow' notification. Here are some other examples of info, success and error
![image](https://github.com/user-attachments/assets/314f6c06-ca41-418d-8c16-f5bcdcbd8102)
