### ISSUE TITLE
[Publication]: Check box for folders inside unpublish request is not available

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1867]
### EPAM AI DIAL chat version

0.16.0

### How to reproduce

Preconditions:
there is published folder with chats

Steps:
1. create unpublish request for this folder
2. view request form

### Actual result

no check boxes for folders, just for content
![Screenshot 2024-08-01 at 14 10 01](https://github.com/user-attachments/assets/d2d08ee4-87d9-4857-990c-89bf573bf599)

### Expected result

according to design check boxes should be available for folders and items for publish/unpublish
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=0-1&t=fKPRjbYkZo0lKbzv-0

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env: now there are check boxes for folders which can be checked/unchecked/partly selected.
![image](https://github.com/user-attachments/assets/e7068b92-6f81-4b0d-80a5-bda14c83d654)
![image](https://github.com/user-attachments/assets/a7e13395-cdd6-45bf-b799-9135e77f6b31)
