### ISSUE TITLE
Prompts: Selectors do not work correctly for folders if the search field is not empty

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1874]
### EPAM AI DIAL chat version

0.15.0

### How to reproduce

Steps:
1. create prompt folder01 with Prompt 1, Prompt 2, Prompt 3 inside
2. type 3 in search text box for prompt panel -> folder01 with Prompt 3 displayed as search result
3. hover on folder01 and choose Select option in context menu 
4. click "Delete selected prompts' button in the bottom of panel

### Actual result

4. folder01 with Prompt 1, Prompt 2, Prompt 3 inside was deleted, reproducible on UAT env only

NOTE: if uncheck Prompt 3 when search is not empty, then folder01 displayed as partially selected 
![Screenshot 2024-08-02 at 11 02 58](https://github.com/user-attachments/assets/3a7e80ca-2f0a-476c-9716-150db7fbc440)

### Expected result

only selected Prompt 3 should be deleted
Folder01 with Prompt 1and Prompt 2 should remain

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on UAT and Sales env where 0.15.2 version is installed successfully.
