### ISSUE TITLE
[Publication]: unchecked check-boxes become checked if change folder 'Publish to' on request form

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1876]
### EPAM AI DIAL chat version

0.16.0

### How to reproduce

Steps:
1. create folder01 with chats chat01, chat02, chat03
2. create publication request from folder01
3. uncheck chat01 and chat02 on request form
4. select another folder for 'Publish to' path

### Actual result

All check boxes become checked
Issue reproducible fot conversations only

### Expected result

Selected items should remain in publication request if folder 'Publish to ' is changed

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
It was fixed by @Alexander-Kezik in some of hie MRs. Verified chats and prompts on staging successfully.
