### ISSUE TITLE
Errors appear when reselecting Organization as a path in the publication request window 

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#1880]
### EPAM AI DIAL chat version

0.16.0

### How to reproduce

1. Open the publication request window for any conversation
2. Press change path
3. Click any folder
4. Click Organization again

### Actual result

Errors appear 

1st error
![image](https://github.com/user-attachments/assets/53398b0d-da0f-412e-aca8-80bf6c55b12e)

2nd error (replaces the 1st one in couple of seconds)
![image](https://github.com/user-attachments/assets/c0465628-a961-4836-a263-2e599a08df6a)

Conversations (model icons) disappear and appear in the left panel.

### Expected result

No errors

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
