### ISSUE TITLE
Redesign error messages

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1889]
### EPAM AI DIAL chat version

0.16.0-rc

### What happened?

![image](https://github.com/user-attachments/assets/3f0cfa13-505d-4527-9460-5d0cde365691)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Redesigned:
![image](https://github.com/user-attachments/assets/292c6055-9d88-4e06-9db6-c7fe8bf58dcf)

![image](https://github.com/user-attachments/assets/bdf29de5-63a2-4607-9d1d-accf4b2560ad)
