### ISSUE TITLE
Import doesn't import all entities

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1892]
### EPAM AI DIAL chat version

0.15.0

### How to reproduce

[epam_ai_dial_-_development_chat_prompts_history_8-5.json](https://github.com/user-attachments/files/16531643/epam_ai_dial_-_development_chat_prompts_history_8-5.json)
- import file above (`Prompt 1`, `Prompt 2` and `Prompt 3` are into `Folder 1`)
- delete `Prompt 3`
- import the same file again
- choose any option `Postfix`, `Replace` or `Ignore` in Confirmation dialog and click `Continue`

### Actual result

deleted `Prompt 3` wasn't imported
![image](https://github.com/user-attachments/assets/04ad9830-0fad-4471-8280-2f00ead2bfa0)

### Expected result

deleted `Prompt 3` should appear again after import

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
