### ISSUE TITLE
[Redesign] Windows are closed automatically if to click outside the window. We want to allow the windows to be closed on X only.

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1918]
### EPAM AI DIAL chat version

0.16.0

### What happened?
Now all pop-up windows are closed if to click out side of them.
For example, while publication request there could be an error. If to close the error on 'x', clickoutside action is triggered and publication window is closed automatically. It confuses as user has to start publication from the beginning.

Example:
https://github.com/user-attachments/assets/aa46ef23-2ca8-4647-8bba-c5b1db9498c1

Expected: We want to allow pop-ups to be closed on X only, need to forbid to close the pop-up automatically on clicking outside the window. No need to do this for any confirmation pop-ups.

 - publication
 - share
 - edit prompt (similar in #1819)
 - custom applicatio
 - request API key
 - report an issue
 - ....any others?

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
Note: I suggest to add `ignoreParentClass` into `Modal`-component and pass `outsidePress` into `useDismiss`

**Comment by VolhaBazhkova** [comment]
Discussed on daily and we decided to update the ticket:
initial problem: Windows are closed automatically if to close the error on 'x'. Example, with publish and unpublish window.
decided to fix it: We want to allow pop-ups to be closed on X only, need to forbid to close the pop-up automatically on clicking outside the window.

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully.
The following forms can be closed now on 'X' or Cancel buttons only. They remain on the screen if to click on any area outside the windows:

- Request API Key
- Report an issue
- Conversation settings
- Publish
- Unpublish
- Add application
- Edit prompt

All other confirmations and some windows where user doesn't need to type any info manually can be closed automatically on the click outside. For example:

- Chat, Chat history or Prompt confirmations while deleting/clearing
- Talk to (See full list)
- See all addons
- Manage attachments, Attach files, Attach folders, Attach links
- Upload from device
- Share
- Unshare
