### ISSUE TITLE
Custom applications: Unpublish 

### ISSUE THREAD

**Issue by Derikyan** [epam/ai-dial-chat#1940]
### Description

Need to create unpublish for custom application

### Related issues
need to fix:
(selectedApplication as unknown as { application: string }).application,
and
handleSubmit(event as unknown as MouseEvent<HTMLButtonElement>);

When you select an application on reviews, then select another, the old name remains in applications and a new one is added

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
tested on staging
