### ISSUE TITLE
Fix(chat): Custom applications: Publish Icons

### ISSUE THREAD

**Issue by Derikyan** [epam/ai-dial-chat#1941]
### EPAM AI DIAL chat version

0.16.0

### What happened?

It is necessary to fix the display of user application icons in the public

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
1)  when user create publication request,
then application icon has incorrect dimensions 15x15
Expected result : 18x18
![Screenshot 2024-09-23 at 12 49 57](https://github.com/user-attachments/assets/0220a225-d964-4325-9eb2-7646fb694eb1)

**Comment by YauheniyaH** [comment]
2. for admin view for publication request for custom app:
- order of sections Applications and Files is incorrect.
Expected result: order of sections should be : Application, Files
- application icon is not displayed, default icon displayed instead
![Screenshot 2024-09-23 at 13 15 19](https://github.com/user-attachments/assets/9d5bb20a-3163-4e42-b069-b0c8b8756068)

**Comment by YauheniyaH** [comment]
1. Icon for custom application is not visible in request details on Admin View
2. Icon on published application is not visible for other users

**Comment by YauheniyaH** [comment]
Icon is not displayed on create request form and on request on Admin view if make request from edit form

Steps:
1. create custom application
2. select in context menu Edit option
3.  on Edit form click on Publish icon -> publish request form is opened -> default icon is displayed -> bug
4. submit request 
5. by admin click on publication request name in right side panel -> File section is not displayed on request -> bug


3

![Image](https://github.com/user-attachments/assets/d2363fd5-5c9b-4b7c-9540-c3ad2dff7325)

5 ![Image](https://github.com/user-attachments/assets/80ae356f-1c8c-4350-a974-720fb9f61c20)

**Comment by YauheniyaH** [comment]
Custom application can not be published into folder

Steps:
1. create custom app
2. create publication request
3. in Change path select folder ( or create new)
4. click 'Send request' button

Actual result: error message displayed "Target resource folder does not match with target folder: files/public/<filename>"

**Comment by YauheniyaH** [comment]
Custom applications can not be published:
request fails with error
 ![Image](https://github.com/user-attachments/assets/28a04b2e-0e3f-4785-944e-5a6c4ef580cb)

**Comment by YauheniyaH** [comment]
issue is verified on staging
Note: default icon for custom application on Admin view in request
