### ISSUE TITLE
[Mobile][Publication] Error messages appear for Admin are impossible to read 

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1944]
### EPAM AI DIAL chat version

0.16.0

### What happened?

Please refer to #1481 to find steps.
![image](https://github.com/user-attachments/assets/22544eec-d471-41be-88c2-03ac32778992)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on stg successfully
