### ISSUE TITLE
[Compare] [FF specific] UI is broken if to open chat settings

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1947]
### EPAM AI DIAL chat version

0.16.0

### What happened?

1. In FireFox open two chats in compare mode
2. Click on Chat settings button in any chat -> the UI is broken -> **bug**
![image](https://github.com/user-attachments/assets/8fa5aaba-519e-435d-8fad-6c4e07a6f6c4)

Note: the issue is not reproduced in Chrome, Edge, Opera

**Expected result:**
![image](https://github.com/user-attachments/assets/1677e775-1047-4bc1-b5cc-b786d120b5ec)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
ticket is not actual after implementation new ui in #2740
