### ISSUE TITLE
[Publication] the text of the error is out of boundaries if there are no spaces

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1959]
### EPAM AI DIAL chat version

0.16.0

### What happened?

The part was fixed in #1915 The error looks fine if there are some spaces inside. But if there are no spaces the error is still out of boundaries (chats and prompts):
![image](https://github.com/user-attachments/assets/d46b01f2-bd80-4a24-a953-4de16fce4973)
![image](https://github.com/user-attachments/assets/257411cb-ee6b-4e39-a17d-f5ae0d363b49)

Please also note newly reported #1944 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on stg - fixed
