### ISSUE TITLE
Admin UI freezes on any action when organization section is opened

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1966]
### EPAM AI DIAL chat version

0.16.0

### What happened?

We need to find out why admin UI freezes on any action when organization section is opened

https://github.com/user-attachments/assets/4551b029-7579-46fb-ad98-4c48d9c51b99

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. If Approve required section is expanded on the "Conversation list" panel (~30 requests), now there is no any freezes in Admin actions. The same is on the "Prompt list" panel.
