### ISSUE TITLE
Add configurable option for role field/claim instead of hard-coded `dial_roles`

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1971]
### Description

Add configurable option for role field/claim instead of hard-coded `dial_roles`

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging with DevOps help, seems not working, waiting for new fix

**Comment by VolhaBazhkova** [comment]
Verified on staging with the help of @dspashynskyi 
DIAL_ROLES_FIELD was configured to set new user-administrator in Keycloak and in Auth0 providers. 
Please use https://github.com/epam/ai-dial-chat/tree/development/apps/chat for the details.
