### ISSUE TITLE
[Attachments] The chat can not be published or shared if to use a file from Organization section or from Shared with me. Need to have proper UI-error

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#1984]
### EPAM AI DIAL chat version

0.17.0

### What happened?

Preparation: publish a chat with attached files -> files appear in Organization section in Manage attachments 
Steps: Create a chat with the files from Organization section -> Share it or Publish it -> error appears 

![image](https://github.com/user-attachments/assets/0d1b88fc-11c8-44ca-ad1e-03d7bb9316a4)
![image](https://github.com/user-attachments/assets/3b2ceda4-dcad-474c-8a69-b269c5637175)

 ****Note:** the same issue if to share a chat with the files from 'Shared with me' section. But it looks like publish works! Need to be discussed why there is the difference and what is correct expected result if to use files from Shared with me and them share and publish the chat**

**Expected result:** we need to show these errors on UI:
1) Sharing failed. You are only allowed to share conversations with attachments from "All files"
2) Publishing failed. You are only allowed to publish conversations with attachments from "All files"
and no error in console

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified for chat created with file from Organization - > works as described

for chat with file from Shared with me:
1. possible to create publish request
2. on sharing error toast displayed 

![Image](https://github.com/user-attachments/assets/c057af5e-2145-40ce-a63a-1fb1727df363)
+ error from console "Resource does not belong to the user"
TO discus if it correct behaviour

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. Reported #2097
