### ISSUE TITLE
Implement opportunity to configure role path for each identity provider separately

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#1996]
### EPAM AI DIAL chat version

0.16.2

### What happened?

Implement opportunity to configure role path for each identity provider separately
I.e.
- `AUTH_AUTH0_ADMIN_ROLE_NAMES`
- `AUTH_AUTH0_DIAL_ROLES_FIELD`
- `AUTH_AZURE_ADMIN_ROLE_NAMES`
- `AUTH_AZURE_DIAL_ROLES_FIELD`
- `AUTH_GITLAB_ADMIN_ROLE_NAMES`
- `AUTH_GITLAB_DIAL_ROLES_FIELD`
- `AUTH_KEYCLOAK_ADMIN_ROLE_NAMES`
- `AUTH_KEYCLOAK_DIAL_ROLES_FIELD`
- `AUTH_PING_ID_ADMIN_ROLE_NAMES`
- `AUTH_PING_ID_DIAL_ROLES_FIELD`
- `AUTH_COGNITO_ADMIN_ROLE_NAMES`
- `AUTH_COGNITO_DIAL_ROLES_FIELD`
- `AUTH_OKTA_ADMIN_ROLE_NAMES`
- `AUTH_OKTA_DIAL_ROLES_FIELD`

according to Core-config where `aidial.identityProviders.keycloak.rolePath`, `aidial.identityProviders.azure.rolePath` and etc.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified with Yauheniya and Dmitro on staging env successfully. 
It works ok for the following providers: Okta, Congnito, Keycloak, Auth0
Was not able to check for Azure and Gitlab because of technical issues not connected to the implementation
