### ISSUE TITLE
[Apps Publication][Admin area]: Version of app displayed as postfix for app name in request form 

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2006]
### EPAM AI DIAL chat version

0.17.0

### How to reproduce

Steps:
1. Add application App1 using widget on Talk to page
2. Create publication request for this App1
3. create App2 and create publication request for it
4. admin review request for App1
5. admin review request for App2

### Actual result

- Name of application displayed with postfix with version
- request for App2 contain App1 in the list of application on the right side of the form

### Expected result

Names of Applications should not contain postfix with version ( versions for apps will be implemented in additional ticket)
Publication request should contain only Application from which request was created

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Alexander-Kezik** [comment]
- request for App2 contain App1 in the list of application on the right side of the form

this part is done

**Comment by Derikyan** [comment]
This part is also done  
 
- Name of application displayed with postfix with version

https://github.com/epam/ai-dial-chat/pull/2078

**Comment by YauheniyaH** [comment]
verified successfully on staging
