### ISSUE TITLE
Don't request published and shared data if these features are disabled

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2007]
### EPAM AI DIAL chat version

0.16.0

### What happened?

Don't request published and shared data if these features are disabled.
Also maybe we shouldn't request all conversations (only root  ones?) if conversation panel is disabled, but in the future conversation context menu can be moved into conversation header where we have `compare` for example

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
