### ISSUE TITLE
Files can not be downloaded from Unpublish request if the chat was published to a folder

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2008]
### EPAM AI DIAL chat version

0.17.0

### What happened?

1. Create a chat with some attachments
2. Publish the chat to any new folder in Organization (important step: to create a folder in Change path)
3. Create unpublish request 
4. By Admin open the request and download the files -> nothing happens -> **bug**

![image](https://github.com/user-attachments/assets/a110204d-478d-4210-8f33-25f49be95426)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified this part, but there are 2 related issues #2065, #2066
