### ISSUE TITLE
[Marketplace] Implement Client Data Service: save/read/update installed applications into Client Data

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2034]
### Description

Client Data documentation:
https://gitlab.deltixhub.com/Deltix/openai-apps/documentation/-/blob/10f5c41cf3a18ff41154830dda55f01079213cfc/design/marketplace.md#client-data
Implement Client Data Service (CRUD)

### Use case/motivation

save/read/update installed applications into Client Data

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env that the user can create/update/delete custom applications on mobile device and changes appear on laptop.
