### ISSUE TITLE
[Marketplace] implement Marketplace Card View

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2035]
### Description

implement Marketplace View with common layout with Grid-view:
- [x] opportunity to open Marketplace View qith header and "Back to conversations" button
- [x] opportunity "Back to conversations"
- [ ] Card-view of applications with "All applications" (without categories Featured and Popular)
- [ ] desktop/tablet/modile Card view
![image](https://github.com/user-attachments/assets/4c339cea-72d3-4f25-b844-fa79396917b5)
https://www.figma.com/design/rx9jQdZGvOuTUdzdunUn7p/DIAL-Marketplace?node-id=6589-79518&t=9TsdxxsX3wuEB6M4-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging, related issues created with prefix [Marketplace]
