### ISSUE TITLE
[Marketplace] opportunity to configure pre-installed applications

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2036]
### Description

opportunity to configure pre-installed applications: 
we need to have some short list of pre-installed applications (initial value for client data).
Maybe this config should be on API side?

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env.
RECENT_MODELS_IDS: "gpt-35-turbo,gpt-4,epam10k-semantic-search,gpt-world,mirror"
if to clear local storage or login by new user, these models are shown in My workspace and in Talk to  for New conversation 
See also #2286
