### ISSUE TITLE
[Marketplace] Implement or reuse Application View

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2037]
### Description

Implement or reuse Application View:
- pictures
- rates/comment view (separate ticket for rate/comment functional)
- tags (provided by API)
- capabilities (provided by API)
- "Use application" button

![image](https://github.com/user-attachments/assets/1267e04a-d367-42f2-9c08-5d82fdb3d87a)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Alexander-Kezik** [comment]
need to implement all other components
now only description, model icon and use button have been implemented

**Comment by YauheniyaH** [comment]
verified on staging, related issues create with prefix [Marketplace]
