### ISSUE TITLE
[Marketplace] My Applications View

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2038]
### Description

My Applications View/tab:
- list installed applications
- context menu with Rate and Delete
![image](https://github.com/user-attachments/assets/0b438d0d-1f02-46b9-a7ad-037c354a3715)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified in staging, related issues created with prefix [Marketplace]
