### ISSUE TITLE
[Marketplace] Filter panel (facets)

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2041]
### Description

- Implement the filter panel with facets
![image](https://github.com/user-attachments/assets/f87541a7-5fbd-4635-bcb0-9390008904db)
- collapsing/expanding of filter panel

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. Now there are Type (always 3 items) and Topics filters (appears if any topic is set in model or custom app)
