### ISSUE TITLE
[Marketplace] Header conversation context menu

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2046]
### Description

Header conversation context menu
![image](https://github.com/user-attachments/assets/38b43014-e9a8-4bbc-9d41-2ab753825bc6)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by DaryaKarniyenka** [comment]
New design
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=13793-62118&t=Jo6pSwANixchx3Vj-1

![Context_menu](https://github.com/user-attachments/assets/42723152-e794-4d45-a88a-d026c01d1d6a)

**Comment by YauheniyaH** [comment]
related issue #2667

**Comment by YauheniyaH** [comment]
Rename option will be added in next iteration

**Comment by YauheniyaH** [comment]
tested on staging successfully

**Comment by sr-remsha** [comment]
Described in u[ser guide](https://docs.epam-rail.com/user-guide#conversation-settings)
