### ISSUE TITLE
[Marketplace] redesigned Change Application/ Talk to modal

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2047]
### Description

- redesigned Change Application/ Talk to modal
- button "Search on DIAL Marketplace"
![image](https://github.com/user-attachments/assets/af09ddc2-94fa-45dd-91be-4553550e1008)
![image](https://github.com/user-attachments/assets/e316eb0a-c4ce-4aa4-951f-0e100c5f40f9)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by DaryaKarniyenka** [comment]
New design 
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=13796-64400&t=Jo6pSwANixchx3Vj-1

![Change_model](https://github.com/user-attachments/assets/80d6ab95-1a30-4e71-a6e2-b899e48d73a4)

**Comment by YauheniyaH** [comment]
verified on staging successfully
