### ISSUE TITLE
[Marketplace] support Topics for applications

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2086]
### Description

support Topics for applications:
- these fields should be in application listing (Core)
- these fields should be configurable for standard applications (Core)
- configure all these fields for standard applications (Core, DevOps)
- support these fields for Custom applications: create/read/update/delete (Chat)
![image](https://github.com/user-attachments/assets/6dfb07fb-494e-4f6c-916f-3a3c184dbee1)
- show these fields into Marketplace
- should we show these fields into "Talk to"?

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging for custom apps and quick apps
