### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2095]
### Description

New colors for these tokens:

1. Dark mode:

bg/layer-4 -> 424952
stroke/primary -> 424952
controls/text/disable -> 424952

2. Light mode:

bg/layer-4 -> C3C9D0
stroke/primary -> C3C9D0
stroke/secondary -> D4D9E0
controls/text/disable -> C3C9D0

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified by Darya on staging successfully
