### ISSUE TITLE
[Marketplace] update model icons and rendering

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2098]
### Description

update model icons and rendering:
- update theme-icons: colored SVG-icons with marging
- update Model icon rendering: circle with white background with 24px size and pay atteintion on shared and review sub-icons
![image](https://github.com/user-attachments/assets/83ed28b2-eb3b-4c6c-a3f2-83931fadb82e)
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=1999-7149&t=0FONRS09Yd4Lkp9L-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env, the icons for models were updated. Now they models/apps have an icon in a circle. The addons still have icon in a square.
For example,
![image](https://github.com/user-attachments/assets/9e5254b9-24b2-4d0d-b888-d75abc983c84)
![image](https://github.com/user-attachments/assets/c7cbd28d-cc4f-4e04-a6e7-c4305d55e0e3)
![image](https://github.com/user-attachments/assets/810c90bc-7a83-43d2-86df-a1d0b2a4afad)

Please note the in #2144 there was added "bg-model-icon" variable to theme config (see Dark theme). By default it's not presented in the Light theme and it means the transparent background. Verified that any color can be set as background, for example:
![image](https://github.com/user-attachments/assets/4ced17a9-f17f-4879-bb5a-330f199e58dc)
