### ISSUE TITLE
[Marketplace] Replace models dialog with my applications page 

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#2112]
### Description

need to remove full models list dialog and replace it with marketplace

- reuse search/filters/app creation logic from models dialog
- remove models dialog

### Related issues

#2047

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging 
related issues created with prefix [Marketplace]
