### ISSUE TITLE
Fix colors

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2113]
### Description

1. Bottom panel divider -> stroke/tertiary (Done)
For modal windows: manage attachments, attach file, select folder

Current: light
![image](https://github.com/user-attachments/assets/f8e5cbb6-dadd-4c10-ba83-2e711d8097e0)
Expected: dark (the same as in other windows)
![image](https://github.com/user-attachments/assets/254c0a91-d113-44a5-8266-1fbc2643c76d)

2. Attachments block stroke in chat -> stroke/secondary

Current: 
the strokes of the upper and lower blocks are different
![image](https://github.com/user-attachments/assets/1601cafc-e94b-43ab-b490-3b95559b43cd)
Expected:
![image](https://github.com/user-attachments/assets/c97e5401-5196-4a04-baed-2da618c4849a)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
second point from ticket was not implemented

**Comment by YauheniyaH** [comment]
verified on staging successfully
