### ISSUE TITLE
Add opportunity to set message template parameters for parametrized Replay 

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2162]
### Description

Add opportunity to set message template parameters for parametrized Replay 

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=12113-75057&t=vF0pV3vNbBngaC2Q-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified the first iteration on staging env. Found issues were discussed with the developer. Have not been reported yet.
