### ISSUE TITLE
make DefaultAssistantSubModelId parameter configurable

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2166]
### Description

make DefaultAssistantSubModelId parameter configurable (DEFAULT_ASSISTANT_SUBMODEL_ID, DefaultAssistantSubModelId in env variables)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully (0.18.0 version). 
NEXT_PUBLIC_DEFAULT_ASSISTANT_SUB_MODEL parameter is used to set a default model for Assistant.
