### ISSUE TITLE
[Marketplace]: listing API is triggered upon navigation to the Marketplace page

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#2177]
### EPAM AI DIAL chat version

0.18.0-rc

### What happened?

**Steps:**

1 Open Dial app
2 Create new conversation
3 Click on 'Search on My applications' link

**Actual result:** all listing requests are triggered

**Expected result:** need to trigger only necessary API calls

![image](https://github.com/user-attachments/assets/48030277-3ef5-4d51-a4be-c26480032e0c)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
I reproduced the ticket on UAT  (0.18 version): there are extra double requests for conversation created today, also extra listing requests (for chats, prompts, files). 
Verified on staging (0.19 version): now there are only necessary requests:
![image](https://github.com/user-attachments/assets/f7dcb1cc-928e-4b9a-bf21-4e337f5e8d23)
Reported #2424
