### ISSUE TITLE
[Custom app]: Published icons' files for custom app can not be unpublished

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2180]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Precondition:
There is published custom application
Icon file of this app is available in Manage Attachments in Organization section

Steps:
1. create unpublish request for custom app -> icon file is not displayed in the request form
2. submit request
3. by admin open request -> icon file is not displayed in the request -> bug
4. by admin approve unpublish request
5. refresh page
6. open Manage attachments, view Organization section -> icon file is still available in Organization -> bug

### Actual result

 icons' files for published custom app can not be unpublished

### Expected result

Unpublish request for custom app should also contain icon file

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Gimir** [comment]
Temporarily remove files from unpublish requests untill nested folder concept is ready.

**Comment by YauheniyaH** [comment]
Issue can not be tested until unpublish files concept will be defined
