### ISSUE TITLE
[Marketplace] Reduce padding between icon and text in buttons

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2212]
### Description

Reduce padding from 12 px to 8 px in all buttons 

![image](https://github.com/user-attachments/assets/0504b6ee-cb72-461f-a503-482a0f4cf6c0)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=10100-14590&t=vF0pV3vNbBngaC2Q-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified the following buttons:
Add app
Use application
Use model
Use assistant
Add the agent to My workspace to continue
Start replay
Duplicate the conversation to be able to edit it (from Organization and Shared with me in Chat history)

@IlyaBondar Please fix also 'Use ...' buttons

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
