### ISSUE TITLE
Change tree paddings in side panels

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2213]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Open conversations or prompts side panel 

### Actual result

The icons are not positioned exactly under the text
![side_panel_paddings](https://github.com/user-attachments/assets/e0230d05-bb8b-4257-a55e-b22dd5258f5f)

### Expected result

![side_panel_correct_paddings](https://github.com/user-attachments/assets/40bfed17-1b06-4709-bb58-3504b95d83ce)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=10395-16241&t=vF0pV3vNbBngaC2Q-1

---

Also let's increase profile settings and side panels size **ON MOBILE** from 260px to 302 px.

![mobile_side_panel](https://github.com/user-attachments/assets/a7e4f6a0-4c56-42bb-80df-4f16f86ecc34)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11630-59803&t=vF0pV3vNbBngaC2Q-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env
1) conversations and prompts, attachments: icons are located under the text like in Figma
2) the width for Mobile will be checked in #2389
