### ISSUE TITLE
[Marketplace] newly selected model disappears from Talk to list if to add it and click to another model from Talk to

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2216]
### EPAM AI DIAL chat version

0.18.0

### What happened?

1. Click on + New conversation
2. Click on Search on My application
3. on Home page click on any model, which is not on Talk to for New conversation. For example, click on Mistral Large -> click on "Use model" -> note that the Marketplace is closed and Mistral Large is shown at the top of the Talk to list -> ok
4. Click on any model/application on Talk to -> the list in Talk to is changed: Mistral Large disappears from the list -> **bug**

https://github.com/user-attachments/assets/cfc5e6af-7f18-4744-9f14-eb66d36d6511

**Expected result:** newly selected model should stay in Talk to list

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
