### ISSUE TITLE
[Marketplace][Custom app] updated icon is not changed on the card view

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2224]
### EPAM AI DIAL chat version

0.18.0

### What happened?

1. Open 'DAIL Marketplace' -> click on 'My applications' -> Click on '+ Add app' button
2. Fill in required fields. Set Icon1 and click on 'Add' button -> custom application appears, Icon1 is set - ok
3. Click on the custom application -> the card view is opened
4. Click on the Edit button
5. Change Icon1 to Icon2 -> click on Save
6. Note that the icon is changed on the My applications page, but is not on the card -> **bug**

![image](https://github.com/user-attachments/assets/7d2cceca-a727-4147-b1e5-7ef49d7b9329)

Expected: new icon should be updated on the card view

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
