### ISSUE TITLE
[Marketplace][Custom app] Need to add a tooltip to Edit button on the card view

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2225]
### EPAM AI DIAL chat version

0.18.0

### What happened?

![image](https://github.com/user-attachments/assets/e1edf75b-a9dc-4d39-8b3c-5d240d21e22d)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
