### ISSUE TITLE
[Marketplace]: Add opportunity to remove specific version of model from My application

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2226]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Steps:
1. add to My application several versions of one model, e.g. GPT-4 Turbo
2. go to My applications
3. hover GPT-4 Turbo tab and select Remove
4. click on GPT-4 Turbo tab

### Actual result

3. Latest version of model was removed from My applications
4. no remove option

![image](https://github.com/user-attachments/assets/cbbd7e5c-5251-474a-8059-6f50be97dcd5)

### Expected result

Need to add Remove button on modal window of Model/Assistant/App
Remove button will remove only selected version
Design to be added

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by DaryaKarniyenka** [comment]
**Desktop:**
- add remove button to the bottom panel 

![image](https://github.com/user-attachments/assets/1809e897-43e1-468b-a287-126e98acfd6c)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11631-36996&t=R2CeoGAKVcWSDnzb-1

**Tablet:** the same as for desktop

**Mobile:** 
- hide buttons in drop down if there is more than one 
- show "v." for version

![image](https://github.com/user-attachments/assets/84e95bc6-ae60-4e57-b8dd-1155fe2acffc)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11630-59508&t=R2CeoGAKVcWSDnzb-1

Also let's show "Share" list in a separate modal window for mobile
![image](https://github.com/user-attachments/assets/85a28f1b-ea28-4570-aea4-8fa2a133df6c)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=12363-73084&t=R2CeoGAKVcWSDnzb-1

**Comment by YauheniyaH** [comment]
NOTE: check icons' tooltips on app' modal form

**Comment by YauheniyaH** [comment]
Verified on staging
related issue #2287, #2290
