### ISSUE TITLE
[Custom app] need to add validation for Attachment types field on onblur event

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2227]
### EPAM AI DIAL chat version

0.18.0

### What happened?

Now validation appears only on Enter. but also should be if to move cursor out of the field (onblur event)

![image](https://github.com/user-attachments/assets/24f6c11c-abf1-4a27-92f7-e587fc6e21b6)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
related issued 
#2250, #2251
