### ISSUE TITLE
[Marketplace][Custom app] custom application disappears from My applications if to updated the version from the card view or Edit context menu

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2230]
### EPAM AI DIAL chat version

0.18.0

### What happened?

1. DIAL Marketplace -> My applications ->+ Add app -> create any application and Add it
2. Click on the added application -> the card view is opened
3. Click on Edit button -> Change version -> Save
4. Note the app disappears from the My applications -> **bug**
It appears only after browser refresh
The same if to edit using context menu

https://github.com/user-attachments/assets/b24ef598-ba45-42ec-be6c-f120907fdf79

**Note: The same if to updated the app name**

**Expected:** The app should stay on My applications with updated version

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
tested on staging successfully
