### ISSUE TITLE
[Marketplace]: Icons of files has incorrect color on Manage Attachments

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2233]
### EPAM AI DIAL chat version

0.0.18

### How to reproduce

1. Open manage attachments form
2. review icons of files

### Actual result

![Screenshot 2024-09-27 at 16 41 34](https://github.com/user-attachments/assets/836875ba-f92f-45b4-b92b-72673a092745)

### Expected result

icons of files should be of the same color as icons of folders

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully (Dark and Light themes)
