### ISSUE TITLE
Redesign of message template editor

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2235]
### Description

Redesign of message template editor:
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=12326-85217&t=toHcFk5x2G7JfxM7-1 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Please update also the test on the Message Template form
Should be:
Copy a part of the message into the first input and provide a template with template variables into the second input.

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully along with other fixes. See also #2291
