### ISSUE TITLE
[Marketplace] UI corrections

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2243]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Open marketplace

### Actual result

1.
 ![image](https://github.com/user-attachments/assets/9fa66102-25b2-4a7b-b54a-42cf94018ede)
2. Tablet 
![image](https://github.com/user-attachments/assets/22fe3b84-3b4e-4d36-865f-2b9908e9b81f)
3. Mobile 
![image](https://github.com/user-attachments/assets/93a376d1-3b08-4b6c-95ea-188954e8a5a0)

### Expected result

1. 
- Icons size = 24 px
- Add divider for "Back to Chat"
- Set correct paddings between sections 

![image](https://github.com/user-attachments/assets/57677247-d044-4637-b26f-423dab2a6f5c)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11680-70900&t=R2CeoGAKVcWSDnzb-1

2. 
![image](https://github.com/user-attachments/assets/5d6877a2-0d6e-464f-9caf-d252014c9df7)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=12190-60330&t=R2CeoGAKVcWSDnzb-1

3. Search must be full width

![image](https://github.com/user-attachments/assets/03f721c6-20c5-4e1c-939a-7e68fb5f0821)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11630-58745&t=R2CeoGAKVcWSDnzb-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
need to add arrow "Back to chat" to header for mobile view

Actual result 
![Image](https://github.com/user-attachments/assets/0ca3fa2d-eec1-478a-a628-cf3e9c41bd2a)
Expected:
![Image](https://github.com/user-attachments/assets/df836e4f-3fc2-4811-a440-d6edecacfa68)

**Comment by YauheniyaH** [comment]
verified on staging succesfully
