### ISSUE TITLE
[Message template] UI corrections

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2275]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Open Message template window

### Actual result

1.
![image](https://github.com/user-attachments/assets/8673ebbb-23c3-48fb-b7ab-41439d04224a)
4. 
![image](https://github.com/user-attachments/assets/00023f6f-4329-4f87-8030-e43b5bad3ff5)

### Expected result

1. Show "Show more" ~on new line and~ without icon
![image](https://github.com/user-attachments/assets/5b96f730-f738-4cf9-9fd4-75342f48195a)

2. Need to correct paddings
![image](https://github.com/user-attachments/assets/af0b108f-2a12-4fdf-b9f8-125396697191)

3. Mobile: need to correct paddings
![image](https://github.com/user-attachments/assets/a9aaa907-e62b-4d84-ba13-2b4959fec5c0)

4. Change text to fit on one line. Example:
![image](https://github.com/user-attachments/assets/dd7ddfc0-4fb2-4b46-8d63-9e2697acc935)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env:
1) arrow icon in Show more/less was removed
2)-3) paddings were partly fix. Please see a separate ticket #2291
4) the phrase was updated to: Your template with {{variable}}
