### ISSUE TITLE
[Marketplace][UI]: Icons has incorrect color for selected items on side panel on marketplace page

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2278]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Steps:
1. Open "DIAL Marketplace"
2. Select Home page
3. collapse side panel

### Actual result

For both collapsed and expanded side panel:

1.  icons for selected item in side panel have incorrect color
2. no vertical blue line at the beginning of the string
![Screenshot 2024-10-03 at 11 51 12](https://github.com/user-attachments/assets/c9f57acb-7d96-4a96-a6e6-86eba2b12892)
![Screenshot 2024-10-03 at 11 46 49](https://github.com/user-attachments/assets/fb16b4df-f282-40ef-a52f-fcc20f1c29b6)
3. incorrect 'home' icon

### Expected result

1,2 according to figma selected item icon should be blue and blue vertical line should be in the beginning of the string
![image (42)](https://github.com/user-attachments/assets/2fde32a3-1cd0-49fc-8ca6-f08311fd2719)
![image (41)](https://github.com/user-attachments/assets/7f2873bb-e5a2-450e-9c61-6bc515f03753)

3. also 'home' should be different according to design https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=10100-15364&node-type=frame&t=vkkn0R1H53HKMISF-0
![image](https://github.com/user-attachments/assets/c2bbe9fc-9183-4935-a6f4-3568e0041544)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
