### ISSUE TITLE
[Message template] UI corrections 2

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2291]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Open Message template window

### Actual result

1. All resolutions: change paddings as shown in the screenshot
![image](https://github.com/user-attachments/assets/afaf41f1-1e1e-48b8-b66e-1c763c33e907)

2. DESKTOP AND TABLETS ONLY: change paddings
![image](https://github.com/user-attachments/assets/29620e4b-e17d-44b1-99fc-91d5d19c0612)

3. MOBILE ONLY: change paddings
![image](https://github.com/user-attachments/assets/08017522-4221-4180-8509-67e029ebdf14)

4. Remove word "message" from the mobile context menu
![image](https://github.com/user-attachments/assets/53fcc2fa-0a92-404e-95a3-4f12d6d16b7a)

### Expected result

1-2. 
![image](https://github.com/user-attachments/assets/a8240c78-0d49-45b8-aa5c-46435033d663)
3. 
![image](https://github.com/user-attachments/assets/7a725337-de4d-4dbe-a478-5da0f7bfeaed)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=12326-85217&t=LCoGf0T9P8jYTnWW-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env. Reported #2306
