### ISSUE TITLE
Setting model id not working in overlay

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#2297]
### EPAM AI DIAL chat version

0.18.0-rc

### How to reproduce

1. Setup model id in overlay options
2. Open overlay

### Actual result

When opening overlay chat is with wrong model id (from last conversation)

### Expected result

When opening overlay chat should be with model which we set in overlay options 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified locally and in sub-project-staging env successfully. Reported #2636
