### ISSUE TITLE
[Marketplace]: Add dropdown icon for 'Add app' button and align dropdown values with button width

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2319]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Steps:
1. click on "DIAL Marketplace" button
2. click "My applications" button on side panel
3. click on "+ Add app" button 

### Actual result

Drop down with options Custom app and Quick app opened
![Screenshot 2024-10-08 at 10 54 46](https://github.com/user-attachments/assets/88db692c-d7d6-42a6-bc27-55a6434cf3e2)

### Expected result

1. Replace + in the button to dropdown arrow
2. Align width of dropdown values with 'Add app' button's width

![image](https://github.com/user-attachments/assets/343452da-21f5-43c9-bb0d-9e6186b0392d)
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11654-53700&node-type=frame&t=frDzDhvFlhGwzze5-0

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully.
1. If to enable Custom applications, Disable Quick applications => there is + Add app button, if to click on it 'Add custom application' opens
2. If to enable Quick applications, Disable Custom applications => there is + Add app button, if to click on it 'Add quick application' opens
![image](https://github.com/user-attachments/assets/53a66585-dea8-4245-960c-b077c161b587)
3. If to enable both features => there is Add app with arrow, if to click on it there are two options 'Custom App' and 'Quick App'
![image](https://github.com/user-attachments/assets/0bc11954-601b-41db-8459-58a8375a5c89)
