### ISSUE TITLE
[Marketplace]: redirect to chat's details instead on Talk to modal when edit chat's settings

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2330]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Preconditions:
there is a conversation with at least one message and response

Steps:
1. click on chat's name from precondition in side panel
2. click on gear icon in the chat's header
3. remove chat's model from My applications
4. click Back to chat ->  returned to chat's details screen-> bug

### Actual result

user is returned to chat's details screen

### Expected result

Need to return to Talk to modal form 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
See also #2221 - similar mechanism should be used

**Comment by VolhaBazhkova** [comment]
Not reproduced because of re-design of settings and the logic of Back to Chat
