### ISSUE TITLE
add modulify-ui library

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2331]
### Description

This MR adds modulify-ui, a React library comprised of two powerful tools, Inversify and ComponentBuilder, designed to enhance component flexibility and simplify complex customization processes.

Inversify: Decouple component implementations for easy swapping and conflict-free customization of forked code.
ComponentBuilder: Structure component building with fine-grained control over state, styles, HTML, and more.

Author: @sergesha

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified new conversation context menu functions and talk to settings on staging env. successfully
