### ISSUE TITLE
[Marketplace] it looks like the tabs are moving if user switches between them (All applications and My applications)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2335]
### EPAM AI DIAL chat version

0.18.0

### What happened?

[Marketplace] it looks like the tabs are moving if user switches between them (All applications and My applications)
Please see the video

https://github.com/user-attachments/assets/7705db6f-0b47-49c7-aead-0f7823421053

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
use `border-transparent` for not selected ones

**Comment by YauheniyaH** [comment]
verified on staging successfully
