### ISSUE TITLE
[Marketplace]  model/applications icon are changed to default icon on the 'Conversation list' panel. They are restored after refresh and switching to DIAL Marketplace and return back

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2347]
### EPAM AI DIAL chat version

0.18.0

### What happened?

[Marketplace] after deploy model/applications icon are changed to default icon on the 'Conversation list' panel. They are restored after refresh and switching to DIAL Marketplace and return back

![image](https://github.com/user-attachments/assets/8407c8a1-7d63-4868-87ec-5810e14878d3)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Case 2:

Steps:
1. Duplicate any chat from Organization
2. Refresh page -> 2 duplicated chats displayed , name changed to model name
3. Refresh page -> default icons are displayed for all models 


https://github.com/user-attachments/assets/1d118109-f4bb-43a7-940b-4054a2e90072

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. Now default icons are seen only for a moment after browser refresh
