### ISSUE TITLE
[Marketplace] add bookmarks clickable icons in Marketplace to add/remove from My Workspace 

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2349]
### Description

add bookmarks clickable icons in Marketplace to add/remove from My Workspace 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by DaryaKarniyenka** [comment]
![DIAL Marketplace_Home Page](https://github.com/user-attachments/assets/c3ba0d1f-6265-4256-a772-a374a15312c0)
![image](https://github.com/user-attachments/assets/858314f3-fd64-492b-8760-688f49e23326)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11631-37197&t=DFTnjQZHwmIRBV8M-1

Mobile 
![image](https://github.com/user-attachments/assets/c2282b62-7cdf-4c21-8bba-c843fe7adbe7)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11630-59508&t=DFTnjQZHwmIRBV8M-1

**Comment by VolhaBazhkova** [comment]
Please fix also hover on icon
Now: 
![image](https://github.com/user-attachments/assets/0fdf73f0-0620-4d85-87c6-1e8e06b6b3e1)
Expected:
![image](https://github.com/user-attachments/assets/e6d0cd9b-0fe7-42ce-b515-cbcc331ece02)

**Comment by YauheniyaH** [comment]
verified on staging
related issues #2449

**Comment by sr-remsha** [comment]
Described [here](https://docs.epam-rail.com/user-guide#add-to-my-workspace)
