### ISSUE TITLE
[Marketplace] show loader after click on "DIAL Marketplace" or "Search on My workspace"

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2350]
### Description

show loader after click on "DIAL Marketplace" or "Search on My workspace" or "Back to Chat"

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env. Now there is loader if to click on  "DIAL Marketplace" or "Search on My workspace" or "Back to Chat". 
Please note that we see two loaders: 1) when open DIAL Marketplace 2) when model card are loaded. It's ok if there is any network issue, but when there is perfect connection it looks not so nice. Decided to leave it until any feedback from user. Please see the video. 

https://github.com/user-attachments/assets/e3616b17-b769-4ee1-8a24-0e56c438f84f
