### ISSUE TITLE
[Marketplace]: New conversation created when go to DIAL market place from duplicated published chat and Back to Chat. Duplicated published chat name changed to model name

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2352]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Preconditions:
there is at least one chat in Organization available for user

Steps:
1. Duplicate published chat -> focus is on duplicated chat
2. Click "DIAL Marketplace" button
3. Click "Back to chat" -> 2 chats instead of duplicates displayed, name of chats changed to model name -> **Bug**
4. select focus on duplicated chat
5. Click "DIAL Marketplace" button
6. Click "Back to chat" -> New conversation 1 was created -> **bug**

### Actual result

https://github.com/user-attachments/assets/25e3d985-c21e-4b84-9307-dfdc6987803a

Note: issue is not reproducible for created chat or for duplicated shared chat.

### Expected result

3. duplicated chat should not be duplicated when refresh page. 
name of the chat should not be changed to model name
6. New conversation should not be created when Back to Chat from Market place

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
@Alexander-Kezik Please look thru the fix one more time. The issue is still reproduced. 


https://github.com/user-attachments/assets/de77f0f0-cb1c-4269-b948-0457b9ea401f

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully (previously it was a problem with CI process)
