### ISSUE TITLE
Publish: Need to implement "Approved required" section

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#236]
### Description
Admin should be able to see all requests for approvals and counter of unread requests.
Unread requests/items marked by green/violet dot on icon. 
When admin viewed item then green/violet dot disappears from item icon. 
When admin viewed all items in request then green/violet dot disappears from request icon. 

### Mockups
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3741-11008&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/4fff126f-6707-4cc1-89aa-b4691957afb9)

**Comment by YauheniyaH** [comment]
It was stated on daily meeting that counter in approve required section will not be implemented in first release of Publish functionality
Feature about dot in icon was moved to #1457

Inside current feature need to check other functionality of Approve required section

**Comment by YauheniyaH** [comment]
Verified on STG
