### ISSUE TITLE
Regenerate button is available and can be pressed if the model is not allowed (error in console appears, the chat hangs)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2360]
### EPAM AI DIAL chat version

0.18.0

### What happened?

1. Create custom application -> create a chat based on the applications and send several messages there
2. Remove the application
3. Open the chat -> note that "Not allowed model selected. Please, change the model to proceed" appears instead of input -> ok
But Regenerate button is available -> **bug**
![image](https://github.com/user-attachments/assets/4f9b4d71-c118-4dc1-aad9-0193f6a0da25)

If to click on it - error in console appears

![image](https://github.com/user-attachments/assets/18b435db-4f82-4339-b8f6-ca4cc60b90fe)

Expected result: 
Regenerate button should not be available if the model/application is not allowed or not exists

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
related issue #2784
ticket is verified on staging
