### ISSUE TITLE
Make DIAL logo clickable which lead to latest selected conversation

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2369]
### Description

After Marketplace implementation it will be useful to make EPAM DIAL ( or custom logo) clickable (use the same logic as for Back to chat)

![Screenshot 2024-10-14 at 14 09 24](https://github.com/user-attachments/assets/4d5da564-38b7-4676-aa1a-a05818ef8e1d)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Return to @Gimir because new expected result is needed. 
Now click on Logo works as Back to Chat
Expected click on Logo creates New conversation

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
