### ISSUE TITLE
[Marketplace] redesign of card view

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2373]
### Description

redesign of card view
Cards: https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=10525-44705&t=SJQQkoofk3cjclxX-1

Dark UI: https://www.figma.com/proto/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?page-id=11630%3A38064&node-id=11631-36354&node-type=frame&viewport=3430%2C2909%2C0.39&t=iImLFLow52QVcItL-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=12711%3A46938

Light UI: https://www.figma.com/proto/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?page-id=11630%3A38064&node-id=11716-59140&node-type=frame&viewport=3312%2C3401%2C0.34&t=xDCwop5VPXorCEo2-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=12711%3A46938

Note that the cards now have shadows and the corner rounding has changed.
![image](https://github.com/user-attachments/assets/4c0753ac-b481-4d85-9262-cd1e3dce0b79)

Also let's change paddings on the page and in the card grid. Change the rounding of the banner's corners.
![image](https://github.com/user-attachments/assets/35a009db-daae-4b3b-9f38-7b70954bd14f)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. See also #2426
