### ISSUE TITLE
Use token limits from listing

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#239]
1. We agreed not to announce limts in the apps. For now.  
2. We have tokenizerModel to specify unit of window measures
|-> String tokenizerModel; https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb , Define and document enum of global standard tokenizer model.
https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken
There will be:
- standard supported tokenizer model list. Global across all installations
- custom list. Specific for deployment. That extends the standard one. (we will recommend use prefixes for custom extensions)
In case new model appears:
  1. It uses known tokenization algo. -> specify it tokenizerModel
  2. It uses new tokenization algo, and we think it wort being supported ->  extend standard list, and support on FE
  3. Otherwise -> keep tokenizerModel blanc, or specify custom value. FE will use not tokenize messages for this model.
- If we have history. 
  1. For stadanrd tokenization algo: we MAY dynamically show what is going to be in the context (and refine it once we get response from)
  2. Else: we can only show what is in context once we get response
- It's mandatory for the models to have "maxTotal or (maxCompletion and maxPrompt)"
- Let's add max_prompt_messages (if more -> error), max_system_messages (if more -> error). Let's add "one shot" feature flag (app/adapter ignroes history).
- system prompt limits  := prompt limits
 
Frontend may start with implementing default case, and continue with tokenization algo bit later.
- if model supports "truncatePrompt"
  - If model announces its maxPrompt, chat will set this value to request.maxPrompt
  - if model announces its maxTotal, chat will set request.maxPrompt = min(2000, 0.75 * maxTotal)
  - if chat receives "maxPrompt tokens limit reached", chat removes all messages except system and the very last role = "user" and repeat request without maxPrompt.
  - In case second fail, chat show error to the user.
- Otherwise chat fallbacks to its own implementation of the algo above, that uses own tokenization (in case no tokenization with fallback on token:=byte)

**Comment by avavilau** [comment]
Among other things do not allow entering too long prompts.

**Comment by vladisavvv** [comment]
Limits model:
```
limits: {
    maxTotalTokens: 1,
    maxPromptTokens: 2,
    maxCompletionTokens: 3
}
```

**Comment by VolhaBazhkova** [comment]
Verified on staging env. Now there is the following kind of message:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/2009fd7c-d61d-45d9-827b-c770072d4953)

Entered or pasted text, which exceeds the limits is not added after pressing Confirm button on the pop-up.
