### ISSUE TITLE
[Marketplace] Cards redesign corrections

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2426]
### EPAM AI DIAL chat version

0.19.0

### What happened?

1. Paddings in the card grid should be 20 px
![image](https://github.com/user-attachments/assets/248e9077-79f7-422c-9b01-8173324e3dd4)
2. Fix the position of the topics
Current:
![image](https://github.com/user-attachments/assets/c2c75cb7-912e-4ae4-9f24-253deeb10625)
Expected:
![image](https://github.com/user-attachments/assets/5eed5cb0-4dd5-42d2-b37f-31da15b25609)
3. Shadows should be deeper as in Figma
Current:
![image](https://github.com/user-attachments/assets/4f568b65-c101-424a-8d1d-a43bd0bb1b46)
Expected:
![image](https://github.com/user-attachments/assets/280bf973-ea23-42df-9177-fafe7f88129f)
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11716-59140&t=lc1BSyKuQr5vdWBo-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
