### ISSUE TITLE
Incorrect markdown rendering inside DIAL chat

### ISSUE THREAD

**Issue by sdryapko** [epam/ai-dial-chat#2446]
### EPAM AI DIAL chat version

0.15

### What happened?

Prompt to reproduce: 

"- create a markdown table that has 5 columns, that have the cells are aligned to the middle both vertically and horizontally"

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Reproduced on 0.15.6 version:
![image](https://github.com/user-attachments/assets/984869d7-770d-4404-a37e-931f129ab4ee)

Verified on staging env on 0.20.0 version:
![image](https://github.com/user-attachments/assets/24f8738c-3b1c-4be6-8053-a5788f6826f6)
