### ISSUE TITLE
[Marketplace] UI corrections for bookmarks

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2449]
### EPAM AI DIAL chat version

0.20.0

### What happened?

1) on the cards with long names and long versions there is not nice view
![image](https://github.com/user-attachments/assets/7eefa81c-9e52-4715-9812-650217e1c3fd)
![image](https://github.com/user-attachments/assets/c1889a1a-27e0-4847-a44d-16d7053c1e08)

2) on laptop need to add tooltip explanation
![image](https://github.com/user-attachments/assets/d6bb505a-0cfc-4132-bc57-688a3ab62b60)

3) on mobile need to remove tooltip if to open the card
4) on laptop **only** need to show three dots context menu on hover
5) dots color should be text/secondary
![image](https://github.com/user-attachments/assets/70286ff3-17d9-44d2-b0d4-3f7cd5e676b7)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
