### ISSUE TITLE
[Marketplace] Add app button and search height should be the same 

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2459]
### EPAM AI DIAL chat version

0.20.0

### What happened?

![image](https://github.com/user-attachments/assets/ad0912be-63bf-4ce4-a684-391fd86cac9f)

 Add app button and search height should be 38px

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
It's a duplicate of #2439
