### ISSUE TITLE
[Code apps] it's necessary to add validation about the existence of the "app.py" file

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#2475]
### EPAM AI DIAL chat version

0.19

### What happened?

it's necessary to add validation about the existence of the "app.py" + "requirements.txt" files cause it's the entrypoint for code app
![image](https://github.com/user-attachments/assets/e026b4ac-6eda-416f-a334-a7f8dec9df04)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
