### ISSUE TITLE
[Code apps] Implement code editor

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#2478]
### EPAM AI DIAL chat version

0.19

### What happened?

need to implement code editor
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=12921-76965&t=hGJg8NEyh6raLxYV-4

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging, related issues created

**Comment by sr-remsha** [comment]
Documented in [user guide](https://docs.dialx.ai/tutorials/user-guide#addedit-code-app-form)
