### ISSUE TITLE
Organization section disappears from Select application icon

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2481]
### EPAM AI DIAL chat version

0.20.0

### What happened?

Organization section disappears from Select application icon (open from Custom app, Quick app)

![image](https://github.com/user-attachments/assets/74419f14-e704-4208-aca6-a40cc3c1e62b)
Expected: Organization should be while icon selection (if there are some files in published chats)

Once after DIAL redeploy the section has appeared, but than again disappeared... Sometimes issue

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
