### ISSUE TITLE
[Code apps] Need to add ability to view logs while code app is running

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#2484]
### EPAM AI DIAL chat version

0.19

### Expected result

Need to add ability to view logs while code app is running

```
response = send(HttpMethod.POST, "/v1/ops/application/logs", null,"""
    {
        "url": "applications/{bucket}/{path_to_app}"
    }
""");
```

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
