### ISSUE TITLE
'Target resource already exists' error appears if to create publish request for custom app if the same icon has already been used in another published custom app or in another version of the same custom app

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2493]
### EPAM AI DIAL chat version

0.20.0 - 0.18.0

### What happened?

Steps to reproduce1:
1) Create custom app using icon1 -> publish the app (create the request, approve by admin)
2) Create custom app2 using the same icon -> create publish request -> 'Target resource already exists' error appears -> **bug**

Steps to reproduce2:
1) Create custom app using icon1 -> publish the app (create the request, approve by admin)
2) Update the same custom app, change the version, don't change the icon -> create publish request -> 'Target resource already exists' error appears -> **bug**

**Expected result:** user can use the same icon as many times as it's necessary. No any error should appear

![image](https://github.com/user-attachments/assets/7e262a7a-dcb0-4abc-8487-197f3d38a7e2)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Please find out similar ticket for Chat publication #2207

**Comment by YauheniyaH** [comment]
related issue #2634

**Comment by YauheniyaH** [comment]
verified on staging
