### ISSUE TITLE
[Code Apps] successful toast message appears for all users when Admin deploys Code app  

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2497]
### EPAM AI DIAL chat version

0.20.0

### What happened?
If the code app is available for several users and when Admin deploys the code -> app successful toast message appears for these users -> **bug**

Expected: the message should appear for Admin only

![image](https://github.com/user-attachments/assets/bd6199fb-26c6-4f6b-872d-9126a481a9a5)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
