### ISSUE TITLE
[Code app]: Using code app from examples in chat cause error

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2529]
### EPAM AI DIAL chat version

0.20.0

### How to reproduce

Steps:
1. Open add Code app form
2. Add attachment type pdf and number of attachments 1
3. select empty folder for source files
4. click Add example "Simple RAG" link
5. input Env variable DIAL_URL
6. save application
7. click Deploy button on application card
8. after Code app deployed use it cor chat
9. Attach pdf file and ask question about it
10. send message

### Actual result

error is displayed in response
<img width="861" alt="image (55)" src="https://github.com/user-attachments/assets/9c82b9c8-4782-4bd1-afd3-e7fd5e8495f4">

In Code app logs
![Screenshot 2024-11-05 at 13 51 47](https://github.com/user-attachments/assets/c17ef609-b644-426b-8f31-6cfb5ca06238)
Log from example "Hello world"
<img width="834" alt="image" src="https://github.com/user-attachments/assets/46c08678-d6c0-4605-967e-9b552fef57ee">

### Expected result

response should be provided by app

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
for the example `Simple RAG`:
- `app` should be replaced by `simple-rag` in `Chat completion` 
- add the env variable "DIAL_URL=https://dev-dial-core.staging.deltixhub.io/" (found in log information)

for the example `Hello world`:
- `app` should be replaced by `echo` in `Chat completion` 

`Chat completion` should be updated according to name from `app.add_chat_completion("<NAME>", ....)`

**Comment by YauheniyaH** [comment]
related enhancement #2536
