### ISSUE TITLE
Limit attachments files and folders with special characters in name

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#253]
: ; , = /
On Chat UI - We should show error message when attachment has special characters in name 
On core API - reject such files with special characters in name (@avavilau to discuss with @Maxim-Gadalov)

**Comment by VolhaBazhkova** [comment]
@IlyaBondar returning the ticket. 
We need to show error on "Upload from device" pop-up if user renames the files using ;:,/= symbols. 
Now we show error on Attach files pop-up and for the file with : Also file with / in name isn't shown at all. Files with ;,= is uploaded without any error

![image](https://github.com/epam/ai-dial-chat/assets/111180458/03761375-8235-4f7d-a250-ce742d553d1b)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
