### ISSUE TITLE
[Code Apps] fix application logs displaying

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2534]
### EPAM AI DIAL chat version

0.20.0

### What happened?

![image](https://github.com/user-attachments/assets/462ac4eb-7360-49c6-913d-df4a70c443ce)

need to align-top and decrease line gaps

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
