### ISSUE TITLE
[Code Apps] Add reload button to the logs window 

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2546]
### Description

![image](https://github.com/user-attachments/assets/a8c9d984-6210-4c70-b54d-2d397c18b0d6)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=13440-65237&t=ygu6gjYhpPOxww1u-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully

**Comment by sr-remsha** [comment]
Added to the [user guide](https://docs.dialx.ai/tutorials/user-guide#to-access-code-app-logs)
