### ISSUE TITLE
[Code app]: Update confirmation message for deleting files 

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2558]
### Description

In order to highlight that files will be removed without button Save click on Code app form need to update confirmation message:
Actual: Are you sure that you want to delete <file name>
Expected: Are you sure that you want permanently delete <file name> ?
![image](https://github.com/user-attachments/assets/991dcdb1-9883-438a-a2bf-f1ccb832eba0)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
@YauheniyaH , @DaryaKarniyenka , @Derikyan 
I think it should be `Are you sure that you want to delete {{name}} permanently?`

**Comment by YauheniyaH** [comment]
verified on staging successfully
