### ISSUE TITLE
Add gitlab like notifications

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#256]
![Image](https://github.com/epam/ai-dial-chat/assets/6322751/2cb20adb-e0fd-4cd3-b00d-989711cbc42c)

**Comment by mikitabut** [comment]
This ticket was implemented in next way - 
1. if client configured ANNOUNCEMENT_HTML_MESSAGE it will be shown for all people
2. If user dismissed message it will be hided before any changes in text
3. Message support some simple html

**Comment by VolhaBazhkova** [comment]
Verified on laptop, tablet, mobile successfully.


![Image](https://github.com/epam/ai-dial-chat/assets/111180458/6f28c12a-b04f-4a0b-8bca-038058c3a64d)
