### ISSUE TITLE
[Code app]: Hello world application created from example return link in response

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2564]
### EPAM AI DIAL chat version

0.21.0

### How to reproduce

Steps:
1. open Add code app form
2. select any empty folder for source files
3. click "Add example "Hello world"" link
4. in Chat Completion field add "/openai/deployments/echo/chat/completions"
5. save app
6. deploy app
7. click "Use application" button
8. enter any text to message

### Actual result

Response return some part of url for each message "deploy...<ulr text>..com"

### Expected result

Need fix example's source files to return message as response

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
@YauheniyaH , "Hello world" example should return "Hello world" phrase on any message

**Comment by YauheniyaH** [comment]
verified on staging successfully
related issue #2737
