### ISSUE TITLE
Application settings opened from chat header on laptop has mobile view if recently used models don't have long description 

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#257]
The issue was reproduced on staging and uat servers on laptop.
1. Create 4-5 conversation based on different models/applications which do not have long description
2. Create a chat based on an application
3. Open the settings from chat header -> setting view is the same as for mobiles -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/f0b988e8-1383-4c61-b276-2ddf389eaa1f)

**Expected result:** laptop setting view should be shown

**Comment by IlyaBondar** [comment]
@VolhaBazhkova ,
it's not reproducible

**Comment by VolhaBazhkova** [comment]
Agree. I wasn't able to reproduce it on UAT, thought it's easily reproduced on Sales env (0.4.2 version)
