### ISSUE TITLE
[Code app] Need to refactor code editor from internal to redux state

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#2573]
### EPAM AI DIAL chat version

0.19.0

### What happened?

Now we have all code editor state inside CodeEditor component what is inconvenient
Need to move actions to epics and component state to codeEditor slice

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
