### ISSUE TITLE
[Code Apps] Add download button to the logs window

### ISSUE THREAD

**Issue by Derikyan** [epam/ai-dial-chat#2581]
### Description

<img width="809" alt="Снимок экрана 2024-11-11 в 08 26 38" src="https://github.com/user-attachments/assets/104dd005-5513-4df2-9bed-9a75aa36dc60">

[https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=13440-65237&t=ygu6gjYhpPOxww1u-1](url)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully

**Comment by sr-remsha** [comment]
Added to the [user guide](https://docs.dialx.ai/tutorials/user-guide#to-access-code-app-logs)
