### ISSUE TITLE
[Regression]: Bold font for "No results found" text for chats, prompts, select folder, manage attachments

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2589]
### EPAM AI DIAL chat version

0.21.0

### How to reproduce

Steps:
1. input search phrase which does not fit any content
2. check empty search results and message

### Actual result

![Screenshot 2024-11-12 at 12 25 51](https://github.com/user-attachments/assets/605ffa44-b4a8-42c8-921b-b16baac120d4)

In select folders for publication request Organization section still visible

https://github.com/user-attachments/assets/0cd98667-5cbc-4b6f-8826-7e139a4d8939

In Select folder for Code app source files All files section is visible 

https://github.com/user-attachments/assets/6a4af13f-97c1-48c6-b040-13f24e8be232

### Expected result

Message "No results found" should not be in bold font for chat area

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
1) DIAL Marketplace has the phrase in bold
![image](https://github.com/user-attachments/assets/203202fc-2bc2-4aa4-beab-123d96158762)

2) other places not in bold
![image](https://github.com/user-attachments/assets/e817ca4f-b394-4bca-946b-a9267b9e31dd)
