### ISSUE TITLE
[Tech Debt] refactoring `getInitActions`(settings.epic.ts)

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2598]
### EPAM AI DIAL chat version

0.20.0

### What happened?

add flag for each reducer and init only first time

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. 
Waiting for UAT to test performance optimization.
Reported #2642
