### ISSUE TITLE
Update themes to use semantic colors and being able to provide multiple themes

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#262]
### Description
Need to use new colors:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/273403d7-9d25-49e5-ade8-e91231a0e2db)
https://www.figma.com/proto/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?page-id=0%3A1&type=design&node-id=2337-7309&viewport=-11368%2C-16005%2C0.8&t=4izqcQXde0DcWDzD-1&scaling=min-zoom&starting-point-node-id=2%3A14

#### Related
- Issue #255 
- Issue #245

**Comment by mikitabut** [comment]
Closed because wil be covered in #245
