### ISSUE TITLE
Unpublish request for chat contain file for version if file was unpublished earlier with another version of chat

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2632]
### EPAM AI DIAL chat version

0.21.0

### How to reproduce

Steps:

1. create chat with file
2. create publication request for chat with file v0.0.1
3. by admin approve request
4. create publication request for chat with file v0.0.2
5. by admin approve request 
6. create unpublish request for chat with file v0.0.2 -> chat and file were unpublished, file was removed from Manage attachments from Organization
7. create unpublish request for chat v0.0.1 -> request form contain file section -> bug
8. 

### Actual result

creation unpublish request failed with error

### Expected result

if file from chat was unpublished earlier than next unpublish requests for other versions should not contain file in request

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by Gimir** [comment]
Temporarily remove files from unpublish requests untill nested folder concept is ready.

**Comment by YauheniyaH** [comment]
Ticket can not be tested until concept of unpublish files will be defined
