### ISSUE TITLE
Move "New conversation"(Chat) and "Back to Chat"(Marketplace) buttons in header on all devices

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2641]
### Description

Show "New conversation"(Chat) and "Back to Chat"(Marketplace) buttons in header on all devices
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=13828-49107&m=dev 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by DaryaKarniyenka** [comment]
New design 
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=13703-80222&t=Jo6pSwANixchx3Vj-1

![image](https://github.com/user-attachments/assets/8f15cee9-a860-418f-a40e-a3dc90accded)

![image](https://github.com/user-attachments/assets/2176f914-694e-4708-9b85-8d0aacd1b98b)

**Comment by YauheniyaH** [comment]
verified on staging successfully

**Comment by sr-remsha** [comment]
Documented:
- [Create conversation](https://docs.epam-rail.com/user-guide#create)
- [Marketplace](https://docs.epam-rail.com/user-guide#create)
