### ISSUE TITLE
[Marketplace+ Search]: Not latest version of model can not be found in My workspace

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2648]
### EPAM AI DIAL chat version

0.21.0

### How to reproduce

Steps:
1. Open DIAL Marketplace
2. find card for model GPT-4 turbo
3. click on card
4. select in version dropdown not latest version (e.g. 1160-Preview)
5. click on bookmark icon
6. open My workspace page and find GPT-4 turbo card
7. click on card -> version 1160-Preview is displayed -> ok
8. close application view modal
9. input in search textbox GPT -> GPT-4 1160-Preview is not found in My workspace, it is displayed in Suggested -> bug

### Actual result

If add not latest version of the model to My workspace, it can not be found by search
Issue is reproducible for applications (custom, code) also

Note: Latest version of model can be found by search in My workspace

https://github.com/user-attachments/assets/dfbe8024-20ff-4ab0-98c3-14ec6916dc3b

### Expected result

user should be able to find model in My workspace if any version was added

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified by Yauheniya on staging successfully
