### ISSUE TITLE
Automigrate conversations from local store (prev version) into stateful api (new version)

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#265]

**Comment by DaryaKarniyenka** [comment]
![1920_migration](https://github.com/epam/ai-dial-chat/assets/151838896/1a167b8a-b8ce-4bab-8b60-1c7ce0d89866)

For mobile we should use smaller font sizes
![360_migration](https://github.com/epam/ai-dial-chat/assets/151838896/c534d50c-69c5-4eda-80cf-0bcaf786b119)

Animated prototype (press "R" to start animation)
https://www.figma.com/proto/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?page-id=0%3A1&type=design&node-id=5846-11399&viewport=-2337%2C-3900%2C0.14&t=ahsLozRNTyEWf5FE-1&scaling=min-zoom&starting-point-node-id=5846%3A11399&mode=design

**Comment by VolhaBazhkova** [comment]
Verified on staging (Chrome, FF, Opera, Edge browsers), iPhone, iPad. See also #682
