### ISSUE TITLE
[Redesign] don't show new empty conversation into conversation panel

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2651]
### Description

- don't show new empty conversation into conversation panel, 
- disable "New conversation" until new empty conversation is selected [VB] not valid. Decided that + button resets setting on new conversation screen
- remove new empty conversation if select existed not empty conversation

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully

**Comment by sr-remsha** [comment]
Added to [user guide](https://docs.dialx.ai/tutorials/user-guide#create)
