### ISSUE TITLE
Create New conversation after delete chat which had the focus 

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2654]
### Description

Steps:
1. Click on conversation in left panel -> conversation is selected, its details displayed on the central screen
2. Hover over conversation, click on 3 dots 
3. click on  Delete option in context menu

Actual result: focus is set on:
1.  the latest own conversation 
2. if not own user's chats exist, then focus set  to the latest chat from Organization section
3. if not own user's chats and no Organization section, then focus set to latest from Shared with me section
4. if nothing from above applicable, New conversation is created

Expected result:
if delete conversation , when focus set on this conversation, then New conversation should be created

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. See also #2681
