### ISSUE TITLE
Move `Layout` from `_app.tsx` and make HOC for specific pages instead

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2666]
### EPAM AI DIAL chat version

0.20.0

### What happened?

Move `Layout` from `_app.tsx` and make HOC for specific pages instead:
`Chat`(index.tsx) and `Marketplace`(marketplace/index.tsx) should be wrapped by `Layout.tsx`, but not auth-pages

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified by @valerydluski
