### ISSUE TITLE
[Marketplace] on DIAL marketplace incorrect version of custom app is shown on the card. The first created is shown, thought the second (the newest) is available

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2670]
### EPAM AI DIAL chat version

0.21.0

### What happened?

1. User1 creates and publishes any custom_app version 0.0.1
2. User1 updates and publishes the custom_app version 0.0.2
![image](https://github.com/user-attachments/assets/24f81fa0-6065-4e42-a84b-78cb687031b6)

3. Open DIAL Marketplace by User2 and note that the app is available, but the version on the card is 0.0.1 -> **bug**
![image](https://github.com/user-attachments/assets/130f0ab0-9f5c-422b-9e0b-e6063b9f3c72)

**Expected:** 0.0.2 version
Note: the version with higher number will be shown not depending on the time if publication

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
