### ISSUE TITLE
Blinking "Conversation not found" label after each click on "New conversation"

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2676]
### EPAM AI DIAL chat version

0.20.0-rc

### What happened?

Blinking "Conversation not found" label after each click on "New conversation"

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully.
Two cases:
1) No blinking label when refresh DIAL on chat screen and on Marketplace screen
2) No blinking label when click on + button
