### ISSUE TITLE
Background for items in context menu opened from chat header should be blue (now green)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2678]
### EPAM AI DIAL chat version

0.21.0

### What happened?

**Actual:**
![image](https://github.com/user-attachments/assets/5ba1716a-3ee1-44f4-a298-089feb0c8d4b)
![image](https://github.com/user-attachments/assets/db041748-f269-4414-81d9-26a87cbe6dc6)

**Expected:** on the central part items are highlighted using blue color
Example: 
![image](https://github.com/user-attachments/assets/d8251abf-f531-4397-b00d-3ebbf3fb0dd0)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
