### ISSUE TITLE
New conversation not created when delete focused chat from Shared with me section. 

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2681]
### EPAM AI DIAL chat version

0.21.0

### How to reproduce

Preconditions:
there is at least one chat in Shared with me section
there is at least one chat in Organization

Steps:
1. click on chat's from Stared with me in side panel
2. in context menu select delete option and confirm

### Actual result

Focus moved to chat from Organization section
New conversation was not created

### Expected result

New conversation start screen should be displayed

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The fix was verified on staging env successfully (tested with deleting of shared folder, shared chat)
