### ISSUE TITLE
'Talk to' selected model has different state for two local conversations

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#2684]
### EPAM AI DIAL chat version

0.20

### What happened?

1. Create a new conversation
2. Go to the marketplace and choose a different model
3. Return to the Chat and refresh the page.
4. Previously selected model is selected -> ok
5. Create a new chat and see that another model is selected -> bug

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging 
related issue #2822
