### ISSUE TITLE
Change icons for replay and playback

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2698]
### EPAM AI DIAL chat version

0.22.0

### What happened?

New icons 
![image](https://github.com/user-attachments/assets/142d0244-6b5e-4161-b13e-017c24d984fb)
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=11988-26222&t=0ee2bjDMk7uDiVcM-1

Expected result:
![image](https://github.com/user-attachments/assets/c56acf4b-f068-4d38-ad4b-9ecfe01724f1)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
