### ISSUE TITLE
"New conversation" (Chat) loading spinner have incorrect size for mobile

### ISSUE THREAD

**Issue by Derikyan** [epam/ai-dial-chat#2701]
### EPAM AI DIAL chat version

0.22.0

### What happened?

"New conversation" button loading spinner have incorrect size for mobile

Actual result
![image (1)](https://github.com/user-attachments/assets/1e18e12a-f412-4d0f-bb71-b85f74dae3d5)

Expected result
<img width="180" alt="Снимок экрана 2024-11-29 в 15 06 06" src="https://github.com/user-attachments/assets/5cab7f90-72b4-48b1-86fe-52d0a2cc0a44">

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
