### ISSUE TITLE
[Marketplace] 'Latest' is not shown as first version on the Card view and in drop down versions list

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2708]
### EPAM AI DIAL chat version

0.20.0

### What happened?

![image](https://github.com/user-attachments/assets/75c0bbb6-add9-4235-9d1e-4d334c4621e1)
Another example: Gemini 1.5 Flash, Gemini 1.5 Pro

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
+ GPT-4 Turbo

**Comment by YauheniyaH** [comment]
verified on staging successfully
