### ISSUE TITLE
In DIAL XL users can not use application from DIAL Marketplace

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2724]
### EPAM AI DIAL chat version

0.22.0

### How to reproduce

Steps:

1. open [DIAL XL]
2. open chat in overlay
3. click DIAL Marketplace
4. click qg 2.0 card
5. click Use application

### Actual result

Actual result: "User application" button is not clickable
also Bookmark button and x-button are not clickable, but looks like enabled

### Expected result

DIAL XL users should be able to select model/application though DIAL Marketplace

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
error place:
![image](https://github.com/user-attachments/assets/a6821e63-ac93-4ec3-8ae0-a77c8c1eef05)

**Comment by YauheniyaH** [comment]
verified on staging successfully
