### ISSUE TITLE
Rename item should be added to the chat context menu in chat header

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2743]
### EPAM AI DIAL chat version

0.22.0

### What happened?

![image](https://github.com/user-attachments/assets/933f6b3b-b93d-4a95-ac83-89db1debc390)
Expected: we agreed to add Rename item and implement renaming is a modal window

![image](https://github.com/user-attachments/assets/8c95809e-19fd-465d-bf7f-880f49dac7e9)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=14390-50603&t=AStIpsj1R3KaYC6q-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. Reported #2888
Agreed to re-design chat renaming only. Folder renaming stay the same.

**Comment by sr-remsha** [comment]
Described [here](https://docs.epam-rail.com/user-guide#conversation-settings)
