### ISSUE TITLE
[Code app]: Example Simple RAG respond with error in conversations

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2750]
### EPAM AI DIAL chat version

0.22.0

### How to reproduce

1. Open Add code app form
2. select empty folder for field "Select folder with source files" ( create new folder and select it)
3. click on Add example "Simple RAG"
4. input chat completion url /openai/deployments/simple-rag/chat/completions
5. input env variable DIAL_URL 
6. input Attachment types = application/pdf
7. Max attachment type =1
8  save app
9. find code app's card in My workspace and  deploy code app
10. click on code app's card and click on 'Use application" button
11. input any pdf file with question for new chat with applied code app

### Actual result

Error in response "Sorry, we were unable to process your request at this time due to a server error. Please try again later. Thank you for your patience and understanding."
log from code app
[application_logs_12-4.txt](https://github.com/user-attachments/files/18021641/application_logs_12-4.txt)

### Expected result

Response message should be generated 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
[application_logs_12-13 (2).txt](https://github.com/user-attachments/files/18127529/application_logs_12-13.2.txt)
latest logs

**Comment by IlyaBondar** [comment]
@YauheniyaH , @VolhaBazhkova , pay attention that:
- env variable `SSL_CERT_FILE` will be passed on controller level (@artsiomkorzun , for resolving `SSL: CERTIFICATE_VERIFY_FAILED`)
- env variable `DIAL_URL` must be set manually

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. Now code app with Simple Rag example works fine
