### ISSUE TITLE
[Tech Debt] inverstigate the issues with sudden reloading Dial chat application (often in development mode)

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2753]
### EPAM AI DIAL chat version

0.21.0

### What happened?

inverstigate the issues with sudden reloading Dial chat application (often in development mode):
- investigate console errors
- investigate reloading reasons

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
![image](https://github.com/user-attachments/assets/fa00dcb2-4ca0-47ef-bc60-d9558255c530)

**Comment by IlyaBondar** [comment]
![image](https://github.com/user-attachments/assets/9ec159d3-4568-45c7-96bd-45db432e9293)

**Comment by IlyaBondar** [comment]
![image](https://github.com/user-attachments/assets/fa0aa7aa-62b5-4b72-99cd-d8072edd571c)

**Comment by Gimir** [comment]
![Image](https://github.com/user-attachments/assets/66ae1203-d929-47c1-bfe0-31302503fdaa)


After 10 mins doing nothing in the chat  I sent 'hello' message in the chat and this error dropped. No refresh though

**Comment by VolhaBazhkova** [comment]
The Auto and Dev team confirmed that the fix helped.
