### ISSUE TITLE
Publish: Need to add search filter icon/panel for sharing and publishing

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#276]
### Description
we want to filter what was shared or published from search field
![image](https://github.com/epam/ai-dial-chat/assets/20163971/37089534-2e4e-4575-9800-82c5bbe0ecfc)
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3562%3A8688&mode=design&t=gN1oe5xMfd3Ka8TX-1

**Comment by VolhaBazhkova** [comment]
Verified "Shared with me" filters chat/prompts successfully.
Please note that shared folder and filter will be checked in #291 Also publishing is not ready now and will be verified in future tickets.
