### ISSUE TITLE
Need to introduce some feature flags

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#2771]
### EPAM AI DIAL chat version

0.22.0

### What happened?

1) new flag: EmptyChatAgent - it should show the 'Change agent' link on new conversation like it's done for Conversation settings link and flag: EmptyChatSettings (#2728)
Please also enable it by default in our code, like it's done for EmptyChatSettings
2) new flag: TopMenu - it should show three dots (chat menu)
Please also enable it by default in our code, like it's done for other chat header settings
3) new flag: DisallowChangeAgent - it should not allow Change agent pop-up to appear. Typically the setting makes sense if TopChatInfo flag is enabled (it shows the chat name and model icon) + TopSettings flag (it shows the chat header)
 if there is **no** the flag: agent icon exists in chat header; tooltip on hover is shown, if to click on the agent icon the pop-up appears
 if there is the flag: agent icon exists in chat header; tooltip on hover is shown, if to click on the agent icon **no** pop-up appears
4) please be sure to update the documentation with new flags (https://github.com/epam/ai-dial-chat/blob/development/libs/shared/src/types/features.ts)

UPD:
![image](https://github.com/user-attachments/assets/a05e130b-33f6-4523-b8c2-660092fd1f3d)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified locally in overlay-sandbox successfully.

**Comment by sr-remsha** [comment]
@Derikyan please complete the example with all necessary flags
https://github.com/epam/ai-dial-chat/blob/development/libs/shared/src/types/features.ts

**Comment by Derikyan** [comment]
> @Derikyan please complete the example with all necessary flags https://github.com/epam/ai-dial-chat/blob/development/libs/shared/src/types/features.ts

As a result of the discussion, the flags that were specified in the task changed to:
DisallowChangeAgent,
HideEmptyChatChangeAgent,
HideTopContextMenu
