### ISSUE TITLE
Use/fix `NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT` 

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2775]
### EPAM AI DIAL chat version

0.21.0

### What happened?

Use/fix `NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT` 

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
