### ISSUE TITLE
Inconsistent Folder Creation Behavior in "Change Path" Modal of Prompt/Conversation Publishing

### ISSUE THREAD

**Issue by nartovm** [epam/ai-dial-chat#2803]
### EPAM AI DIAL chat version

Version 0.22.0-rc

### What happened?

**Description:**

There are several issues related to creating and deleting folders within the "Change path" modal of the prompt publishing feature.

**Prerequisites:**
1. Create a new prompt.
2. Press the "Publish" button in the prompt's dropdown menu.
3. In the "Publish Prompt" modal, press the "Change" button to open the "Change path" modal.

**Case 1: Incorrect Rename Mode after Folder Deletion**

**Steps to Reproduce:**
1. Press the "Create new folder" button.
2. Rename the folder to "testfolder 1".
3. Create a nested folder named "testfolder 2" inside "testfolder 1".
4. Delete the nested folder "testfolder 2".
5. Press the "Create new folder" button.

**Expected Result:**
A new folder is created in rename mode, allowing the user to change its default name ("New folder 1").

**Actual Result:**
A new folder named "New folder 1" is created, but *not* in rename mode.

**Case 2: Folder Structure Corruption after Nested Folder Deletion**

**Steps to Reproduce:**
1. Press the "Create new folder" button.
2. Rename it to "testfolder 1".
3. Create a nested folder "testfolder 2" inside "testfolder 1".
4. Create a nested folder "testfolder 3" inside "testfolder 2".
5. Create a nested folder "testfolder 4" inside "testfolder 3".
6. Delete the nested folder "testfolder 4".
7. Press the "Create new folder" button.

**Expected Result:**
A new folder is created in rename mode.

**Actual Result:**
"New folder 1" is created with "testfolder 2" nested inside. The original "testfolder 1" disappears completely.

**Edge Case: Unresponsive "Create New Folder" Button**

**Steps to Reproduce:**
1. Follow the steps for either Case 1 or Case 2.
2. Sometimes, the first click on the "Create new folder" button produces no visible effect.
3. A second click then creates "New folder 2" instead of "New folder 1".  "New folder 1" is not present in the DOM, but the application behaves as if it exists.

https://github.com/user-attachments/assets/e9cf56dd-1ec0-4070-b36a-6de714884518

**Reproducibility:**  Cases 1 and 2: Almost always.  Edge case: Intermittent (approximately 10% of the time).

**Environment:**  Chrome Version 131.0.6778.109 (Official Build) (64-bit), Windows 11.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by nartovm** [comment]
**Update:**

**Additional Edge Case:** Unresponsive "Create New Folder" Button After Renaming

**Steps to Reproduce:**
1. Follow the prerequisites to open the "Change path" modal.
2. Create a new folder.
3. Rename the folder to any valid name.
4. Press the "Create new folder" button.

**Actual Result:**
Sometimes, the first click on the "Create new folder" button has no visible effect.  A second click then creates "New folder 2" instead of "New folder 1".  Attempting to rename this newly created folder to "New folder 1" automatically saves it as "New folder 2".

**Comment by YauheniyaH** [comment]
verified on staging successfully
