### ISSUE TITLE
Move version closer to name in conversation header

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2815]
### EPAM AI DIAL chat version

0.22.0

### What happened?

1) Move version closer to name
2) Move Stop playback to the end

General elements order in the header 
![image](https://github.com/user-attachments/assets/12f7474b-7350-4c2b-ad14-dd59835e6671)

For each case
![image](https://github.com/user-attachments/assets/f06776a3-81a1-473e-9ae8-8380b26db621)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=10464-16353&t=ER0inp7FtyIZG9vO-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
verified on staging successfully
