### ISSUE TITLE
[Select agent form]: Dots-pagination for large number of pages

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2825]
### EPAM AI DIAL chat version

0.22.0

### What happened?

![image](https://github.com/user-attachments/assets/f040285d-9cdc-49e2-8de5-1d23b5ea086a)
https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=10464-16326&t=hp0xCnsBRZ9FTxC4-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
