### ISSUE TITLE
[Select agent form]: Add padding to text in cards

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2833]
### EPAM AI DIAL chat version

0.22.0

### How to reproduce

Open change agent window 

### Actual result

![image](https://github.com/user-attachments/assets/33d27374-c088-4594-9f7a-98d96ebda85a)

### Expected result

![image](https://github.com/user-attachments/assets/2e6be13c-4a04-401f-9a64-f06dafffd1f8)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=13796-64400&t=dxHRkppWcaQAMvcm-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
