### ISSUE TITLE
Fix issues for bash and sh code blocks in markdown

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2854]
### EPAM AI DIAL chat version

0.22.0

### What happened?

Issues:
- no syntax highlighting for `sh` script
- `.txt` extension in suggested download name for bash or sh scripts 
- add date in generated name for download

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env, Reported #2867 #2868
