### ISSUE TITLE
The settings modal panel has a delay before opening

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#2863]
### EPAM AI DIAL chat version

0.22

### What happened?

The settings modal panel has a delay before opening
It's necessary to make the tokenizer not block the thread

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Example on staging env
![image](https://github.com/user-attachments/assets/83c666ec-84d8-4d97-9612-9776386388da)

**Comment by VolhaBazhkova** [comment]
Verified on staging env that there is no error in console, but for o1-mini it still takes ~200 ms on opening conversation settings.  Seems that it's reproduced for all GPT models and not reproduced for others? like Stable, DALLE, etc

**Comment by VolhaBazhkova** [comment]
Verified on staging env, now it takes 76-91 ms to open the modal settings for GPT models
