### ISSUE TITLE
Need to add share option for Folder context menu for conversations and prompts

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#291]
Pinned:
- add share option for Folder context menu for conversations and prompts
- displaying share icon only for shared item

Shared with me:
- displaying shared items on root level
- displaying shared folders and items inside

**Comment by VolhaBazhkova** [comment]
The ticket was verified on staging. Updated test cases for Share folder chat and folder prompt. Still need to create test cases for Shared with me functionality.
