### ISSUE TITLE
Need to add numeration for folders and fix for prompts

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#302]
### Description

numeration should be applied only for default names
#### Changes

- add numeration for folders
- fix numeration for prompts
- add numeartion for conversations

![image](https://github.com/epam/ai-dial-chat/assets/20163971/4538caae-8b02-41cb-a864-ef0a02f88a7b)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/0f87ec1a-a184-4227-adfb-41ec4d7f55c6)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/359e7660-c29a-4652-bb3e-ce84ed941646)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. 
Now chats/prompt folders and new conversations are also numerated automatically. Renamed/deleted items are not counted into numeration. Dial increments New items only according to the found biggest number: for example, if you rename any prompt to Prompt 100, newly created prompt name will be Prompt 101, even though there are missed Prompt 99, 98..etc.
