### ISSUE TITLE
EPIC: Publish conversations, prompts and collections

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#313]
### Description

- [x] Issue #276 
- [x] Issue #163 
- [x] Issue #317 
- [x] Issue #330 
- [x] Issue #331
- [x] Issue #433 
- [x] Issue #1269 
- [x] Issue #318 
- [x] Issue #236
- [x] Issue #164 
- [ ] Issue #320 
- [ ] Enhancement #496
- [ ] Bug #605
- [x] Bug #1421
- [x] Bug #1422
- [x] Bug #1423
- [x] Bug #1424
- [x] Bug #1425
- [x] Bug #1428
- [x] Bug #1429
- [x] Bug #1430 
- [ ] Issue #1434
- [x] Issue #1439
- [ ] Issue #1440
- [x] Issue #1441
- [x] Issue #1442 
- [x] Bug #1444 
- [x] Bug #1446
- [x] Bug #1447
- [x] Bug #1448
- [x] Bug #1450
- [x] Issue #1455 
- [ ] Issue #1456 
- [x] Feature #1457
- [x] Bug #1460
- [x] Bug #1463
- [x] Bug #1464
- [x] Bug #1466
- [x] Bug #1469
- [x] Bug #1470
- [x] Bug #1473
- [x] Bug #1478
- [x] Bug #1481
- [x] Bug #1482
- [x] Bug #1483
- [x] Bug #1494
- [x] Enhancement #1495
- [x] Bug #1501
- [x] Bug #1502
- [x] Bug #1503
- [x] Bug #1504
- [x] Bug #1508
- [x] Bug #1510
- [x] Bug #1512
- [ ] Bug #1514 
- [x] Bug #1515
- [ ] Enhancement #1522
- [x] Bug #1529
- [x] Bug #1532
- [x] Bug #1534
- [x] Bug #1535
- [ ] Enhancement #1537
- [x] Bug #1544
- [x] Bug #1556
- [x] Bug #1558
- [x] Bug #1564 
- [x] Bug #1568
- [x] Bug #1569
- [x] Enhancement #1579
- [x]  Bug #1580
- [x] Bug #1583
- [x] Enhancement #1589
- [x] Bug #1591
- [x] Bug #1597 
- [x] Bug #1599
- [x] Bug #1600 
- [x] Bug #1601
- [ ] Bug #1608
- [x] Bug #1609
- [x] Bug #1610
- [x] Bug #1611
- [ ] Bug #1613
- [x] Bug #1632 
- [x] Bug #1612
- [ ] bug #1613
- [x] Bug #1618
- [x] Bug #1620
- [x] Enhancement #1628
- [x] Bug #1631
- [ ] Bug #1634
- [ ] Bug #1635
- [x] Enhancement #1640 
- [x] Bug #1661
- [x] Bug #1663
- [x] bug #1667
- [x] Bug #1668
- [x] Enhancement #1676
- [ ] Enhancement #1683
- [x] Feature #1686
- [x] Bug #1695
- [x] Bug #1696
- [x] Bug #1700 
- [x] Bug #1701
- [x] Bug #1707
- [ ] Bug #1713
- [x] Bug #1714
- [ ] Bug #1715
- [x] Bug #1729
- [ ] Bug #1730
- [ ] Bug #1734
- [x] Bug #1736
- [ ] Bug #1744
- [x] Bug #1745
- [x] Enhancement #1746
- [x] Bug #1748
- [ ] Bug #1757 
- [ ] Bug #1758
- [x] Bug #1762
- [x] Bug #1770
- [x] Bug #1771
- [ ] Bug #1772
- [ ] Bug #1775
- [ ] Enhancement #1776
- [x] Bug  #1780
- [ ] Bug #1781
- [x] Enhancement #1801 
- [x] Enhancement #1805
- [x] Enhancement #1812
- [x] Bug #1842 
- [x] Bug #1844 
- [x] Bug #1847 
- [x] Bug #1853 
- [ ] Bug #1854 
- [x] Bug #1856 
- [x] Bug #1860 
- [ ] Bug #1861
- [x] Bug #1867
- [x] Bug #1876
- [x] Bug #1913 
- [x] Bug #1915 
- [ ] Enhancement #1926 
- [x] Bug #1944 
- [ ] Bug #1969
- [ ] Bug #1993 
- [x] Bug #2004
- [x] Tech debt #2007
- [ ] Enhancement #2011
- [x] Bug #2022 
- [x] Bug #2025
- [x] Bug #2026 
- [ ] Enhancement #2030
- [x] Bug #2048 
- [ ] Bug #2050
- [ ] Bug #2064 
- [ ] Bug #2072 
- [x] Bug #2088
- [ ] Enhancement #2123
- [ ]Enhancement #2124
- [x] Bug #2126 
- [ ] Bug #2134 
- [ ] Enhancement #2143
- [ ] Enhancement #2145 
- [ ] Bug #2148
- [ ] Enhancement #2150
- [ ] Enhancement #2154 
- [ ] Bug #2158 
- [ ] Bug #2159 
- [ ] Enhancement #2176 
- [ ] Enhancement #2178 
- [ ] Enhancement #2179
- [x] Bug #2183
- [x] Bug #2200 
- [x] Bug #2201
- [x] Bug #2207
- [x] Bug #2208
- [ ] Enhancement #2254

**Comment by sr-remsha** [comment]
Added instructions for [conversations](https://docs.epam-rail.com/user-guide#publish) and [prompts](https://docs.epam-rail.com/user-guide#publish-1) publications. Also, the [configuration flow](https://docs.epam-rail.com/user-guide#publications) and the [section for admins](https://docs.epam-rail.com/user-guide#administrators).

**Comment by sr-remsha** [comment]
Added [publications API reference](https://epam-rail.com/dial_api#tag/Publications)
