### ISSUE TITLE
Publish: Need to implement publish/update request wizard for conversations and for prompts

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#317]
### Description

User clicks on "Publish" option for folder/conversation/prompt if it hasn't been published or "Update" option for already published item
User sees Publication request wizard.
Some parts of wizard will be implemented separately. See `Related` section.
User should be able set custom name of publication. Current name of item prepopulated in `Name` field and is in header.
When user change name header stays the same.
`Version` field is required and value must be unique (validation) from all versions of current collection

#### Related:
- Issue #330 
- Issue #331
- Issue #433 

#### Design
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3977-10625&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/6a7fb97d-f43a-4021-a1ec-71b7ee923e42)
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3807-8917&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/6e129c14-43e4-4a85-8bce-9319c647613f)

**Comment by VolhaBazhkova** [comment]
Closing the ticket now to clear current "milestone board". The feature will be verified after integration with Publish API. Please see also EPIC #313
