### ISSUE TITLE
Publish: Need to implement Unpublish dialog

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#318]
### Descriprion
User clicks on "Unpublish" option in context menu of published folder/conversation/prompt in his/her items.
User sees "Unpublish" modal with collection and items inside.
Every checkboxes are checked by default. User can choose what should be unpublished.

User can click on "Unpublish" option in context menu of folder/conversation/prompt inside `Organization` section.
In this case versions of this item will be cheched by default.

#### Mockups
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=4009-11177&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/be01bcdb-80ea-43b4-b3fc-48d98637dad8)

**Comment by YauheniyaH** [comment]
Verified on STG
Related issues linked to EPIC #313 

Note: ticket verified taking into account that selector of content and versioning is not implemented yet
