### ISSUE TITLE
Publish: Need to implement versioning for publishing

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#321]
### Description
- how to combine publishing from different users
- how to display versions for collections
- how to display versions for chats/promts inside of collections

Let's imagine that we have following versions:

- **v1** (user1): folder "folder1" with "prompt1" (user1, initial publish)
- **v2** (user2): folder "folder1" with  "prompt1" and "prompt2" (user2 added "prompt2" into folder)
- **v3** (user1): folder "folder1" with  "prompt3" and "prompt2" (user1 removed "prompt1", added "prompt3")
- **v4** (user1): folder "folder1" with "prompt2" and folder "folder1/folder2" with  "prompt3"  (user1 moved "prompt3" from "folder1" to "folder1/folder2")

then

- can users manage only their chats/proms from “pinned”?
- how to show/switch between versions of a collections, where in version **v4** there is one additional folder and two prompts, in **v1** there is one prompt?
- how to show/switch between versions of conversations/prompts? In this source, "prompt2" does not have version **v1**
- how to display movement in version **v4**? In theory, we are showing version **v4** from the latest structure

**Comment by sr-remsha** [comment]
Added basic principles of versioning in user guide:
* [Conversations](https://docs.epam-rail.com/user-guide#publish)
* [Prompts](https://docs.epam-rail.com/user-guide#publish-1)

**Comment by YauheniyaH** [comment]
verified on staging, related issues created
