### ISSUE TITLE
Button "Save and Submit" is unclickable from time to time

### ISSUE THREAD

**Issue by evgeny-danilov** [epam/ai-dial-chat#33]
When the button "Regenerate response" is on the same vertical line with "Save & Submit", the "Save & Submit"  button itself becomes unclickable. It happens due to overlapped css blocks, and I believe can be fixed very fast.

<img width="778" alt="dial-screen" src="https://github.com/epam/ai-dial-chat/assets/12776494/fdf73d24-ac13-4f8a-90ca-b40fdf8eb5a9">

**Comment by mikitabut** [comment]
Hello @evgeny-danilov 
Thank you for submitting the bug. We are starting to work on it and we will provide some updates right after the fix will be merged in the release branch.

**Comment by mikitabut** [comment]
Hello @evgeny-danilov 
The bug has been fixed and is now available in the release branch under tag 0.1.9 and in development branch

Thank you!
