### ISSUE TITLE
Publish: Need to implement Change Path dialog

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#330]
### Description
we want to have opportunity to select path for your publication.
Your folders marked by hihglight and you can rename, delete folder or add new folder.
Also we can add folder on root level.
User can choose any folder for publishing

https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3521-9535&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/9d7bef6c-6060-43fa-aea1-5711dbc89a26)

**Comment by VolhaBazhkova** [comment]
Closing the ticket now to clear current "milestone board". The feature will be verified after integration with Publish API. Please see also EPIC #313
