### ISSUE TITLE
Publish: Need to implement file view for publishing request

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#331]
### Description

User should be able to see all files in published collection/conversation/prompt with full paths
User can rename some file or download it

#### Mockups
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3807-8997&mode=dev
![image](https://github.com/epam/ai-dial-chat/assets/20163971/d2229489-bfd0-4b38-b0b6-4522bae4743b)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/353c1c6f-6c88-49d5-b271-c545e7b99fb0)

**Comment by VolhaBazhkova** [comment]
Closing the ticket now to clear current "milestone board". The feature will be verified after integration with Publish API. Please see also EPIC #313
