### ISSUE TITLE
Sidebars height is not changed when window height have been changed.

### ISSUE THREAD

**Issue by denys-kolomiitsev** [epam/ai-dial-chat#336]
This is regression bug. 
The height of the sidebar should be calculated from the hight of the parrent element.

Steps to reproduce:

1. make a browser window height smaller then your screen height,
2. resize chatbar width,
3. switch browser in a full screen mode. Chatbar height is not equal an available screen height -> **bug**. 

![image](https://github.com/epam/ai-dial-chat/assets/143205282/31457dd9-b57d-46e3-9907-721b07d01676)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
