### ISSUE TITLE
Error in console (Uncaught (in promise) Chat Overlay destroyed) if to open landing page

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#352]
1. Open console
2. Open our landing page (Please ask Devops or QA to provide actual landing link)
3. Check console -> error below appears -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/b86fd825-6089-4696-ac5a-bc95d0b71129)

Note: Overlay works fine

**Expected:** no error in console

**Comment by denys-kolomiitsev** [comment]
This issue caused by implementation of Overlay in the landing page. 
Since Overlay will be removed from the landing page, this issue is not actual anymore.
