### ISSUE TITLE
Need to show error message about incorrect symbols during renaming folder

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#375]
At this moment we don't allow to type incorrect symbols, but it would be nice to show error message and not allow to save such folder name
![image](https://github.com/epam/ai-dial-chat/assets/20163971/d246384a-104f-45b9-a3be-d4fd6c9c09fa)

**Comment by IlyaBondar** [comment]
![Image](https://github.com/epam/ai-dial-chat/assets/20163971/a2accf76-6604-41f5-919d-408b33758658)



![Image](https://github.com/epam/ai-dial-chat/assets/20163971/20a8bb24-fe33-48f6-9968-43976de4d14c)

**Comment by VolhaBazhkova** [comment]
![image](https://github.com/epam/ai-dial-chat/assets/111180458/e6fd7963-3faa-46ce-9f59-6940eea53be0)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
