### ISSUE TITLE
Sharing: limited context menu and readonly view (no message input)

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#389]
### Description
items in "Shared with me" section are readonly and have less context menu options
![image](https://github.com/epam/ai-dial-chat/assets/20163971/7d4563c0-ed3c-4379-88e7-6e6175fe54c0)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/c95937bc-3832-4864-9c74-0bca7719c9f3)

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully
