### ISSUE TITLE
Get rid of lint issues

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#393]
1. Now we have `61 problems (0 errors, 61 warnings) ` in eslint which mostly connected with `Unexpected any. Specify a different type`. We need to refactor such code or suppress the warnings
2. Check for other lint rules which can be added to project to improve DX and prevent potential issues for future. Check Airbnb lint rules to find something

### Related 
Continue to fix in
- Issue: #513

**Comment by denys-kolomiitsev** [comment]
All eslint issues fixed or disabled.

**Related**
disabled errors will be rechecked in 
#513
