### ISSUE TITLE
When having some incorrect mime types provided in list of inputAttachmentTypes you will see `.false`, but incorrect types should be filtered

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#397]
When having 
"inputAttachmentTypes": [
  "image/jpg",
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/gif
]
next supported file extensions displayed `.false, .jpeg, .png, .webp, .gif`
We need to filter invalid mime types(image/jpg not exist)

**Comment by VolhaBazhkova** [comment]
Closing the issue as it's technical dev update. Now there is no specific issues with attached files exist in DIAL, all types are available.
