### ISSUE TITLE
Need to fix console errors

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#407]
### Description
- fix following console errors
  - ![image](https://github.com/epam/ai-dial-chat/assets/20163971/ac95bae6-349b-4ff4-ad2e-14712eb3ffc9)
  - ![image](https://github.com/epam/ai-dial-chat/assets/20163971/058da667-07bd-4cdd-8a33-f2ae64b3c299)
- fix opening file upload twice (locally in dev mode)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. No errors in console if to work with settings; attachment functionality.
