### ISSUE TITLE
Colour and icons issues

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#414]
Need to fix some issue appeared after #255 (https://github.com/epam/ai-dial-chat/issues/255)

1)  Attach files window
![image](https://github.com/epam/ai-dial-chat/assets/111180458/f4ed825c-76bb-43a8-9fe4-f012c206063c)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/a1d04a29-9c16-418e-a31d-24cf655455b7)
2) Upload from device window
![image](https://github.com/epam/ai-dial-chat/assets/111180458/96b8bed3-9e11-4a7f-8cb5-aa276b77bdc6)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/7ac12630-7308-4a77-bc52-c4c6ba20dfee)
3) Settings
![image](https://github.com/epam/ai-dial-chat/assets/111180458/0e8beba6-afde-4f14-9511-e3ab23749c24)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/04ea82ef-e244-4bd3-bed1-3b16146622fa)
4) Model and addon icons
![image](https://github.com/epam/ai-dial-chat/assets/111180458/730504a5-4eb7-41fa-ba43-837135dd799d)

**Comment by DaryaKarniyenka** [comment]
5. Divider and block border colors in chat. It should be stroke/secondary 
![image](https://github.com/epam/ai-dial-chat/assets/151838896/766ef2b5-a0b9-46af-ac5c-1bc316304516)

6. Side panels border color.  It should be stroke/tertiary
![image](https://github.com/epam/ai-dial-chat/assets/151838896/461aa817-4c4d-482c-b005-b15812c8b9aa)

7. Scroll bg should be transparent
![image](https://github.com/epam/ai-dial-chat/assets/151838896/e9ee7abb-20a2-447a-bbf9-2d6aaea55a68)

**Comment by VolhaBazhkova** [comment]
@mikitabut may I address one more issue to this ticket?

![image](https://github.com/epam/ai-dial-chat/assets/111180458/9f83e5ab-3c08-4ca0-ac74-57437b6565a4)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/0bd605f2-7235-4644-8944-32f35aa3cff9)

**Comment by mikitabut** [comment]
Hello @VolhaBazhkova 
I fixed most of the problems but issue `vii` which Darya reported and issue from your comment not fixed. I suggest to create separate tickets for them, because Darya ticket require a lot of changes and it was before my changes, and your ticket need more time to investigate. All other tickets fixed and can be tested

**Comment by VolhaBazhkova** [comment]
Created https://github.com/epam/ai-dial-chat/issues/426

**Comment by VolhaBazhkova** [comment]
Reported #477 and #478

The rest of items were verified on staging successfully.
