### ISSUE TITLE
Attachments are not shown well in edit message mode (mobile view)

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#424]
![image](https://github.com/epam/ai-dial-chat/assets/20163971/8b2a2dff-e160-4840-958d-48e30c0859bc)

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. Now in portrait mode attachments are shown one by one; in landscape no, but user can click on the file name and see the full file name.
![image](https://github.com/epam/ai-dial-chat/assets/111180458/ed4c51f9-d9f4-4a2f-bda7-8feaf4283fe7)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/d88ebf24-7001-4dd1-a4b3-fb957dfc2da7)
