### ISSUE TITLE
When opening overlay when you not logged in you will see error that bucket not found

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#425]
We shouldn't request bucket if user not logged in, because only user has it
Actual:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/f24d7ec4-518e-4e56-9d08-4328145f9cbc)
Expected:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/b3a43ac9-8cb8-4367-81e2-c2f5891d83ae)

**Comment by VolhaBazhkova** [comment]
Please note: reported in core ticket https://github.com/epam/ai-dial-core/issues/122

![image](https://github.com/epam/ai-dial-chat/assets/111180458/7dc26646-36e5-429c-82ee-6fc58021899e)

**Comment by VolhaBazhkova** [comment]
Verified on landing site + staging overlay successfully. Reported issue #512
