### ISSUE TITLE
[MacOS Sonoma 14.1.2/Safari browser] request text area overlaps with response area text when user pastes text into request area.

### ISSUE THREAD

**Issue by IlyaRabtsau** [epam/ai-dial-chat#430]
OS: MacOS Sonoma 14.1.2
Browser: Safari

Steps to reproduce:

1. Generate text to fill working display area.
2. Paste same text into request field.

Issue is not reproducible in Chrome on MacOS/Win, or Safari on iPadOS.
Video: https://epam-my.sharepoint.com/:v:/p/ilya_rabtsau/EVa7YqUPlIhLpWLLyvZfuoQB2MAQC4FIWTixgZwsuzZEcQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=1F0u7p
![image](https://github.com/epam/ai-dial-chat/assets/154673134/fba5eb23-2cbe-46ef-896e-e9f114e85a0e)
![image](https://github.com/epam/ai-dial-chat/assets/154673134/507fe517-831c-45d6-ad46-670899196fb5)

**Comment by VolhaBazhkova** [comment]
The fix was verified successfully on staging server (using desktop Safari browser in MacOS).
