### ISSUE TITLE
Previous conversation is still highlighted after creating Playback, Replay or Duplicate copies

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#431]
#### Actual result:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/b85e117a-3742-4f4a-b17e-af1e93f49ab8)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/163b8619-d1e5-4a79-8e7d-f8ceeea72da6)
#### Expected result:
only new copy should be highlighted

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully (replay, playback). Note that Duplicate feature exists on dev machine only.
