### ISSUE TITLE
Publish: Need to implement filter view for publishing request

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#433]
### Description
Need to implement "Target Audience Filters" section
- User groups with badges
- Contains with badges
- Regex with text

### Filter mode list (TBD):

- contains
- not contains
- equals
- regex

### Tasks:

- [x] Create reusable MultipleComboBox component;
- [x] Create reusable Target Audience Filter component;

#### Design
https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=3736-9951&mode=design&t=sqS1MyvgeYjkhA0C-0
![image](https://github.com/epam/ai-dial-chat/assets/143205282/a0cfda52-b8eb-4050-80d2-4b5e3cf266fa)

**Comment by VolhaBazhkova** [comment]
Closing the ticket now to clear current "milestone board". The feature will be verified after integration with Publish API. Please see also EPIC #313
