### ISSUE TITLE
[PROD] Mixtral-8x7B-Instruct-v0.1 model throws 500 error.

### ISSUE THREAD

**Issue by IlyaRabtsau** [epam/ai-dial-chat#434]
User reported not being able to use Mixtral-8x7B-Instruct-v0.1 model https://gitlab.deltixhub.com/Deltix/openai-apps/aiproducts1ls/-/issues/117, 
Issue is reproducible, model throws 500 error on any request.
 
![image](https://github.com/epam/ai-dial-chat/assets/154673134/e1c91007-ace2-4c1d-ad78-a7ef71272d71)
![image](https://github.com/epam/ai-dial-chat/assets/154673134/80fc0a91-b702-45b9-8aec-a9272dbbf146)

**Comment by VolhaBazhkova** [comment]
The model works on PROD now correctly
