### ISSUE TITLE
Sharing: fix displaying "Shared with me" and "Organization" section items

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#437]
### Description
if collection was shared with some sub folder and items then all subitems aren't displayed in "Shared with me" and "Organization" section
#### Actual result:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/a0d6b08e-f27f-467e-9a12-7d60940abcbb)
#### Expected result:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/384aa5b5-5309-468a-8b2b-98611e5ba54a)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully.
