### ISSUE TITLE
Need to add a space in "Share with Me" and "Organization" sections between names chats and prompts

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#447]
Right now it looks like this:
<img width="255" alt="screenshot as is" src="https://github.com/epam/ai-dial-chat/assets/98586297/37f66c83-7740-4bae-a674-180e2b7b96c5">

Expected:
<img width="248" alt="screenshot as it should be" src="https://github.com/epam/ai-dial-chat/assets/98586297/8c9f67b4-178e-4a43-b2b4-124a2fd5721c">

It works fine for folders.

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully.
