### ISSUE TITLE
Toggle activation area too large for "Full width chat" setting

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#454]
1. Navigate to the "Settings" panel.
2. Attempt to click on the area surrounding the "Full width chat" toggle -> note that the toggle is activated even when the click is outside the switch control ->  **bug**

<img width="515" alt="Screenshot of the issue" src="https://github.com/epam/ai-dial-chat/assets/98586297/05b8df08-05e8-4909-959b-a46b0f36157e">

Note: screenshot of the issue area showing the extensive clickable region for the "Full width chat" toggle.

**Expected result:** "Full width chat" should only activate when you click on the toggle.

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. Now "Full width chat" settings is on/off if to click on the OFF/ON UI element only.
