### ISSUE TITLE
Add missing gradient for error message

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#458]
#### Actual result:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/77f2af39-c318-4d11-b84b-869687cd8c0b)
#### Expected result:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/52403dc7-7703-44bf-b8b9-e67bd88dd107)

To reproduce you can import such file:
[chatbot_ui_conversation_1-4.json](https://github.com/epam/ai-dial-chat/files/13830848/chatbot_ui_conversation_1-4.json)

**Comment by VolhaBazhkova** [comment]
Return to @IlyaBondar as we need to fix one more case:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/4cdcfaff-7479-4d9a-89a7-00d4bfb565fe)

**Comment by VolhaBazhkova** [comment]
Now the fix is perfect with "Not allowed model" error on staging env.
@IlyaBondar Can you check one more time the fix with text as there is still a little bit of text shown:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/68acbe57-f0a8-4083-b738-d950b38c1a39)

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully.
