### ISSUE TITLE
Error message goes out of bounds for long filenames when uploading

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#465]
1. Upload a file with an exceptionally long name through "Upload from device" screen which already exists in uploaded attachments -> note that error message goes out of bounds -> **bug**

<img width="471" alt="screenshot of the issue" src="https://github.com/epam/ai-dial-chat/assets/98586297/6031b1eb-e102-465e-9898-08832402dbba">

**Expected result:** The error message mustn't go out of bounds

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. Error message is not broken (verified two errors - equal names and incorrect chats in the name). Examples:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/05138dd0-2afd-48cb-bbb6-fe60c42fc727)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/6705c4d5-7a3d-4ca4-a746-d321db52f036)
