### ISSUE TITLE
Change model selection form to combine different versions of the same model family under one option

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#468]
Related #782 

Example gpt-4 currently has 4 options:
- 0314
- 0613
- 1106-preview
- latest (0613)

All 4 need to be combine under the same gpt-4 option to not pollute model selection form with versions of the same model. Default version selection must be latest. Where latest means latest stable version. 1106-preview cannot be considered latest, as it's preview and not stable.

**Comment by DaryaKarniyenka** [comment]
Design https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=4939%3A9167&mode=design&t=lwp3DnVz4qErt3oO-1

![1920_model_versions](https://github.com/epam/ai-dial-chat/assets/151838896/cf0be9f8-9203-4b5e-a0db-b00d1a243923)
