### ISSUE TITLE
Add option to copy markdown table from the chat response

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#469]
It would be nice to provide different versions of table copy, such as csv, markdown code and text values that would be correctly pasted into excel/google sheets.

**Comment by DaryaKarniyenka** [comment]
![1920_table](https://github.com/epam/ai-dial-chat/assets/151838896/588cd895-2b72-466a-a087-e148f5245f5d)

Also we need to add tooltips for each icon.

Figma: https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=7155%3A10273&mode=design&t=XSd6EKadcP4SMdaH-1

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. Please note that #1275 and #1302 were also found and fixed
