### ISSUE TITLE
[MacOS,Safari] while response is generated, content section  jumps up to the top of the page and back to the bottom each time a new line is printed. 

### ISSUE THREAD

**Issue by IlyaRabtsau** [epam/ai-dial-chat#470]
Received several user reports regarding issue of content well jumping to the top of the conversation and to the bottom each time a new line is printed:
https://gitlab.deltixhub.com/Deltix/openai-apps/aiproducts1ls/-/issues/123
https://gitlab.deltixhub.com/Deltix/openai-apps/aiproducts1ls/-/issues/125

Steps to reproduce:
Generate content in any model while using desktop Safari browser in MacOS.
[Video](https://epam-my.sharepoint.com/:v:/p/ilya_rabtsau/EedtChEco9RAjlD4sBV_FpIBajjRnFl8uHWyXVYcWCF-cg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=CIzRIQ)

**Comment by VolhaBazhkova** [comment]
Verified on staging om MacOS, Safari successfully
