### ISSUE TITLE
Scroll background is not transparent in the central chat with user questions, model answers

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#478]
1. Create a chat with several questions/answers to appear vertical scroll
2. Please note that on dark grey part of the screen there is black scroll background -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/0a63c965-1aa4-43b6-9d62-9706b4a03505)

Note: scroll background is ok in Talk to pop-up screen
**Expected result:** scroll background should be transparent

**Comment by Alexander-Kezik** [comment]
The browser reserves the scroll space on its own and we can't completely change it as we want. There is no easy way to fix this at the moment
