### ISSUE TITLE
It's impossible to start New conversation if configuration config has incorrect recent model (even  if it is updated to correct one later - need to clear local store to fix the problem)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#488]
New user faced with problem while DIAL configuration:

1. Need to update config file to have recent models: only one and restricted for user or not existed
2. User logged in the DIAL for the first time  -> new conversation is not created, user sees DIAL without settings

**Note:** user fixed the issue by clearing local store

**Expected result:** ??? need to investigate and discuss 
Do we need to update default variables ? Update documentation for new users?

**Comment by denys-kolomiitsev** [comment]
It is not possible to create new conversation if in **'recentModelsIds'** is **id** of the restricted or not existed model (see the screenshort below).
![image](https://github.com/epam/ai-dial-chat/assets/143205282/225010d7-ca11-44d1-8cde-b61f118a10d3)

![image](https://github.com/epam/ai-dial-chat/assets/143205282/e1316d8b-e17f-4170-b047-d2079e70b810)

Way to reproduce localy:

1. In the Environment Variables set RECENT_MODELS_IDS to "not-existing-model".
2. Start an APP. 
3. Clean the local storage.
4. Reload APP. New conversation is not created.
5. In the Environment Variables set RECENT_MODELS_IDS to existing model.
6. Reload APP. New conversation is not created - > **bug**

**Comment by VolhaBazhkova** [comment]
Verified locally successfully. 
If there is incorrect (not existed) model in RECENT_MODELS_IDS, DIAL uses the default one set in "DEFAULT_MODEL" variable. If DEFAULT_MODEL" variable is incorrect model set (or not-existed one), DIAL uses the first available received model from API.
