### ISSUE TITLE
[iPhone SE, Safari] Chat and Prompt panels are opened at the same time if to log into DIAL for the first time

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#490]
The original issue is #241 The fix was verified on iPhone 13, iPhone 14pro based on iOS 17.1.2 and Android, browser (with toggled device toolbar) successfully. But the issue is still reproduced on iPhone SE with 17.1.2 and 17.2.1 iOS. 

We are going to investigate the issue deeper in case of end-users complain.
![image](https://github.com/epam/ai-dial-chat/assets/20163971/58d474f8-4d8e-4883-a85d-ba96bf02e3f5)

**Comment by IlyaBondar** [comment]
I think the problem is in User-Agent detecting (IsMobileView)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/bc485e79-7db5-48b6-a741-5953dd841ed0)

**Comment by VolhaBazhkova** [comment]
Verified on iPhone XS and staging server successfully.
