### ISSUE TITLE
Need to fix settings panel

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#492]
Need to fix following parts of settings panel:
1. hide cross icon
2. move button to right
3. add divider for button section
#### Actual:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/c37c31c0-28bd-4032-9dd0-ec95742ff294)

**Comment by DaryaKarniyenka** [comment]
1. Let's keep cross icon without changes 

![chat_settings](https://github.com/epam/ai-dial-chat/assets/151838896/a59306b2-809c-4f6a-ad38-512fda5d60e8)

**Comment by VolhaBazhkova** [comment]
Please update the following screen also
![image](https://github.com/epam/ai-dial-chat/assets/111180458/64517fb2-3107-4d93-8ad7-43917b257ff5)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully

**Comment by VolhaBazhkova** [comment]
Return to developer as we need to fix the following items:
1. Chat settings: horizontal divider should have width like vertical one
2. Chat settings: the cornet is rounded, but shouldn't
3. In the light theme horizontal divider is white, but should be grey

![image](https://github.com/epam/ai-dial-chat/assets/111180458/fe3e3bba-f48b-4fff-abd2-d2b20b3bcb58)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/e323b9e9-f6bb-401b-a443-c60c98f618f9)

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. 
Please note that there is tiny issue (not reported): 
1. Click on Settings button inside chat with history
2. Press Ctrl+"+" several times to have display size 175%
3. Note that vertical and horizontal dividers have different width
![image](https://github.com/epam/ai-dial-chat/assets/111180458/7b26906b-8fcd-4018-84b6-b2e14ee7435c)

Seems it's reproduces in rare cases, that is why no issue reported
