### ISSUE TITLE
Request API key form has not nice description at the top

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#494]
![image](https://github.com/epam/ai-dial-chat/assets/111180458/cf02e9ce-b9fe-467a-b80d-80384ac70913)

**Comment by Alexander-Kezik** [comment]
![image](https://github.com/epam/ai-dial-chat/assets/98586297/6c59f7df-e418-4eb1-8918-e1202b1d62c3)
![image](https://github.com/epam/ai-dial-chat/assets/98586297/319872a1-cd38-4913-9a36-d0edfb0e3793)

Also, these links should open in new tabs.

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. UI is nice, links are opened in new browser tab
