### ISSUE TITLE
Update attachments functionality

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#497]
1. Change type property in files and folders 
nodeType: { FOLDER, ITEM }
resourceType: { FILE, PROMPT ... }
2. Migrate all conversations with backend files URL from `bucket/a/b/c.txt -> file/bucket/a/b/c.txt`
3. Change backend metadata URL from  v1/files/metadata to v1/metadata/files

**Comment by mikitabut** [comment]
Hello @VolhaBazhkova 
Please retest files functionality for models to be sure that all changes are correct. To being able to test migrations of old files to new ones you need to upload old file with old files URLs and check that all images and files updated to new URLs when exporting this conversations again.

**Comment by VolhaBazhkova** [comment]
Verified using the following steps:
1. Export chat created based on Imagen model with some generated picture from Prod env.
2. Import the json on Staging env.
3. Export the chat again from Staging env
4. Checked the URL structure has been updated to new one
