### ISSUE TITLE
It's possible to send new message if previous response contains error only (applicable for Gemini Pro Vision model only)

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#532]
Gemini Pro Vision response contains Error stage with error explanation => we should disable Send button and add tooltip explanation to regenerate response

To reproduce: 
1. create a chat based on the model
2. send any text without attachment picture or send text file -> error appears
3. type any text and click on Send button -> the message is sent -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/30f4cefc-3e42-474c-8cfa-eb063e4ea088)

**Expected result:** disable Send button, tooltip-explanation

**Comment by avavilau** [comment]
We need to support new design for user readable error message reporting

**Comment by VolhaBazhkova** [comment]
Verified on UAT successfully
![image](https://github.com/epam/ai-dial-chat/assets/111180458/2a9d6a6d-a2c7-4480-9ff5-7e3dc062fd3a)
