### ISSUE TITLE
System prompt cannot be deleted if it exceeds the maximum length limit

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#559]
1. Enter the number of characters that exceeds the max limit and press "backspace" -> you will see an error message about an invalid number of characters -> **bug** 

https://github.com/epam/ai-dial-chat/assets/98586297/73a4631c-7685-4469-8898-5a4de5661625

This works fine if you'll highlight enough characters at once to avoid crossing the limit.

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully using the following steps:

1.  Click on "New conversation" 
2.  Set GPT-4-0613 model (it has 24000 limit of tockens)
3.  Paste some text in System prompt to reach models' limit -> message pop-up appears
4.  Don't clear system prompt
5.  Switch to model with lower limit, e.g. GPT-3.5 ( which is alias now and has 12000 limit of tockens)
6.  Set cursor in System prompt field and use backspace -> text is deleted ok
7.  Highlight a world and press delete -> text is deleted ok
