### ISSUE TITLE
Need to fix postfix incrementation during "Duplicate" executing

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#560]
![image](https://github.com/epam/ai-dial-chat/assets/20163971/2ca2d073-039c-4b3c-907a-07e6a33a7aa9)

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully. Probably it's not the best numeration, as now chat_test is duplicated and named as chat_test 2. I feel that it's a little bit inconsistent as new chat/folder/prompt is created started with 1 (New folder 1, New folder 1 etc). Seems we will wait for customers feedback.
