### ISSUE TITLE
Mobile redesign

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#582]
The ticket is created to re-design Mobile (for [Overlay](https://github.com/epam/ai-dial-chat/issues/565)).

Please find Figma link (available for DIAL team only): https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=4674%3A9250&mode=design&t=nhapmnjG29Hnd7h1-1

![image](https://github.com/epam/ai-dial-chat/assets/151838896/0df8d723-061e-4bde-899e-79b189b8e9aa)

**Comment by VolhaBazhkova** [comment]
Verified on staging, please note also new tickets #622 and #618
