### ISSUE TITLE
Using NEXT_PUBLIC_DEFAULT_TEMPERATURE in the chat overrides whatever the user set as temperature in chat UI

### ISSUE THREAD

**Issue by photonn** [epam/ai-dial-chat#588]
If you set the chat env variable NEXT_PUBLIC_DEFAULT_TEMPERATURE to 0 and the user select a different value using the chat UI temperature slider, the core log shows that request come with NEXT_PUBLIC_DEFAULT_TEMPERATURE value, not what user selected in UI. I understand NEXT_PUBLIC_DEFAULT_TEMPERATURE should be used until the user change the temperature manually and not override what user decides.

chat version: 0.4.1
core version: 0.6.0

**Comment by irinakartun** [comment]
the request to chap api is valid, but we still send "temperature":0 to proxy api

**Comment by photonn** [comment]
Ill test it. Thanks for the fix.

**Comment by irinakartun** [comment]
verified on staging env
