### ISSUE TITLE
Need to show message explanation in case share link is expired 

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#589]
According to the requirements, prompt/ chta share link is available three days only. When it's expired, let's show the message below:

![image](https://github.com/epam/ai-dial-chat/assets/111180458/f9358ccf-ac01-4cf1-a8e4-632bffa8c3a4)

Figma link (for epam team only): https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=5658%3A9325&mode=design&t=F0BrN2pLehiacctP-1

**Comment by mikitabut** [comment]
Hello @VolhaBazhkova 
Agreed with @DaryaKarniyenka that error box is enough in such case

**Comment by VolhaBazhkova** [comment]
Returned to developer as there is incorrect error message 
![image](https://github.com/epam/ai-dial-chat/assets/111180458/d7f78bf7-257a-4134-aaf9-8f211668b411)

**Comment by VolhaBazhkova** [comment]
Now the message is the following
![image](https://github.com/epam/ai-dial-chat/assets/111180458/dcb1a351-5078-4f9a-b1b9-e26ac91ffce9)
Verified on staging env. using icorrect shared link.
