### ISSUE TITLE
[Attachments] Need to forbid # symbol

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#592]
It is impossible to load file with # symbol in the name. The following screen is shown (nothing happens). no error in console

![image](https://github.com/epam/ai-dial-chat/assets/111180458/7576235b-2628-47a5-a922-9ed8e6d7858d)

Expected: need to show error if to load file with # in the name
Note: similar fixes were here #253 #417

**Comment by Alexander-Kezik** [comment]
need to forbid \ symbol also

**Comment by VolhaBazhkova** [comment]
Now on staging the symbols are forbidden. But the change is going to be reverted
