### ISSUE TITLE
Need to update exported file names

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#594]
Now there are the following file names if to export single chat/prompt, structure of chats/prompts
![image](https://github.com/epam/ai-dial-chat/assets/111180458/974575e3-20a3-472c-9f39-e59eae31d230)

Expected result:
1) need to change "chatbot_ui" to "ai_dial_chat"  TBD will it work for prompts
2) need to make the export name configurable. Use NEXT_PUBLIC_APP_NAME instead of ai_dial_chat
3) chat /prompt name should be used for exported file (encoding, snakecase). TBD max allowed symbols in names (23 symbols?)
4) use the date of export in the name. Like it's used now
5) need to clear "chatbot_ui" name in readme, e2e tests (probably, it's a separate task)

**Comment by irinakartun** [comment]
verified on local env: not allowed symbols in filename are replaced with "_"
