### ISSUE TITLE
Address feedback on Playback functionality (confusing button, starting screen, user focus management)

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#600]
General feedback is that user wants playback to look as close to normal chat UX as possible.

1.  Starting screen is very different to normal chat, it's screaming "I'm Playback". Show model selection window with only one model available might be a good solution. Note: it's very common to playback model/application that your environment does not have 
2. We need to manage audience focus and not showing next chat message prematurely. Right now user sees next message before it's even needed that drags his attention. We either need to not show it in edit box at all (may make playback chat to look different which is not good) or make it appear after user press next.
3. Exit button is extremely hard to find and it's tooltip is very confusing. We need to somehow either make it noticable (without screwing the overall look-and-feel of a normal chat) or find another place for it.

**Comment by DaryaKarniyenka** [comment]
1. Start screen

- Show playback icon and prefix [Playback] for the selected model
- We do not allow any interactions with the chat settings panel. We should use a prohibiting cursor and show hint "Editing conversation settings is not available in playback mode" on click
- Show placeholder "Type a message..." in the main chat input. We should use a prohibiting cursor and show hint "Editing conversation messages is not available in playback mode" on click
![image](https://github.com/epam/ai-dial-chat/assets/151838896/eb1e13d8-cd3b-497b-9821-d72aff684065)

2. Let's show placeholder "Type a message..." right after sending previous message and only after clicking "next message" button we will show next message preview in input. 

3. Let's use "Stop playback" button

![image](https://github.com/epam/ai-dial-chat/assets/151838896/44097d7c-27b1-4524-8707-e5043def82dc)

**Comment by DaryaKarniyenka** [comment]
Figma https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=2889%3A8558&mode=design&t=OCuYxSjnViZVHk0c-1

**Comment by mikitabut** [comment]
The points 2 and 3 already finished

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully.
