### ISSUE TITLE
Need to show confirmation message if user imports chat/prompt/structure which is already exist 

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#609]
1. Create a chat -> export it
2. Don't delete the chat -> import it 
Now nothing happens. There is no any explanation or action. 

**Expected result:** 
Need to show confirmation modal window with the question:
"You already have chat <chat name>, do you want to replace?" with buttons Cancel and Replace
or 
"You already have prompt <chat name>, do you want to replace?" with buttons Cancel and Replace
If there is a structure with several files to be replaces, the list should be shown

See also #797

**Comment by VolhaBazhkova** [comment]
Seems that we have a similar one #123

**Comment by DaryaKarniyenka** [comment]
Confirmation window. By default we should show "Postfix".

![image](https://github.com/epam/ai-dial-chat/assets/151838896/b551b753-b199-41b7-bcf9-5e0f01d9e1ba)

Figma: https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=7312%3A10411&mode=design&t=XSd6EKadcP4SMdaH-1

**Comment by YauheniyaH** [comment]
Ticked tested on Staging. The following bugs found:
 https://github.com/epam/ai-dial-chat/issues/1237
 https://github.com/epam/ai-dial-chat/issues/1234
 https://github.com/epam/ai-dial-chat/issues/1235
 https://github.com/epam/ai-dial-chat/issues/1239
https://github.com/epam/ai-dial-chat/issues/1244
https://github.com/epam/ai-dial-chat/issues/1232

https://github.com/epam/ai-dial-chat/issues/1231
https://github.com/epam/ai-dial-chat/issues/1230
https://github.com/epam/ai-dial-chat/issues/1191
