### ISSUE TITLE
System prompt selected from a list doesn't apply to conversation

### ISSUE THREAD

**Issue by MaksimMeshcheriakovEPAM** [epam/ai-dial-chat#610]
**Environment:** MacOS Ventura 13.6.3; Chrome 121.0.6167.85; GPT-3.5; 

**Preconditions:** there is a list of prompts 

**Steps to reproduce:**

1. In the Settings -> System prompt press "/" and select any prompt from a list (prompt "Let's play a game. I give you a word and you answer me a word of opposite meaning" has been selected for this scenario)
2. Type in some word in the Chat Panel
Expected: the word of opposite meaning will be typed out 
Actual: some explanation of the provided word's meaning has been typed out
Video: https://github.com/epam/ai-dial-chat/assets/33826856/7891de86-507e-4cc6-a5bf-829f53e11abb
3. Clear the dialog
4. Go to the prompt from step 1 and copy it's text; then paste this text into Settings -> System prompt
5. Type in some word in the Chat Panel
Actual: the word of opposite meaning will be typed out 
Video: https://github.com/epam/ai-dial-chat/assets/33826856/6b377333-d521-498a-a23b-c09f0507d2f0

NOTE: this scenario was reproduced with several prompts in two languages (English and Russian).

**Comment by avavilau** [comment]
@MaksimMeshcheriakovEPAM  we confirm the bug and will try to address in the nearest release

**Comment by VolhaBazhkova** [comment]
Verified on staging server successfully.
