### ISSUE TITLE
Edits for mobile and overlay redesign

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#618]
Mobile and overlay:

1) Message side paddings should be 12 px
![image](https://github.com/epam/ai-dial-chat/assets/151838896/45c6b822-1ebe-4363-94d9-328c0cbd1ff0)
2) Min width for chat title is 200 px, but max is width of the message content
![image](https://github.com/epam/ai-dial-chat/assets/151838896/eb7231ff-a530-4086-bbc6-0487419a89a7)
3) Remove left padding for model icon 
![image](https://github.com/epam/ai-dial-chat/assets/151838896/d88e11be-0a5c-490c-90f4-4229fef9e9f8)
4) Let's color the profile icon in text/secondary
![image](https://github.com/epam/ai-dial-chat/assets/151838896/c45b3cd2-3641-4861-b1f1-2aabd7712fa8)

Mobile only:

1) Context menu on tap for messages. Remove right icons
![image](https://github.com/epam/ai-dial-chat/assets/151838896/467ac73e-e269-49f9-bb72-d6863339a6ff)
2) Profile icon size is 24x24 px
![image](https://github.com/epam/ai-dial-chat/assets/151838896/1638b791-272a-4f23-be4c-57a2f35cc5e2)
3) Let's increase these icons size to 20 px
![image](https://github.com/epam/ai-dial-chat/assets/151838896/cd3e3c48-99ad-4902-951a-5e0bf447c03f)

**Comment by VolhaBazhkova** [comment]
Verified on UAT successfully
