### ISSUE TITLE
Remove extra paddings in the chat settings window

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#629]
Сontent should not stretch across the entire height on the right side. We should remove extra paddings.
If there is free space, it should be left after the addons section.
![image](https://github.com/epam/ai-dial-chat/assets/151838896/ee1c31b0-dcc7-4b60-8965-99240896a53f)
![image](https://github.com/epam/ai-dial-chat/assets/151838896/038647bd-f073-4acd-9f2c-f063bb6f7e29)

**Comment by YauheniyaH** [comment]
issue is not actual any more, was fixed with implementation of new UI of change application /Talk to model
