### ISSUE TITLE
Need to integrate export/import with Stateful API

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#640]
Need to implement:
- [x] export single chat: upload all entities for export from API (chats, folders, attachments)
- [x] export history: upload all entities for export from API (chats, prompts, folders)
- [x] export: need to upgrade export version (`"version": 5`) and replace "chatbot_ui" to "ai_dial_chat"(see #594 )
- [x] import: need to generate id from GUID-format to path-format(see `getPathToFolderById` + `generateConversationId`/`generatePromptId`) on the fly for export format less version 5 (see #633)
- [x] import: save imported data in API

Additionally:
- [x] see #594 
- [ ] see #609
- [x] see #651 
- [x] see #652

**Comment by VolhaBazhkova** [comment]
Verified on staging. Import/export works fine without attachments.
See also #797 
See #819 for export/import with attachments
