### ISSUE TITLE
[Integration] Edits to the conversations list in compare mode

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#661]
1. Icon size is 18 px
2. Let's show the conversation name on one line with dots at the end
![image](https://github.com/epam/ai-dial-chat/assets/151838896/6df62b2d-4ade-43f1-bac8-7557639ba76b)

Figma: https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=249%3A8205&mode=design&t=BdqR07Mf0Mjtk9NE-1
![image](https://github.com/epam/ai-dial-chat/assets/151838896/863a39e0-9620-4128-a501-4aebb6555e88)

[Volha] It's not a rare case to have chats with long name (created automatically). These chats in Compare mode look in the following way:

![image](https://github.com/epam/ai-dial-chat/assets/111180458/445aaef4-9aa9-4054-b0af-a32796fcfb7e)

**Comment by VolhaBazhkova** [comment]
Verified on UAT server, now the chat name is cut in the list, but reported #1037
