### ISSUE TITLE
API: handle all error cases

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#663]
Possible cases:
- [ ] unsuccessful create (maybe already exist, chech where we can use tryCreate + get/save new name with postfix)
- [ ] unsuccessful create Replay, Playback and Duplicate copies (maybe already exist)
- [ ] if original chat was deleted and user tries to execute Playback, Replay, Duplicate, Share options of context menu (other cases?)
- [ ] handle all errors from API and log them

**Comment by VolhaBazhkova** [comment]
I wasn't able to verify all the scenarios during the release testing phase. But please note some reported issues #733, #724, #728

Also faced with some errors (ok):
![image](https://github.com/epam/ai-dial-chat/assets/111180458/7d7da4b3-c7b7-477b-ab05-6b0b30c636e3)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/13ef22f8-63a9-4fa3-91d8-242f8c5c3619)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/4b597bf2-a920-4304-a4f6-a7febc2769a3)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/d42ee7f3-ece5-4cc2-8288-a5d616a2c8a0)
