### ISSUE TITLE
[Integration] Overlay conversations from different browsers appear in main DIAL

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#669]
1. Open landing page -> open DIAL Overlay -> send any message there to create a chat
2. Open DIAL -> Note that the chat appears there in Today -> **bug**
3. Send any message to the chat in DIAL
4. Refresh Overlay -> the message/response appear -> **bug**

  **Expected result:** Overlay should "be separated" from DIAL

**Comment by mikitabut** [comment]
Duplicate of #569
