### ISSUE TITLE
[Attachments] it's impossible download file if it contains % in the name

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#686]
**Preparation:**
1. Click on Clip icon in Conversations panel
2. Click on Upload from device -> select a file with % in the name -> click on "Upload and attach files" -> the file appears on Manage attachments screen

**Steps:**
1. Hover over the file name -> click on three dots menu -> select Download
2. Check download files and browser download history -> the file is not downloaded -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/2f7f662b-c618-495c-abf4-3bcd3270fe08)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/9a17be8d-dbf6-4795-82ec-f4f289942a45)

**Note:** | \ * symbols are changed to _ in file names -> it seems to be ok
**Expected:** can we allow to download file with % in the name or just change it to _ ?

**Comment by IlyaBondar** [comment]
Need to fix such case
![image](https://github.com/epam/ai-dial-chat/assets/20163971/073c3f13-3a90-41e5-8238-8791d7e64aec)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/e48744e3-5ab9-47d2-b6c6-14103cf3849d)

**Comment by VolhaBazhkova** [comment]
Verified on UAT (both names with %, but not all the spec chars) successfully
