### ISSUE TITLE
[Integration] There is no error on UI if there was interruption while response is being generated

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#691]
1. Create a chat and send a message like "Type 50 famous cities"
2. While response is being generated refresh the browser -> the response is interrupted (ok), but there is no error on UI -> **bug**

On staging now:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/bea52523-2392-457e-a5aa-9eb1aa4d7944)

Expected as on Prod now:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/82602e6e-0c69-4d83-bd35-345732d7d248)

**Comment by IlyaBondar** [comment]
The behavior is consistent with Open AI and we can't save the error without connection

**Comment by VolhaBazhkova** [comment]
Verified by auto-tests
