### ISSUE TITLE
[Integration] Imported chat/prompt in folder appears only after browser refresh

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#695]
1. Import from the previous import version where chat or prompt is located in folder
Example of jsons:
[chatbot_ui_prompts_history_2-13.json](https://github.com/epam/ai-dial-chat/files/14271619/chatbot_ui_prompts_history_2-13.json)
[chatbot_ui_conversation_2-13 (1).json](https://github.com/epam/ai-dial-chat/files/14271671/chatbot_ui_conversation_2-13.1.json)
2. Click on triangle near folder -> nothing appears -> **bug**

Note: 3. Refresh -> imported chat/prompt appears in the folder
Note: the same case but with chat/prompt created in current import version5 is not reproduced. Seems that issue appears with "old" files

Expected: if to open imported folder, imported chat/prompt is shown

**Comment by denys-kolomiitsev** [comment]
Fixed in scope of #640
PR #752

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. Reported #797 #798
