### ISSUE TITLE
Shared icon appears only after browser refresh

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#703]
1. In chat context menu select Share icon
2. On the pop-up click on Copy button and close the pop-up
3. Check the chat -> there is no shared icon -> **bug**

Note: Shared icon appears after browser refresh
Note the same is for prompts. folders

Expected: Shared icon appears if user click on copy icon, or copy the link using hot keys and closes the pop-up

**Comment by mikitabut** [comment]
Not a bug, because share icon appearing only after other user accepting invite
