### ISSUE TITLE
[Integration] It's impossible to delete chat (error 500 in console) if there any shared file exists in the structure

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#712]
1. Create chat1 and chat2
2. Share chat1 (open shared link by another user) to have shared icon appeared
3. Delete chat2 thru context menu -> error in console -> **bug**
4. Refresh the browser -> deleted chat appears
![image](https://github.com/epam/ai-dial-chat/assets/111180458/6986f56f-c0ab-4750-96e0-7ef1a0e3b799)

Note: verified on new user, that chat is deleted ok if there is no any shared chat

Note: blocker #696

**Comment by mikitabut** [comment]
Hello @VolhaBazhkova 
It was an issue on core side and @Maxim-Gadalov already fixed
Please recheck it

**Comment by VolhaBazhkova** [comment]
This particular case was verified successfully on staging
