### ISSUE TITLE
[Shared] Need to notify user that if he/she renames shared chat/prompt/folder it will disappear from "Shared with me"

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#744]
1. User1 shared a  prompt
2. User2 has the prompt in "Shared with me"
3. User1 updated description or body in the prompt -> changes are available for User2 -> ok
4. User1 updates the name of the prompt -> after browser refresh the prompt disappears from "Shared with me" in User2's structure

This situation is not evident. We need to help users.

**Comment by mikitabut** [comment]
Agreed to add confirmation modals for all entities removal and renames, but for shared resources(by me) we also need to add some text describing that users who use this shared resource also will lose access to it

**Comment by IlyaBondar** [comment]
> Agreed to add confirmation modals for all entities removal and renames, but for shared resources(by me) we also need to add some text describing that users who use this shared resource also will lose access to it

@avavilau , @DaryaKarniyenka @mikitabut  , I don't think that it's good idea to ask twice confirmation for renaming if it's not shared entity because it's annoying. For shared yes, it's required because it's not obvious that sharing will be broken

**Comment by VolhaBazhkova** [comment]
Verified on UAT server, reported #985
