### ISSUE TITLE
[Integration] Drag&drop doesn't work on prompt panel

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#745]
**Steps:**

1 Create 2 folders on prompt side panel
2 Try to drag&drop one folder to another -> no effect
3 Try do move prompt into some folder or prompt inside folder out of it -> no effect

https://github.com/epam/ai-dial-chat/assets/15156585/39270d2e-297b-4876-95e9-4618a7376d78

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
