### ISSUE TITLE
Need to make prompt body required

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#78]
Need to add blue asterisks here and forbid to save Prompt, when the field is empty

![image](https://github.com/epam/ai-dial-chat/assets/111180458/96905e0e-d49f-45be-9a7f-76e2a1d254c6)

**Comment by IlyaBondar** [comment]
I suggest to not create a prompt in promptbar until all required fields filled and `Save` button clicked.
And we have two variant what should be used for existing prompt as content:

- use prompt name if prompt content is empty
- use "-" or "<empty>" if prompt content is empty
@VolhaBazhkova , @avavilau

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
