### ISSUE TITLE
[Integration] "Delete all conversations" action clears shared with me chats also

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#780]
1. Prepare Shared with me structure with folders and chats inside
2. Click on Delete all conversation
3. Note that all the chats are deleted -> ok. Seems that New conversation 1 should be created automatically....-> **low priority issue?**
and all nested levels in Shared with me disappeared -> **bug**

Note: if to refresh the browser Shared with structure appears again -> ok
Note: it's not reproduced in prompts -> ok

https://github.com/epam/ai-dial-chat/assets/111180458/7d2afa76-4f31-444d-bd83-b5bfc3921a36

**Comment by IlyaBondar** [comment]
Related to #707

**Comment by VolhaBazhkova** [comment]
Verified on UAT successfully
