### ISSUE TITLE
Option to set personal custom logo from user preferences (from personal storage)

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#783]
## This must be config pluggable feature

**Comment by denys-kolomiitsev** [comment]
**Designs**
![image](https://github.com/epam/ai-dial-chat/assets/143205282/b6ebba6c-8560-45a1-a5b6-bbf09a1aa514)

**Figma link:** https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=1479%3A6708&mode=design&t=gfZ7FiCMXz01B1vl-1

**Comment by VolhaBazhkova** [comment]
The feature was verified on UAT server successfully. Reported #919, #920, #984, #1036
