### ISSUE TITLE
Add option to attach file into application by link 

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#785]
Should only be available for application that support it

**Comment by DaryaKarniyenka** [comment]
Design https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=6855%3A10174&mode=design&t=VMApIKhex0OgPgJW-1

![image](https://github.com/epam/ai-dial-chat/assets/151838896/fc21e326-22b1-4087-913b-e83626274a91)
![attach_link](https://github.com/epam/ai-dial-chat/assets/151838896/6b364e23-5acb-4e4f-83b1-7c794cc33d2f)
![input](https://github.com/epam/ai-dial-chat/assets/151838896/52120a53-1b08-4eda-bb38-3d643c81d08a)

**Comment by VolhaBazhkova** [comment]
Reported #1273 #1274 #1275

**Comment by VolhaBazhkova** [comment]
Verified on staging env. Reported #1275  #1274 #1273 #1273 #1301 #1303 #1276
