### ISSUE TITLE
[Sub-Project] Show error display_message to user if it occurs 

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-chat#788]
Related: https://github.com/epam/ai-dial-sdk/issues/78

**Comment by mikitabut** [comment]
@VolhaBazhkova  This ticket can be tested by sending any message to [Sub-Project] and getting not standard message

**Comment by VolhaBazhkova** [comment]
Specific error message is shown if to create a chat based in sub-project model in DIAL
![image](https://github.com/epam/ai-dial-chat/assets/111180458/10e11389-4640-4d57-b58f-48084bc13cd5)
