### ISSUE TITLE
Need to redesign information tool tip on model icons in chat history and in chat header

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#79]
**[Volha: this info is from old DIAL]** As it's allowed to change setting during the conversation, it's needed to add information tool tip on model icons in chat history like in chat header
![image](https://github.com/epam/ai-dial-chat/assets/111180458/3e0f9736-3a8c-4290-bfac-3260652203cc)
**Now 12/10/2024** it has the following design:
![image](https://github.com/user-attachments/assets/499ab257-b4e4-446d-8fe0-2571301ed550)

**Expected new design if to click on Agent icon and on Settings icon in chat header and in chat history:** 
![image](https://github.com/user-attachments/assets/34b030cd-0c1c-446c-8140-b74ec07bb538)
![image](https://github.com/user-attachments/assets/5ec685f8-14ce-422b-a733-dbc6b3a8f6fa)

https://www.figma.com/design/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?node-id=14399-63907&t=8urrKPQ8EqEmvgJs-1

**Comment by YauheniyaH** [comment]
Need to fix font for tooltip for models in 'Select agent for conversation' form and for icon of model in left chat panel
Actual: Italic
![image (1)](https://github.com/user-attachments/assets/052c7615-8af3-4fee-8cb4-d20c597626af)
![image (64)](https://github.com/user-attachments/assets/4ccf23a5-a8ce-4214-882d-23245bcd1b31)

Expected: regular

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
