### ISSUE TITLE
[Core][Shared] 404 error in console. It's impossible to get rid of shared chat if user clicks on the link after original chat has been deleted. Shared link is still valid though original chat is deleted.

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#807]
1. By user1 create a chat and share it
2. By user2 click on the link -> shared chat appears in Shared with me (ok)
3. By user1 delete the chat
4. By user2 refresh the screen -> shared chat disappears from Shared with me (ok). Can we show any message-explanation for user2 why the chat disappears? Any notification? -> **issue1**
5. By user2 click on the link again -> the chat appears in Shared with me -> **issue2**
If to click on the shared chat, error 404 in console appears, the chat disappears. After browser refresh, the chat again appears in Shared with me. Now it's impossible to remove the chat!

![image](https://github.com/epam/ai-dial-chat/assets/111180458/08c27cb1-767e-4617-b7f7-ed682643da80)

Note: need to check the same scenario for prompts

Expected: TBD

**Comment by mikitabut** [comment]
Hello @VolhaBazhkova 
Looks like this ticket will be fixed right after https://github.com/epam/ai-dial-core/issues/221 will be done

**Comment by IlyaBondar** [comment]
Related to https://github.com/epam/ai-dial-core/issues/221

**Comment by VolhaBazhkova** [comment]
Verified on UAT successfully. 
note that 409 error in console still exists, but  shared link is not valid and error message appears "We are sorry, but the link you are trying to access has expired or does not exist."
