### ISSUE TITLE
[Integration] 403 error in shown instead of picture if to import by another user. 

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#819]
Steps1:
1. By user1 create a chat (use Imagen or Stable/Dalle/Gpt-V.. etc) and generate several pictures, sent a picture
2. By user1 export the chat using "Export with attachments" option
3. By user2 import zip
4. By user2 expand attachments -> attachment is not found -> **bug**
![image](https://github.com/epam/ai-dial-chat/assets/111180458/1c4a86cf-9b13-407f-b5c7-354cb217d0f7)

Note: pictures appear in Attachments -> import structure is not correct (bug) 
Note: file can be downloaded (ok)
Note: the issue is not reproduced with DIAL RAG document

Steps2:
If to continue the same scenario but with user1
1. By user1 rename original chat (to have correct import in future)
2. By user1 import the same chat -> pics are shown
3. By user1 do NOT delete pics in image structure
4. By user1 delete the pic from app structure
5. By user1 expand the attachments -> no found pictures -> **bug**

The issue is with the new attachment path.

Expected: 

- in imported chat pictures are used from imports structure;
- the conversations with same name do not create a new folder with postfix;
- the postfix is added to the files with the same name;

**In scope of this issue the following behaviour should be fixed:**

- when user stops import -> attachments are saved under imports/conversation_name
- when user resumes import -> attachments are duplicated under imports/conversation_name

**Expected behaviour**: postfix should be added not to conversation_name dir but to attachment

![image](https://github.com/epam/ai-dial-chat/assets/15156585/0a13b265-57b2-4c54-b7d1-3a946e731bbe)

**Comment by irinakartun** [comment]
verified on staging - user is able to open/download attachment from the respons; if he tries to download attachment from request, he got error because of incorrect path to attachment:

![image](https://github.com/epam/ai-dial-chat/assets/15156585/affff764-8a84-45b2-80e9-4698f9c414c7)

**Comment by irinakartun** [comment]
one more issue to fix:
attachments uploaded from the device are saved by: **\res\files\bucket**\ path within exported .zip.

**Expected result**: \res\path

**Comment by irinakartun** [comment]
verified on review env by autotests
