### ISSUE TITLE
if there is "\" symbol in conversation name, DIAL creates folders structure

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#821]
Reproduced on UAT environment. And not reproduced on Staging env.

1. On UAT server create a chat and send the first message: DIAL\DIALa\DIALb 
2. Refresh the browser 
-> Folder structure is created , chat is moved into the folders and renamed

![image](https://github.com/epam/ai-dial-chat/assets/111180458/79af4c8c-c4b0-4841-98e0-83e29da200b6)

Note: the same is for prompts
Expected result: "\" should be added to no allowed list

--------------------------------------------------------------

**Steps1:**
1. Create a chat. Sent the first message with with special chars. Use restricted chars also. For example, by phrase was "Special chars : ; , = / \ / : * ? " < > | # &"
4. Edit -> Save&Submit the message is chat. Probably several types, but leave special chars in it -> in some iterations error in console and UI-error-message appears. After that folders are created with chats inside -> **bug** 

![image](https://github.com/epam/ai-dial-chat/assets/111180458/3121cc11-51ba-4b99-acf0-ac4c692c5ea4)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/2b9a2d64-5810-4a4b-8a25-32b8df3a65bb)

[epam_ai_dial_(uat)_chat_prompts_history_2-20.json](https://github.com/epam/ai-dial-chat/files/14357480/epam_ai_dial_.uat._chat_prompts_history_2-20.json)
[epam_ai_dial_(uat)_chat_conversations_history_2-20.json](https://github.com/epam/ai-dial-chat/files/14357482/epam_ai_dial_.uat._chat_conversations_history_2-20.json)

**Steps2:**
1. Create chat1 with the fist message, which contains restricted special char. For example, "name/name" -> the chat is renamed automatically, spec chars is removed from the name -> ok
2. Create chat2 with "name:name"
5. Create chat3.... etc After some iterations error appears in console if to click on New conversation

![image](https://github.com/epam/ai-dial-chat/assets/111180458/a5aa18fc-f4ee-42a9-97cd-6be4122bc29f)

**Comment by IlyaBondar** [comment]
@VolhaBazhkova ,
not reproduced. Everything is ok


![Image](https://github.com/epam/ai-dial-chat/assets/20163971/ce870bc7-aa47-4090-acfa-e60caad629f3)

**Comment by VolhaBazhkova** [comment]
Seems it's not reproduced anymore. Experimented on UAT server.

**Comment by VolhaBazhkova** [comment]
@IlyaBondar 
The issue appears on UAT again. 

Created a chat, it was fine several hours, after browser refresh I saw the following:

![image](https://github.com/epam/ai-dial-chat/assets/111180458/cd17a32f-5424-4dff-9265-7539fecc7ea0)

![image](https://github.com/epam/ai-dial-chat/assets/111180458/c36f001a-06f4-487c-9a50-7e82969e6d3a)

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
