### ISSUE TITLE
Need to add an option in Settings to allow to use entire screen width for chat messages and message box

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#83]
We need to add an option in Settings to allow to use entire screen width for chat messages and message box. By default the option should be off. Please find the design here (the link is available for DIAL dev team only): https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=1479-6708&mode=design&t=bvYoJf5FCesvhuAZ-4 

![image](https://github.com/epam/ai-dial-chat/assets/111180458/aea13edc-bd0d-4860-b938-f7de9c3b52b8)

Comment from user (246 internal ticket): `Please consider increase the conversation width, it currently only occupy less than 50% approx. of the visible area width. This drawback becomes quite outstanding when the conversation include table format content, when each column becomes very narrow, it's difficult to read.`

**Comment by VolhaBazhkova** [comment]
Please take care of #143 #144 
Can we fix them at the same time?

**Comment by VolhaBazhkova** [comment]
@denys-kolomiitsev return the feature:


![Image](https://github.com/epam/ai-dial-chat/assets/111180458/d653e681-edf7-48db-ae56-eb17ce5d927b)

**Comment by denys-kolomiitsev** [comment]
The width of the conversation name container depends on the conversation name length. Now default renaming after the first message cuts name at 160th character.
![image](https://github.com/epam/ai-dial-chat/assets/143205282/905c9c3b-a6c1-4576-8887-a4a517e28454)

If manualy rename conversation it will widen to full width.
![image](https://github.com/epam/ai-dial-chat/assets/143205282/8a311d97-2717-4cc2-9136-8f6c8cb11d6f)

TBD: should we increase characters number of the default conversation name.

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
