### ISSUE TITLE
[Core][Share] Folder from "Shared with me" doesn't disappear automatically if to rename original one. Note that chat located in shared folder disappears in this case

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#833]
1. By user1 create folder with chat inside -> share the folder
2. By user2 click on the link -> folder with char appears in Shared with me
3. By user1 renamed the folder -> shared icon disappears (ok)
4. By user2 refresh the browser and note that the chat disappears (ok), but folder is still in "Shared with me" structure -> **bug**

**Expected result:** folder with its elements should disappear from "Shared with me" if the original shared folder was renamed

Note: user2 can delete such folder from Shared with me thru context menu

**Comment by IlyaBondar** [comment]
Related to https://github.com/epam/ai-dial-core/issues/221

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
