### ISSUE TITLE
[Share] shared chat becomes unavailable if to expand shared folder with the chat if it was shared also separately

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#838]
*Preparation:* 

1. By user1 create Folder1 (with chat1 inside)
2. By user1 share Folder1
3. By user1 share Chat1

*Steps:*

1.  By user2 open link with shared folder -> shared folder appears in "Shared with me"
2.  By user2 open link with shared chat -> shared chat appears separately from folder (from previous step) in "Shared with me"
3.  By user2 expand folder -> chat inside folder appears; but separate chat disappears -> **bug**
4.  Refresh the browser -> chat appears again, but if to click on it, it's unavailable -> **bug**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/b0a43347-2751-4a38-8fbe-c1d7b434f16f)

Note: the issue is not reproduced for Prompts

Expected result: these two structures are shared separately, user can work with them separately

**Comment by YauheniyaH** [comment]
Verified on STG, no issues
