### ISSUE TITLE
[Core][Share] Unshared link is still valid though user Unshared it

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#840]
Preparation:
1 By user1 prepare shared chat link
2 By user2 click on the chat link -> the chat appears in Shared with me
3 By user1 unshare the chat
4 By user2 refresh browser -> the chat disappears from Shared with me

Steps:
5 By user2 click on the same shared link -> chat appears in the structure again; shared icon appears in original chat -> **bug**

Expected:  Error appears "We are sorry, but the link you are trying to access has expired or does not exist."

**Comment by IlyaBondar** [comment]
Related to https://github.com/epam/ai-dial-core/issues/221

**Comment by VolhaBazhkova** [comment]
Verified on UAT server successfully
