### ISSUE TITLE
Mobile: Close side panels after selecting a chat or clicking on the profile

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#856]
### EPAM AI DIAL chat version

0.4.2

### How to reproduce

Case 1
1. Open the chat side panel
2. Select or create a chat

Case 2
1. Open the prompt/chat side panel
2. Open the profile panel

### Actual result

![image](https://github.com/epam/ai-dial-chat/assets/151838896/039cc2c6-cbc1-4752-9421-032b6d855901)
![image](https://github.com/epam/ai-dial-chat/assets/151838896/8d39664f-e2d8-48d1-8535-ea6448e97d18)

### Expected result

Case 1
We should close the chat side panel

Case 2
We should close the prompt/chat side panel

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
#856 and #905 were verified successfully. Reported #1010
