### ISSUE TITLE
Support GIF-file rendering as image

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#871]
### Description

Support GIF-file rendering as image
![image](https://github.com/epam/ai-dial-chat/assets/20163971/ffe1b62c-92cd-4da3-9242-3588ab493fc7)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully. ".gif" can be set as logo; send and received in chat. 
![image](https://github.com/epam/ai-dial-chat/assets/111180458/d174ab09-6bf8-423a-962c-9854d4a1e1a7)
