### ISSUE TITLE
Selected model always must be displayed in recent models

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#873]
### EPAM AI DIAL chat version

0.4.2

### How to reproduce

- create 6 chats, each with different model
- open first created chat

### Actual result

5 recent models are displayed and no selected model from them
![image](https://github.com/epam/ai-dial-chat/assets/20163971/dc818541-4b14-4184-a79f-75e5daa6e8e0)

### Expected result

Always max 5 recent models should be displayed.
If selected model is not in recent list then it should be displayed as first + 4 recent models

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Not sure that this ticket was worth to be implemented, now we have regression #1025 . Let's continue discussing expected result there
