### ISSUE TITLE
[Share] It's impossible to create a link for sharing if there is no chat inside the shared folder, but it exists at another folder level

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#874]
### EPAM AI DIAL chat version

0.5.3

### How to reproduce

1. Create "folder 1" and "folder 2";
2. Put a chat into "folder 2" => Put "folder 2" along with chat into "folder 1";
3. Try to create a share link => Note that the loader is spinning endlessly.

### Actual result

The loader is spinning endlessly.
https://github.com/epam/ai-dial-chat/assets/98586297/cf9b3193-cd96-4c68-baef-f5db128c208f

### Expected result

Link should be created

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on UAT for chat and prompts successfully
