### ISSUE TITLE
Move icons to the message bottom for overlay and desktop

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#875]
### Description

![right_icons](https://github.com/epam/ai-dial-chat/assets/151838896/ae0032de-c285-4c26-bf50-4f6061a04abd)
![overlay_right_icons](https://github.com/epam/ai-dial-chat/assets/151838896/1d980c1d-2f09-4a22-b3cd-a7b0661097a5)

Figma: https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=6996%3A10422&mode=design&t=UnBMSP0aaLJrrzXB-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by DaryaKarniyenka** [comment]
Also let's add tooltips for these icons on hover
![image](https://github.com/epam/ai-dial-chat/assets/151838896/83af66e0-cb44-4048-bb14-6a7452d987fe)

**Comment by VolhaBazhkova** [comment]
Verified on staging-overlay and UAT Dial successfully
