### ISSUE TITLE
Change the regenerate button to an icon

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#878]
### Description

Desktop and overlay: show regenerate as an icon at the end of the last message.

![image](https://github.com/epam/ai-dial-chat/assets/151838896/8cd24a66-732d-4c01-83c9-a52af0e9e8ef)

Mobile: show regenerate in the context menu of the last message.

![image](https://github.com/epam/ai-dial-chat/assets/151838896/54411ce3-b4ae-4715-869b-8f3e1e0b1572)

But we should save the current button in an error state.

![image](https://github.com/epam/ai-dial-chat/assets/151838896/bafa8524-2858-4101-b749-1b23108b7557)

Note that the direction of the arrows on the icon should be the same everywhere.

Figma: https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=7001%3A10994&mode=design&t=RF4hNJnIgWjj9svr-1

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. Note that for the errors, there is also nre regenerate button in red colour
