### ISSUE TITLE
"Not allowed model selected" message should be re-designed

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#88]
When the model is not available there should be specific design. Please find it here (the link is available for DIAL dev team only): https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=831-6015&mode=dev

**Now:**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/ce520dc3-e775-420d-8a88-6d1da97a4a6f)

**Expected:**

![image](https://github.com/epam/ai-dial-chat/assets/111180458/a0fe5144-4908-44f8-b006-5f44c2557ac8)

**Comment by avavilau** [comment]
The current design actually makes a lot of sense as it clearly show that there is no model or system failure and this chat is simply a dead end.  Let's discuss.

**Comment by VolhaBazhkova** [comment]
The design was updated. User can not continue the conversation but now two types of error-message can appear: 1) if model is restricted 2) if addon is restricted

![image](https://github.com/epam/ai-dial-chat/assets/111180458/4ff5a57f-3189-4bb6-ab81-ea088abf9bf9)

![image](https://github.com/epam/ai-dial-chat/assets/111180458/a2325a39-8a47-438c-b68b-f146f986b812)
