### ISSUE TITLE
Suppopt all popular image formats for rendering in chat messages

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#883]
### Description

At this moment only `png`, `jpg`, `jpeg` and `gif` files can be expanded to see image:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/7236d3eb-91f8-4538-b390-04c63300a98f)

But we can support all popular image formats which are supported by browsers (+ ICO, BMP...):
![image](https://github.com/epam/ai-dial-chat/assets/20163971/263f4f39-dbe2-4fc4-b095-454370ceecc6)

### Use case/motivation

it looks like EPAM AI DIAL chat is limited and can't work with these popular formats which isn't truth and it was limited by us.
We can extend supported image formats without significant effort (just add these content types in our image types array)

Especcially it would be nice to add support `webp` which supported by `GPT-V`

I don't know any security or other risks are related to it

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Verified possibility to upload and see avif, apng, svg, gif, webp, png, jpeg, ico, tiff, bmp
