### ISSUE TITLE
Place "stop generating" button instead of "send" button when message generating

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#885]
### Description

![image](https://github.com/epam/ai-dial-chat/assets/151838896/8c08b8e1-ec33-4b10-8448-4b2c7d15c586)
 
Also let's add standard tooltip for the icon

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
