### ISSUE TITLE
Need to add custom popups for confirmation actions

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#89]
Need to add custom popups for confirmation actions:
* [ ] Clear conversation in the chat header
* [ ] Delete message in the middle of conversation (seems it was re-implemented)
* [ ] to be continued...

**Comment by IlyaBondar** [comment]
![image](https://github.com/epam/ai-dial-chat/assets/20163971/f863e2bd-c4e6-44b3-a7cf-aec3d59c319c)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/90fb8f16-5a70-4503-bb0e-ee8d7603597a)
![image](https://github.com/epam/ai-dial-chat/assets/20163971/15bf3d4c-8c18-400d-8f78-141415e96967)

Ideally need to create reusable modal component

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully.
Some examples:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/84e22df6-de52-4a9b-af2f-f215a965d517)
![image](https://github.com/epam/ai-dial-chat/assets/111180458/f9ca6fc1-90d4-44e0-adce-9a72101cf43e)
