### ISSUE TITLE
Use only first not empty line for name of conversation

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#912]
### EPAM AI DIAL chat version

0.4.2

### How to reproduce

- create new conversation
- enter some text in input with several lines
- send message

### Actual result

first 160 symbols of message content will be used (or 157 symbols + `...` if more) for new chat name

### Expected result

use only first not empty line for new chat name

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on UAT successfully, but need to updated test cases and auto-tests
