### ISSUE TITLE
Problems with scroll bar on long conversations

### ISSUE THREAD

**Issue by sergeev0** [epam/ai-dial-chat#949]
### EPAM AI DIAL chat version

0.5.3

### What happened?

Issue Description
In long conversations, while you scroll down, the right-side scrollbar gets smaller and smaller and even disappears in case of very long conversations.

Steps to Reproduce
Create a long conversation with any model. Try using the scroll bar as the chat gets longer.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The implementation of scroll bar was changed:
![image](https://github.com/epam/ai-dial-chat/assets/111180458/c0a58b50-bca4-4a65-9c75-1ec3bc780558)
