### ISSUE TITLE
When setting up custom prompts, if a variable is defined multiple times, a new occurrence of a variable becomes 'undefined' when the user enters values in the prompt

### ISSUE THREAD

**Issue by sergeev0** [epam/ai-dial-chat#950]
### EPAM AI DIAL chat version

0.5.3

### What happened?

Issue Description
When setting up custom prompts, if a variable is defined multiple times, a new occurrence of a variable becomes 'undefined' when the user enters values in the prompt. Furthermore, if there are multiple new variables after the variable which is defined multiple times, the first new variable will take the value of the one after it, and this pattern will continue until the last variable, which will then become 'undefined'.

Steps to Reproduce
1. Click on New Prompt to create a new custom prompt.
2. Type your prompt, making sure to repeat one variable and to add a new variable after it, for example: “write this text: ‘Hello, {{name}}, the product is called {{product}}. The price is {{price}}$. {{product}} is available in {{country}}.’”
3. Save your custom prompt.
4. Type ‘/’ in the chatbox and select your custom prompt.
5. Input the values for each of the variables in the pop up window.
6. Your prompt should appear in the chatbox and the value for {{country}} should be ‘undefined’

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully. In 0.7.0 version custom prompt is applied correctly (without ‘undefined’ value).
