### ISSUE TITLE
UI Freezes if custom app response is not received within ~20s

### ISSUE THREAD

**Issue by sergeev0** [epam/ai-dial-chat#951]
### EPAM AI DIAL chat version

0.5.3

### What happened?

Issue Description
UI Freezes if custom app response is not received within ~20s

Steps to Reproduce
Create a custom DIAL app that takes around 20s to send response to DIAL.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
@sergeev0 , could you provide more details, please. Which model/application, what the message/question/content(in ideal case you can export your conversation and attach to this issue) and what does "UI Freezes" look like?

During answer generation we block any options on conversation bar and prompt bar and it's expected. 
Also we have long timeout. 
But you still have "stop generation" button:
version 0.6:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/2a3ba325-a692-4191-ae3b-538636cdef96)
version 0.5:
![image](https://github.com/epam/ai-dial-chat/assets/20163971/c1aabc56-e389-47a3-8082-50985c1d1b18)

**Comment by souhail-bougrine** [comment]
@IlyaBondar I have reported this issue to @sergeev0 originally. The "freeze" happens when a custom app developed using the ai dial sdk (very similar to the example echo app) doesn't send a response within 25~30s. The chat is stuck in the text generation status (the icon blinking) and is no longer responsive. the "stop generation" button does not work and the only way to get out of the situation is to refresh the page and edit the user message and resend it.

**Comment by photonn** [comment]
Hi! same situation here. We have a custom RAG application developed with ai-dial-sdk and we think the limit is around 30 secs. Which looks like some kind of default timeout somewhere on the code. 

   In our case, we are 100% sure that the application microservice is making back a POST to chat when it finish, is just that if the request is longer than 30 secs, it gets ignored and the UI freeze. Our chat version is 0.8.2

**Comment by photonn** [comment]
found issue in a default config in azure appgw:

https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-annotations?source=recommendations#request-timeout

You can close this bug.

**Comment by sdryapko** [comment]
Closing based on comment above. Issue is not related to dial-chat.
