### ISSUE TITLE
Forced scroll in chat window

### ISSUE THREAD

**Issue by sergeev0** [epam/ai-dial-chat#953]
### EPAM AI DIAL chat version

0.5.3

### What happened?

Issue Description
The screen keeps forcibly being scrolled to the bottom and the newest generated content. It should stay on the user’s screen selection as soon as they scroll up.

Steps to Reproduce
Instruct LLM to generate a big chunk of text. Try to scroll up to the beginning of the generated response while it is still being generated.

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
This issue was fixed in version `0.6`.
