### ISSUE TITLE
Spaces are cut in prompt and chat names on panels, Share, Publish; folders , e.g. "Prompt     1" is shown as "Prompt 1"

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#973]
### EPAM AI DIAL chat version

0.7.0

### What happened?

Create a prompt with the name  `Prompt       1`  -> Note that on Prompt panel is looks like `Prompt 1`

![image_2024-03-07_102140216](https://github.com/epam/ai-dial-chat/assets/111180458/a2c52705-1120-4151-b41c-3165f7105ea3)

Note: the same issue is for conversations and prompt/chat folders
Note: the same issue if to open Share pop-up, please check also Publish

Expected: spaces should not be cut on panels view

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by IlyaBondar** [comment]
@VolhaBazhkova  I've already fixed it in sidebar, but we need to double-check all places where chat/propmpt/folder/file names are displayed
![image](https://github.com/epam/ai-dial-chat/assets/20163971/f4393c2b-3577-4111-9d0f-7fbeed1d3e1f)

**Comment by VolhaBazhkova** [comment]
Reported #1090

**Comment by VolhaBazhkova** [comment]
Verified on staging successfully
