### ISSUE TITLE
On Mobile "X" appears instead of user photo if the menu is opened

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#98]
1. Open the app on any mobile
2. Click on user photo -\> the menu is opened (ok), user photo is changed to "x" icon (bug)

![image](https://github.com/epam/ai-dial-chat/assets/111180458/81e70577-5594-4131-ab0c-d542e464fdf3)

**Expected result**: the photo should stay

![image](https://github.com/epam/ai-dial-chat/assets/111180458/6f91c174-333a-417d-a5bf-4c14019c14a2)

Figma link is available for DIAL dev team ony: https://www.figma.com/file/lwL5jneveZczAj5RLcLFH2/DIAL-Chat?type=design&node-id=90-1380&mode=design&t=rNsgVx1ygcEE88vr-0

**Comment by DaryaKarniyenka** [comment]
We should show cross in the header and profile photo instead of the profile icon.
![image](https://github.com/epam/ai-dial-chat/assets/151838896/2f320c66-9b6b-48db-81c3-04b2bbf2ed93)

**Comment by VolhaBazhkova** [comment]
Verified on staging nd UAT successfully
![image](https://github.com/epam/ai-dial-chat/assets/111180458/b7e14044-0e60-4124-9de5-cdd29f41cde9)
