### ISSUE TITLE
[Shared] Shared prompt folder structure is duplicated if to clear all prompts via Delete all button on the panel

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#986]
### EPAM AI DIAL chat version

0.6.7

### What happened?

1. Prepare folder and chats to be in "shared with me"; create some prompts
2. Click on Delete all button to clear all prompts
3. Note that prompts in Recent are deleted and "Shared with me" stays -> ok; but prompt folder structure is duplicated -> **bug**

Note: single shared prompt is not duplicated -> ok
Note: it's not reproduced for shared chats

![image](https://github.com/epam/ai-dial-chat/assets/111180458/4f7728ad-1b42-4b36-927e-a9b738886201)

**Expected:** no duplicates

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
Verified on STG version 0.10.0
