### ISSUE TITLE
Overlay missing parts

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#99]
During implementing more complex overlay logic we lost next things:

1. Showing button for opening overlay
2. Showing animation when showing overlay
3. Showing header with next buttons there: full screen and minimize

**Comment by VolhaBazhkova** [comment]
Verified on rail landing page (staging) successfully.

**Comment by AnastasiiaHarkot** [comment]
**QA Verification — Fixed ✅**

**Verified by:** AnastasiiaHarkot
**Date:** 2026-09-04
**Result:** Overlay missing parts issue is resolved.

**Verdict: Fixed** — verified.
